In [1]:
import os
import sys
import numpy as np
import pandas as pd
import geopandas as gpd

sys.path.append("../utils")

pd.set_option("display.max_columns", None)

In [2]:
# CHUNK FOR BUFFER_GEOMETRIES; RUN IF USING BUFFER_GEOMETRIES, NOT TRAINING_GEOMETRIES
# Loading in inspections data with newly calculated geometries 4/29/25

insp_19 = gpd.read_file(
    "/capstone/wildfire_prep/data/buffer_geometries/buffer_geometries_2019.geojson"
)
insp_20 = gpd.read_file(
    "/capstone/wildfire_prep/data/buffer_geometries/buffer_geometries_2020.geojson"
)
insp_21 = gpd.read_file(
    "/capstone/wildfire_prep/data/buffer_geometries/buffer_geometries_2021.geojson"
)
insp_22 = gpd.read_file(
    "/capstone/wildfire_prep/data/buffer_geometries/buffer_geometries_2022.geojson"
)
insp_23 = gpd.read_file(
    "/capstone/wildfire_prep/data/buffer_geometries/buffer_geometries_2023.geojson"
)

insp_19.head()

,fulcrum_id,created_at,updated_at,system_cre,system_upd,version,status,project,assigned_t,latitude,longitude,report_tit,globalid,calculated,inspectorp,inspection,addressvis,address_su,address_th,address__1,address_lo,address__2,address_ad,address_po,address_co,address_fu,calfireuni,county,community,community_,battalion,enginenumb,stationnam,stationn_1,shift,occupantho,deliveryno,inspecti_1,a_removebr,b_removele,c_removede,d_removede,e_removedy,f_removefl,g_relocate,h_cutannua,i_reducefu,j_allexpos,k_deaddyin,l_logsstum,m_outbuild,n_addressd,o_chimneys,recommend_,propanetan,accessegre,waterstora,water_sour,can_engine,water_stor,water_comm,structuret,roofconstr,eaves,ventscreen,exteriorsi,windowpane,deckporchg,deckporche,patiocover,fenceattac,utilitymis,utilitym_1,nonhabitab,escalateto,reinspecti,clearreins,citationnu,citationda,deadtrees3,photoid,photoid_ca,le100numbe,inspecti_2,coredatafl,partner_di,principal_,firescopei,responsibi,yearbuilt,siteaddres,numberofst,appenddate,editstatus,createddat,createdby,editeddate,editedby,textfield1,textfield2,numberfiel,numberfi_1,core_with_,Date,year,keyid,propertyst,e_removefl,i_removefu,j_exposedw,k_removede,l_removelo,n_displaya,o_stovepip,recommendc,structureh,inspecti_3,coredata,calculat_1,calculat_2,previousyr,previous_1,calculat_3,calculat_4,creationda,editdate,creator,editor,number_of_,shift_juli,created_by,updated_by,system_created_at,system_updated_at,assigned_to,report_title,propertystatus,inspectionstatus,inspectorfirstname,inspectorlastname,prevention_inspectorfirstname,prevention_inspectorfirstname_other,prevention_inspectorlastname,prevention_inspectorlastname_other,inspectorposition,inspectiondate_calculate,addressvisible,address_sub_thoroughfare,address_thoroughfare,address_suite,address_locality,address_sub_admin_area,address_admin_area,address_postal_code,address_country,address_full,calfireunit,community_other,enginenumber,stationname,shift_julian,accessegress,occupanthome,deliverynotificationmethod,inspectionhours,a_removebranchesfromstovepipe,b_removeleavesneedlesveg,c_removedeaddyingtrees,d_removedeaddyinggrassplants,e_removeflammablegroundcover,f_removeflammablevegetation,g_relocateexposedwoodpiles,h_cutannualgrassesforbs,i_removefuelsusingctguidelines,j_exposedwoodpiles,k_removedeaddyingwoodyfuels,l_removelogstumpsembeddedsoil,m_outbuildingsliquidpropanegas,n_displayaddresscontrasting,o_stovepipemetalscreenopenings,recommendclearvegetation,water_source,can_engine_access_water_source,water_storage_size_stored_water_on_individual_parcels_only,water_comments,structuretype,structurehabitable,roofconstruction,exteriorsiding,deckporchgrade,deckporchelevated,patiocovercarport,fenceattachedtostructure,propanetankdistance,utilitymiscstructuredistance,utilitymiscstucturecount,nonhabitableoutbuildings,escalatetocoordinator,reinspectiondate,citationnumber,number_of_dead_trees_within_300_ft_of_residence,gatecode,comments,photoid_caption,photoid_url,le100number,inspectioncount,firescopeid,siteaddress,numberofstructures,calculatedglobalid,calculateddate,calculateduid,numberfield1,numberfield2,previousyrinspecteddata,previousyrinspectionstatus,calculatededitor,calculatededitdate,creationdate,inspection_id,month,apn,geometry
0,d9a4d031-d16d-4c84-b32c-f3fcd7d945df,2018-05-25 16:25:06,2019-06-05 11:57:49,2019-05-07 11:52:36,2019-06-05 16:35:26,2.0,Compliant,None,None,34.669616,-120.031160,Defensible Space Inspection Report,None,None,DSI,2019-06-05,Yes - Without Reflective,3462,Brinkerhoff Rd,None,Santa Ynez,Santa Barbara,CA,93460,US,3462 Brinkerhoff Rd Santa Ynez Santa Barbara C...,SBC,SBA,Woodstock,None,2,32,32,None,None,Yes,Hardcopy,30 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,>30',yes,yes,Private Hydrant- Private Stored Water,yes,Over 5000 gallons,None,Utility or Miscellaneous Structure > 120 sqft,Metal,Unenclosed,No Vents,Wood,No Windows,No Deck/Porch,No Deck/Porch,No Patio Cover/Carport,No Fence,30-50',0,0,None,NaT,None,None,None,0,None,None,0.0,0.0,None,None,None,None,None,2000.0,None,0.0,2019-06-05,None,None,None,None,None,None,None,0.0,0.0,None,2019-06-05,2019,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,1,6,141-010-040,"POLYGON ((-2813.179 -371821.557, -2813.179 -37..."
1,7f9b6d98-548d-4b94-97c6-82cbddf84d99,2018-05-25 16:25:10,2019-05-15 12:26:44,2019-05-07 11:52:37,2019-05-15 12:26:45,3.0,Compliant,None,None,34.679129,-120.091914,Defensible Space Inspection Report,None,None,DSI,2019-05-09,Yes - Without Reflective,3290,Avenida Caballo,None,Santa Ynez,Santa Barbara,CA,93460,US,3290 Avenida Caballo Santa Ynez Santa Barbara ...,SBC,SBA,Woodstock,None,2,32,Santa Ynez Valley (Outside Engine Co. Area),None,None,No,Email,15 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Not Applicable,yes,yes,Private Hydrant- Private Stored Water,yes,None,None,Single Family Residence Multi Story,Metal,No Eaves,No Vents,Wood,Single Pane,No Deck/Porch,No Deck/Porch,No Patio Cover/Carport,No Fence,30-50',1,0,None,NaT,None,None,None,None,f1556c16-78c8-44bf-b6ce-a7ddb5908d96,None,0.0,0.0,None,None,None,None,None,0.0,None,0.0,2019-05-09,None,None,None,None,None,None,None,0.0,0.0,None,2019-05-09,2019,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2,5,135-310-022,"POLYGON ((-8368.416 -370860.259, -8475.394 -37..."
2,03afdf39-173a-4f02-bfdc-e0725e554959,2018-05-25 16:25:11,2019-05-09 14:20:04,2019-05-07 11:52:37,2019-05-09 15:26:24,2.0,Compliant,None,None,34.676197,-120.089553,Defensible Space Inspection Report,None,None,DSI,2019-05-09,Yes - Without Reflective,3350,Caballo Ln,None,Santa Ynez,Santa Barbara,CA,93460,US,3350 Caballo Ln Santa Ynez Santa Barbara CA 93...,SBC,SBA,Woodstock,None,2,32,Santa Ynez Valley (Outside Engine Co. Area),None,None,No,Email,15 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Not Applicable,yes,None,None,None,None,None,Single Family Residence Multi Story,Tile,Unenclosed,No Vents,Stucco/Brick/Cement,Multi Pane,No Deck/Porch,No Deck/Porch,No Patio Cover/Carport,No Fence,>50',2,0,None,NaT,None,None,None,None,None,None,0.0,0.0,None,None,None,None,None,0.0,None,0.0,2019-05-09,None,None,None,None,None,None,None,0.0,0.0,None,2019-05-09,2019,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,3,5,135-310-075,"POLYGON ((-8253.618 -371073.707, -8136.129 -37..."
3,941e29b0-6cd3-4c7e-a919-b8f2410b4a2b,2018-05-25 16:25:11,2019-05-09 14:25:18,2019-05-07 11:52:38,2019-05-09 15:26:26,2.0,Compliant,None,None,34.677982,-120.088944,Defensible Space Inspection Report,None,None,DSI,2019-05-09,Yes - Without Reflective,3350,Caballo Ln,None,Santa Ynez,Santa Barbara,CA,93460,US,3350 Caballo Ln Santa Ynez Santa Barbara CA 93...,SBC,SBA,Woodstock,None,2,32,Santa Ynez Valley (Outside Engine Co. Area),None,None,Yes,Email,15 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Not Applicable,yes,no,None,None,None,None,Utility or Miscellaneous Structure > 120 sqft,Metal,Unenclosed,No Vents,Metal,Single Pane,Masonry/Concrete,No Deck/Porch,No Patio Cover/Carport,No Fence,None,0,0,None,NaT,None,None,None,None,17322007-d5d1-4568-bde6-00ae169a0bbf,None,0.0,0.0,None,None,None,None,None,0.0,None,0.0,2019-05-09,None,None,None,None,None,None,None,0.0,0.0,None,2019-05-09,2019,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,4,5,135-310-075,"POLYGON ((-8201.866 -370989.432, -8201.866 -37..."
4,abe890ba-3269-4ef6-84d7-4a9b6bfd717e,2018-05-25 16:25:11,2019-12-17 14:16:14,2019-05-07 11:52:38,2019-12-18 11:43:23,5.0,Compliant,None,None,34.678469,-120.087539,Defensible Space Inspection Report,None,None,DSI,2019-12-17,Yes - Without Reflective,3320 A,Canada Este Rd,None,Santa Ynez,Santa Barbara,CA,93460,US,3320 A Canada Este Rd Santa Ynez Santa Barbara...,SBC,SBA,Woodstock,None,2,32,Santa Ynez Valley (Outside Engine Co. Area),None,None,No,Hardcopy,5 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,>30',yes,yes,Pond,None,None,None,Single Family Residence Multi Story,Asphalt,Unenclosed,"Mesh Screen > 1/8""",Wood,Single Pane,Masonry/Concrete,No Deck/Porch,Non Combustible,No Fence,None,0,0,None,NaT,None,None,None,None,50114b4c-e04a-4054-bd54-5a7dbca535af,None,0.0,0.0,None,None,None,None,None,2002.0,None,0.0,2019-05-08,None,None,None,None,None,None,None,0.0,0.0,None,2019-12-17,2019,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,5,12,135-310-042,"POLYGON ((-7966.144 -370818.558, -7966.144 -37..."

In [3]:
# LOADING TRAINING GEOMETRIES INSTEAD
# insp_19 = gpd.read_file(
#     "/capstone/wildfire_prep/data/training_geometries/training_geometries_2019.geojson"
# )
# insp_20 = gpd.read_file(
#     "/capstone/wildfire_prep/data/training_geometries/training_geometries_2020.geojson"
# )
# insp_21 = gpd.read_file(
#     "/capstone/wildfire_prep/data/training_geometries/training_geometries_2021.geojson"
# )
# insp_22 = gpd.read_file(
#     "/capstone/wildfire_prep/data/training_geometries/training_geometries_2022.geojson"
# )
# insp_23 = gpd.read_file(
#     "/capstone/wildfire_prep/data/training_geometries/training_geometries_2023.geojson"
# )

In [4]:
rows19 = len(insp_19)
rows20 = len(insp_20)
rows21 = len(insp_21)
rows22 = len(insp_22)
rows23 = len(insp_23)

geometries_length = rows19 + rows20 + rows21 + rows22 + rows23
print(geometries_length)

67580

In [5]:
insp_19.head()

,fulcrum_id,created_at,updated_at,system_cre,system_upd,version,status,project,assigned_t,latitude,longitude,report_tit,globalid,calculated,inspectorp,inspection,addressvis,address_su,address_th,address__1,address_lo,address__2,address_ad,address_po,address_co,address_fu,calfireuni,county,community,community_,battalion,enginenumb,stationnam,stationn_1,shift,occupantho,deliveryno,inspecti_1,a_removebr,b_removele,c_removede,d_removede,e_removedy,f_removefl,g_relocate,h_cutannua,i_reducefu,j_allexpos,k_deaddyin,l_logsstum,m_outbuild,n_addressd,o_chimneys,recommend_,propanetan,accessegre,waterstora,water_sour,can_engine,water_stor,water_comm,structuret,roofconstr,eaves,ventscreen,exteriorsi,windowpane,deckporchg,deckporche,patiocover,fenceattac,utilitymis,utilitym_1,nonhabitab,escalateto,reinspecti,clearreins,citationnu,citationda,deadtrees3,photoid,photoid_ca,le100numbe,inspecti_2,coredatafl,partner_di,principal_,firescopei,responsibi,yearbuilt,siteaddres,numberofst,appenddate,editstatus,createddat,createdby,editeddate,editedby,textfield1,textfield2,numberfiel,numberfi_1,core_with_,Date,year,keyid,propertyst,e_removefl,i_removefu,j_exposedw,k_removede,l_removelo,n_displaya,o_stovepip,recommendc,structureh,inspecti_3,coredata,calculat_1,calculat_2,previousyr,previous_1,calculat_3,calculat_4,creationda,editdate,creator,editor,number_of_,shift_juli,created_by,updated_by,system_created_at,system_updated_at,assigned_to,report_title,propertystatus,inspectionstatus,inspectorfirstname,inspectorlastname,prevention_inspectorfirstname,prevention_inspectorfirstname_other,prevention_inspectorlastname,prevention_inspectorlastname_other,inspectorposition,inspectiondate_calculate,addressvisible,address_sub_thoroughfare,address_thoroughfare,address_suite,address_locality,address_sub_admin_area,address_admin_area,address_postal_code,address_country,address_full,calfireunit,community_other,enginenumber,stationname,shift_julian,accessegress,occupanthome,deliverynotificationmethod,inspectionhours,a_removebranchesfromstovepipe,b_removeleavesneedlesveg,c_removedeaddyingtrees,d_removedeaddyinggrassplants,e_removeflammablegroundcover,f_removeflammablevegetation,g_relocateexposedwoodpiles,h_cutannualgrassesforbs,i_removefuelsusingctguidelines,j_exposedwoodpiles,k_removedeaddyingwoodyfuels,l_removelogstumpsembeddedsoil,m_outbuildingsliquidpropanegas,n_displayaddresscontrasting,o_stovepipemetalscreenopenings,recommendclearvegetation,water_source,can_engine_access_water_source,water_storage_size_stored_water_on_individual_parcels_only,water_comments,structuretype,structurehabitable,roofconstruction,exteriorsiding,deckporchgrade,deckporchelevated,patiocovercarport,fenceattachedtostructure,propanetankdistance,utilitymiscstructuredistance,utilitymiscstucturecount,nonhabitableoutbuildings,escalatetocoordinator,reinspectiondate,citationnumber,number_of_dead_trees_within_300_ft_of_residence,gatecode,comments,photoid_caption,photoid_url,le100number,inspectioncount,firescopeid,siteaddress,numberofstructures,calculatedglobalid,calculateddate,calculateduid,numberfield1,numberfield2,previousyrinspecteddata,previousyrinspectionstatus,calculatededitor,calculatededitdate,creationdate,inspection_id,month,apn,geometry
0,d9a4d031-d16d-4c84-b32c-f3fcd7d945df,2018-05-25 16:25:06,2019-06-05 11:57:49,2019-05-07 11:52:36,2019-06-05 16:35:26,2.0,Compliant,None,None,34.669616,-120.031160,Defensible Space Inspection Report,None,None,DSI,2019-06-05,Yes - Without Reflective,3462,Brinkerhoff Rd,None,Santa Ynez,Santa Barbara,CA,93460,US,3462 Brinkerhoff Rd Santa Ynez Santa Barbara C...,SBC,SBA,Woodstock,None,2,32,32,None,None,Yes,Hardcopy,30 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,>30',yes,yes,Private Hydrant- Private Stored Water,yes,Over 5000 gallons,None,Utility or Miscellaneous Structure > 120 sqft,Metal,Unenclosed,No Vents,Wood,No Windows,No Deck/Porch,No Deck/Porch,No Patio Cover/Carport,No Fence,30-50',0,0,None,NaT,None,None,None,0,None,None,0.0,0.0,None,None,None,None,None,2000.0,None,0.0,2019-06-05,None,None,None,None,None,None,None,0.0,0.0,None,2019-06-05,2019,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,1,6,141-010-040,"POLYGON ((-2813.179 -371821.557, -2813.179 -37..."
1,7f9b6d98-548d-4b94-97c6-82cbddf84d99,2018-05-25 16:25:10,2019-05-15 12:26:44,2019-05-07 11:52:37,2019-05-15 12:26:45,3.0,Compliant,None,None,34.679129,-120.091914,Defensible Space Inspection Report,None,None,DSI,2019-05-09,Yes - Without Reflective,3290,Avenida Caballo,None,Santa Ynez,Santa Barbara,CA,93460,US,3290 Avenida Caballo Santa Ynez Santa Barbara ...,SBC,SBA,Woodstock,None,2,32,Santa Ynez Valley (Outside Engine Co. Area),None,None,No,Email,15 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Not Applicable,yes,yes,Private Hydrant- Private Stored Water,yes,None,None,Single Family Residence Multi Story,Metal,No Eaves,No Vents,Wood,Single Pane,No Deck/Porch,No Deck/Porch,No Patio Cover/Carport,No Fence,30-50',1,0,None,NaT,None,None,None,None,f1556c16-78c8-44bf-b6ce-a7ddb5908d96,None,0.0,0.0,None,None,None,None,None,0.0,None,0.0,2019-05-09,None,None,None,None,None,None,None,0.0,0.0,None,2019-05-09,2019,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2,5,135-310-022,"POLYGON ((-8368.416 -370860.259, -8475.394 -37..."
2,03afdf39-173a-4f02-bfdc-e0725e554959,2018-05-25 16:25:11,2019-05-09 14:20:04,2019-05-07 11:52:37,2019-05-09 15:26:24,2.0,Compliant,None,None,34.676197,-120.089553,Defensible Space Inspection Report,None,None,DSI,2019-05-09,Yes - Without Reflective,3350,Caballo Ln,None,Santa Ynez,Santa Barbara,CA,93460,US,3350 Caballo Ln Santa Ynez Santa Barbara CA 93...,SBC,SBA,Woodstock,None,2,32,Santa Ynez Valley (Outside Engine Co. Area),None,None,No,Email,15 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Not Applicable,yes,None,None,None,None,None,Single Family Residence Multi Story,Tile,Unenclosed,No Vents,Stucco/Brick/Cement,Multi Pane,No Deck/Porch,No Deck/Porch,No Patio Cover/Carport,No Fence,>50',2,0,None,NaT,None,None,None,None,None,None,0.0,0.0,None,None,None,None,None,0.0,None,0.0,2019-05-09,None,None,None,None,None,None,None,0.0,0.0,None,2019-05-09,2019,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,3,5,135-310-075,"POLYGON ((-8253.618 -371073.707, -8136.129 -37..."
3,941e29b0-6cd3-4c7e-a919-b8f2410b4a2b,2018-05-25 16:25:11,2019-05-09 14:25:18,2019-05-07 11:52:38,2019-05-09 15:26:26,2.0,Compliant,None,None,34.677982,-120.088944,Defensible Space Inspection Report,None,None,DSI,2019-05-09,Yes - Without Reflective,3350,Caballo Ln,None,Santa Ynez,Santa Barbara,CA,93460,US,3350 Caballo Ln Santa Ynez Santa Barbara CA 93...,SBC,SBA,Woodstock,None,2,32,Santa Ynez Valley (Outside Engine Co. Area),None,None,Yes,Email,15 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Not Applicable,yes,no,None,None,None,None,Utility or Miscellaneous Structure > 120 sqft,Metal,Unenclosed,No Vents,Metal,Single Pane,Masonry/Concrete,No Deck/Porch,No Patio Cover/Carport,No Fence,None,0,0,None,NaT,None,None,None,None,17322007-d5d1-4568-bde6-00ae169a0bbf,None,0.0,0.0,None,None,None,None,None,0.0,None,0.0,2019-05-09,None,None,None,None,None,None,None,0.0,0.0,None,2019-05-09,2019,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,4,5,135-310-075,"POLYGON ((-8201.866 -370989.432, -8201.866 -37..."
4,abe890ba-3269-4ef6-84d7-4a9b6bfd717e,2018-05-25 16:25:11,2019-12-17 14:16:14,2019-05-07 11:52:38,2019-12-18 11:43:23,5.0,Compliant,None,None,34.678469,-120.087539,Defensible Space Inspection Report,None,None,DSI,2019-12-17,Yes - Without Reflective,3320 A,Canada Este Rd,None,Santa Ynez,Santa Barbara,CA,93460,US,3320 A Canada Este Rd Santa Ynez Santa Barbara...,SBC,SBA,Woodstock,None,2,32,Santa Ynez Valley (Outside Engine Co. Area),None,None,No,Hardcopy,5 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,>30',yes,yes,Pond,None,None,None,Single Family Residence Multi Story,Asphalt,Unenclosed,"Mesh Screen > 1/8""",Wood,Single Pane,Masonry/Concrete,No Deck/Porch,Non Combustible,No Fence,None,0,0,None,NaT,None,None,None,None,50114b4c-e04a-4054-bd54-5a7dbca535af,None,0.0,0.0,None,None,None,None,None,2002.0,None,0.0,2019-05-08,None,None,None,None,None,None,None,0.0,0.0,None,2019-12-17,2019,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,5,12,135-310-042,"POLYGON ((-7966.144 -370818.558, -7966.144 -37..."

In [6]:
insp_23.head()

,fulcrum_id,created_at,updated_at,system_cre,system_upd,version,status,project,assigned_t,latitude,longitude,report_tit,globalid,calculated,inspectorp,inspection,addressvis,address_su,address_th,address__1,address_lo,address__2,address_ad,address_po,address_co,address_fu,calfireuni,county,community,community_,battalion,enginenumb,stationnam,stationn_1,shift,occupantho,deliveryno,inspecti_1,a_removebr,b_removele,c_removede,d_removede,e_removedy,f_removefl,g_relocate,h_cutannua,i_reducefu,j_allexpos,k_deaddyin,l_logsstum,m_outbuild,n_addressd,o_chimneys,recommend_,propanetan,accessegre,waterstora,water_sour,can_engine,water_stor,water_comm,structuret,roofconstr,eaves,ventscreen,exteriorsi,windowpane,deckporchg,deckporche,patiocover,fenceattac,utilitymis,utilitym_1,nonhabitab,escalateto,reinspecti,clearreins,citationnu,citationda,deadtrees3,photoid,photoid_ca,le100numbe,inspecti_2,coredatafl,partner_di,principal_,firescopei,responsibi,yearbuilt,siteaddres,numberofst,appenddate,editstatus,createddat,createdby,editeddate,editedby,textfield1,textfield2,numberfiel,numberfi_1,core_with_,Date,year,keyid,propertyst,e_removefl,i_removefu,j_exposedw,k_removede,l_removelo,n_displaya,o_stovepip,recommendc,structureh,inspecti_3,coredata,calculat_1,calculat_2,previousyr,previous_1,calculat_3,calculat_4,creationda,editdate,creator,editor,number_of_,shift_juli,created_by,updated_by,system_created_at,system_updated_at,assigned_to,report_title,propertystatus,inspectionstatus,inspectorfirstname,inspectorlastname,prevention_inspectorfirstname,prevention_inspectorfirstname_other,prevention_inspectorlastname,prevention_inspectorlastname_other,inspectorposition,inspectiondate_calculate,addressvisible,address_sub_thoroughfare,address_thoroughfare,address_suite,address_locality,address_sub_admin_area,address_admin_area,address_postal_code,address_country,address_full,calfireunit,community_other,enginenumber,stationname,shift_julian,accessegress,occupanthome,deliverynotificationmethod,inspectionhours,a_removebranchesfromstovepipe,b_removeleavesneedlesveg,c_removedeaddyingtrees,d_removedeaddyinggrassplants,e_removeflammablegroundcover,f_removeflammablevegetation,g_relocateexposedwoodpiles,h_cutannualgrassesforbs,i_removefuelsusingctguidelines,j_exposedwoodpiles,k_removedeaddyingwoodyfuels,l_removelogstumpsembeddedsoil,m_outbuildingsliquidpropanegas,n_displayaddresscontrasting,o_stovepipemetalscreenopenings,recommendclearvegetation,water_source,can_engine_access_water_source,water_storage_size_stored_water_on_individual_parcels_only,water_comments,structuretype,structurehabitable,roofconstruction,exteriorsiding,deckporchgrade,deckporchelevated,patiocovercarport,fenceattachedtostructure,propanetankdistance,utilitymiscstructuredistance,utilitymiscstucturecount,nonhabitableoutbuildings,escalatetocoordinator,reinspectiondate,citationnumber,number_of_dead_trees_within_300_ft_of_residence,gatecode,comments,photoid_caption,photoid_url,le100number,inspectioncount,firescopeid,siteaddress,numberofstructures,calculatedglobalid,calculateddate,calculateduid,numberfield1,numberfield2,previousyrinspecteddata,previousyrinspectionstatus,calculatededitor,calculatededitdate,creationdate,inspection_id,month,apn,geometry
0,48c58877-f0ce-438d-ac87-6434a2c15fe8,2022-02-13 16:00:00,2023-06-05 17:00:00,None,None,13.0,Compliant,None,None,34.461625,-119.772555,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,SBA,San Marcos Foothills,None,1,None,None,None,A,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,yes,None,None,None,None,None,None,Enclosed,"Mesh Screen <= 1/8""",None,Single Pane,None,None,None,None,None,None,None,None,None,None,None,None,None,"eb994fe9-6273-444c-95b7-c3633b0876f5,de1dc62a-...",None,None,None,None,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,2023-06-05,2023,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-02-14,None,None,None,None,gis@sbcfire.com,gis@sbcfire.com,2022-02-14 10:44:17,2023-12-06 08:54:05,None,Defensible Space Inspection Report,None,None,None,None,Charlotte,None,Endicott,None,DSI,2023-06-05,Yes - Without Reflective,4440,Shadow Hills Cir,None,Santa Barbara,Santa Barbara,CA,93105,US,4440 Shadow Hills Cir Santa Barbara Santa Barb...,SBC,None,NaN,13,157,Yes,No,Mailed,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Hydrant- Municipal/Public Water Supply,yes,None,None,Multi Family Residence Multi Story,Habitable,Tile,Other,Masonry/Concrete,Masonry/Concrete,Non Combustible,No Fence,Not Applicable,None,0,0,None,NaT,None,0.0,None,None,",,",https://web.fulcrumapp.com/photos/view?photos=...,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-02-14,54208,6,059-400-CA1,"POLYGON ((20868.535 -394953.139, 20855.399 -39..."
1,f351800c-fc5c-4b79-bf24-a41775b74d7c,2022-04-04 17:00:00,2023-10-06 09:47:59,None,None,8.0,Compliant,None,None,34.672591,-120.108711,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,SBA,Los Olivos,None,3,None,None,None,B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,yes,None,None,None,None,None,None,Unenclosed,No Vents,None,Single Pane,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,1980.0,None,None,None,None,None,None,None,None,None,None,None,None,None,2023-10-06,2023,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2020-07-08,None,None,None,None,gis@sbcfire.com,sbc.dsp.inspector@sbcfire.com,2022-04-05 13:47:06,2023-10-06 09:55:52,None,Defensible Space Inspection Report,None,None,None,None,None,None,Gailey,None,Prevention,2023-10-06,Yes - Without Reflective,3110 A,Acampo Rd,None,Santa Ynez,Santa Barbara,CA,93441,US,3110 A Acampo Rd Santa Ynez Santa Barbara CA 9...,SBC,None,32.0,Santa Ynez Valley (Outside Engine Co. Area),279,Yes,No,Hardcopy,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Hydrant- Municipal/Public Water Supply,yes,None,None,Single Family Residence Single Story,Habitable,Tile,Stucco/Brick/Cement,Masonry/Concrete,No Deck/Porch,Combustible,Combustible,Not Applicable,None,0,0,None,NaT,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-09-05,54209,10,135-330-020,"POLYGON ((-9914.183 -371474.708, -9914.183 -37..."
2,b97b5b98-bda4-4b41-b850-3fdb36c9f689,2022-04-04 17:00:00,2023-10-06 09:39:32,None,None,8.0,Compliant,None,None,34.668610,-120.115221,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,SBA,Los Olivos,None,3,None,None,None,B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,yes,None,None,None,None,None,None,Unenclosed,"Mesh Screen > 1/8""",None,Multi Pane,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,1991.0,None,None,None,None,None,None,None,None,None,None,None,None,None,2023-10-06,2023,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2020-07-08,None,None,None,None,gis@sbcfire.com,sbc.dsp.inspector@sbcfire.com,2022-04-05 13:47:07,2023-10-06 09:54:37,None,Defensible Space Inspection Report,None,None,None,None,None,None,Gailey,None,Prevention,2023-10-06,Yes - Without Reflective,3035,Figueroa Mountain Rd,None,Santa Ynez,Santa Barbara,CA,93441,US,3035 Figueroa Mountain Rd Santa Ynez Santa Bar...,SBC,None,32.0,Santa Ynez Valley (Outside Engine Co. Area),279,Yes,No,Hardcopy,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Hydrant- Municipal/Public Water Supply,yes,None,None,Single Family Residence Single Story,Habitable,Asphalt,Wood,Masonry/Concrete,No Deck/Porch,Combustible,No Fence,Not Applicable,None,0,0,None,NaT,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-09-05,54210,10,135-071-020,"POLYGON ((-10574.708 -372017.512, -10574.452 -..."
3,03dfcea7-bf0a-461f-92a0-42ac0d84d6ed,2022-04-04 17:00:00,2023-10-06 09:40:52,None,None,8.0,Compliant,None,None,34.669655,-120.115747,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,SBA,Los Olivos,None,3,None,None,None,B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,yes,None,None,None,None,None,None,Enclosed,"Mesh Screen > 1/8""",None,Multi Pane,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,2023-10-06,2023,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2020-07-08,None,None,None,None,gis@sbcfire.com,sbc.dsp.inspector@sbcfire.com,2022-04-05 13:47:07,2023-10-06 09:54:45,None,Defensible Space Inspection Report,None,None,None,None,None,None,Gailey,None,Prevention,2023-10-06,Yes - Without Reflective,3055,Figueroa Mountain Rd,None,Los Olivos,Santa Barbara,CA,93441,US,3055 Figueroa Mountain Rd Los Olivos Santa Bar...,SBC,None,32.0,Santa Ynez Valley (Outside Engine Co. Area),279,Yes,No,Hardcopy,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Hydrant- Municipal/Public Water Supply,yes,None,None,Single Family Residence Multi Story,Habitable,Asphalt,Wood,Masonry/Concrete,No Deck/Porch,No Patio Cover/Carport,Combustible,Not Applicable,None,0,0,None,NaT,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-09-05,54211,10,135-030-031,"POLYGON ((-10648.129 -371812.044, -10567.616 -..."
4,e7d6b19a-e26b-4041-9a52-2138aed4d439,2022-04-04 17:00:00,2023-10-06 09:41:16,None,None,8.0,Compliant,None,None,34.670898,-120.117483,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,SBA,Los Olivos,None,3,None,None,None,B,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,yes,None,None,None,None,None,None,Unenclosed,"Mesh Screen > 1/8""",None,Single Pane,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,2023-10-06,2023,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2020-07-08,None,None,None,None,gis@sbcfire.com,sbc.dsp.inspector@sbcfire.com,2022-04-05 13:47:07,2023-10-06 09:54:47,None,Defensible Space Inspection Report,None,None,None,None,None,None,Gailey,None,Prevention,2023-10-06,Yes - Without Reflective,3150 A,Calkins Rd,None,Los Olivos,Santa Barbara,CA,93441,US,3150 A Calkins Rd Los Olivos Santa Barbara CA ...,SBC,None,32.0,Santa Ynez Valley (Outside Engine Co. Area),279,Yes,No,Email,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,"Hydrant- Municipal/Public Water Supply,Pool",yes,None,None,Single Family Residence Single Story,Habitable,Tile,Stucco/Brick/Cement,Masonry/Concrete,No Deck/Porch,No Patio Cover/Carport,No Fence,Not Applicable,None,0,0,None,NaT,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-09-05,54212,10,135-030-053,"POLYGON ((-10712.259 -371661.47, -10712.259 -3..."

In [7]:
colnames_23 = {
    "system_created_at": "system_cre",
    "address_suite": "address_su",
    "address_thoroughfare": "address_th",
    "address_locality": "address_lo",
    "address_sub_admin_area": "address__2",
    "address_postal_code": "address_po",
    "address_full": "address_fu",
    "inspectiondate_calculate": "inspection",
    "structuretype": "structuret",
    "address_admin_area": "address_ad",
    "address_country": "address_co"
}

insp_23 = insp_23.rename(columns=colnames_23)

In [8]:
insp_19["year"] = 2019
insp_20["year"] = 2020
insp_21["year"] = 2021
insp_22["year"] = 2022
insp_23["year"] = 2023

In [9]:
len(insp_19.columns)

224

In [10]:
len(insp_23.columns)

224

In [11]:
inspections = pd.concat(
    [insp_19, insp_20, insp_21, insp_22, insp_23], axis=0, ignore_index=True
)

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

In [ ]:
inspections

,fulcrum_id,created_at,updated_at,system_cre,system_upd,version,status,project,assigned_t,latitude,longitude,report_tit,globalid,calculated,inspectorp,inspection,addressvis,address_su,address_th,address__1,address_lo,address__2,address_ad,address_po,address_co,address_fu,calfireuni,county,community,community_,battalion,enginenumb,stationnam,stationn_1,shift,occupantho,deliveryno,inspecti_1,a_removebr,b_removele,c_removede,d_removede,e_removedy,f_removefl,g_relocate,h_cutannua,i_reducefu,j_allexpos,k_deaddyin,l_logsstum,m_outbuild,n_addressd,o_chimneys,recommend_,propanetan,accessegre,waterstora,water_sour,can_engine,water_stor,water_comm,structuret,roofconstr,eaves,ventscreen,exteriorsi,windowpane,deckporchg,deckporche,patiocover,fenceattac,utilitymis,utilitym_1,nonhabitab,escalateto,reinspecti,clearreins,citationnu,citationda,deadtrees3,photoid,photoid_ca,le100numbe,inspecti_2,coredatafl,partner_di,principal_,firescopei,responsibi,yearbuilt,siteaddres,numberofst,appenddate,editstatus,createddat,createdby,editeddate,editedby,textfield1,textfield2,numberfiel,numberfi_1,core_with_,Date,month,year,inspection_id,apn,geometry,keyid,propertyst,e_removefl,i_removefu,j_exposedw,k_removede,l_removelo,n_displaya,o_stovepip,recommendc,structureh,inspecti_3,coredata,calculat_1,calculat_2,previousyr,previous_1,calculat_3,calculat_4,creationda,editdate,creator,editor,number_of_,shift_juli,created_by,updated_by,system_updated_at,assigned_to,report_title,propertystatus,inspectionstatus,inspectorfirstname,inspectorlastname,prevention_inspectorfirstname,prevention_inspectorfirstname_other,prevention_inspectorlastname,prevention_inspectorlastname_other,inspectorposition,addressvisible,address_sub_thoroughfare,calfireunit,community_other,enginenumber,stationname,shift_julian,accessegress,occupanthome,deliverynotificationmethod,inspectionhours,a_removebranchesfromstovepipe,b_removeleavesneedlesveg,c_removedeaddyingtrees,d_removedeaddyinggrassplants,e_removeflammablegroundcover,f_removeflammablevegetation,g_relocateexposedwoodpiles,h_cutannualgrassesforbs,i_removefuelsusingctguidelines,j_exposedwoodpiles,k_removedeaddyingwoodyfuels,l_removelogstumpsembeddedsoil,m_outbuildingsliquidpropanegas,n_displayaddresscontrasting,o_stovepipemetalscreenopenings,recommendclearvegetation,water_source,can_engine_access_water_source,water_storage_size_stored_water_on_individual_parcels_only,water_comments,structurehabitable,roofconstruction,exteriorsiding,deckporchgrade,deckporchelevated,patiocovercarport,fenceattachedtostructure,propanetankdistance,utilitymiscstructuredistance,utilitymiscstucturecount,nonhabitableoutbuildings,escalatetocoordinator,reinspectiondate,citationnumber,number_of_dead_trees_within_300_ft_of_residence,gatecode,comments,photoid_caption,photoid_url,le100number,inspectioncount,firescopeid,siteaddress,numberofstructures,calculatedglobalid,calculateddate,calculateduid,numberfield1,numberfield2,previousyrinspecteddata,previousyrinspectionstatus,calculatededitor,calculatededitdate,creationdate
0,d9a4d031-d16d-4c84-b32c-f3fcd7d945df,2018-05-25 16:25:06,2019-06-05 11:57:49,2019-05-07 11:52:36,2019-06-05 16:35:26,2.0,Compliant,None,None,34.669616,-120.031160,Defensible Space Inspection Report,None,None,DSI,2019-06-05,Yes - Without Reflective,3462,Brinkerhoff Rd,None,Santa Ynez,Santa Barbara,CA,93460,US,3462 Brinkerhoff Rd Santa Ynez Santa Barbara C...,SBC,SBA,Woodstock,None,2,32,32,None,None,Yes,Hardcopy,30 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,>30',yes,yes,Private Hydrant- Private Stored Water,yes,Over 5000 gallons,None,Utility or Miscellaneous Structure > 120 sqft,Metal,Unenclosed,No Vents,Wood,No Windows,No Deck/Porch,No Deck/Porch,No Patio Cover/Carport,No Fence,30-50',0,0,None,NaT,None,None,None,0,None,None,0.0,0.0,None,None,None,None,None,2000.0,None,0.0,2019-06-05,None,None,None,None,None,None,None,0.0,0.0,None,2019-06-05,6,2019,0,141-010-040,"POLYGON ((-2813.179 -371821.557, -2813.179 -37...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
1,7f9b6d98-548d-4b94-97c6-82cbddf84d99,2018-05-25 16:25:10,2019-05-15 12:26:44,2019-05-07 11:52:37,2019-05-15 12:26:45,3.0,Compliant,None,None,34.679129,-120.091914,Defensible Space Inspection Report,None,None,DSI,2019-05-09,Yes - Without Reflective,3290,Avenida Caballo,None,Santa Ynez,Santa Barbara,CA,93460,US,3290 Avenida Caballo Santa Ynez Santa Barbara ...,SBC,SBA,Woodstock,None,2,32,Santa Ynez Valley (Outside Engine Co. Area),None,None,No,Email,15 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Not Applicable,yes,yes,Private Hydrant- Private Stored Water,yes,None,None,Single Family Residence Multi Story,Metal,No Eaves,No Vents,Wood,Single Pane,No Deck/Porch,No Deck/Porch,No Patio Cover/Carport,No Fence,30-50',1,0,None,NaT,None,None,None,None,f1556c16-78c8-44bf-b6ce-a7ddb5908d96,None,0.0,0.0,None,None,None,None,None,0.0,None,0.0,2019-05-09,None,None,None,None,None,None,None,0.0,0.0,None,2019-05-09,5,2019,1,135-310-022,"POLYGON ((-8368.416 -370860.259, -8475.394 -37...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
2,03afdf39-173a-4f02-bfdc-e0725e554959,2018-05-25 16:25:11,2019-05-09 14:20:04,2019-05-07 11:52:37,2019-05-09 15:26:24,2.0,Compliant,None,None,34.676197,-120.089553,Defensible Space Inspection Report,None,None,DSI,2019-05-09,Yes - Without Reflective,3350,Caballo Ln,None,Santa Ynez,Santa Barbara,CA,93460,US,3350 Caballo Ln Santa Ynez Santa Barbara CA 93...,SBC,SBA,Woodstock,None,2,32,Santa Ynez Valley (Outside Engine Co. Area),None,None,No,Email,15 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Not Applicable,yes,None,None,None,None,None,Single Family Residence Multi Story,Tile,Unenclosed,No Vents,Stucco/Brick/Cement,Multi Pane,No Deck/Porch,No Deck/Porch,No Patio Cover/Carport,No Fence,>50',2,0,None,NaT,None,None,None,None,None,None,0.0,0.0,None,None,None,None,None,0.0,None,0.0,2019-05-09,None,None,None,None,None,None,None,0.0,0.0,None,2019-05-09,5,2019,2,135-310-075,"POLYGON ((-8253.618 -371073.707, -8136.129 -37...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
3,941e29b0-6cd3-4c7e-a919-b8f2410b4a2b,2018-05-25 16:25:11,2019-05-09 14:25:18,2019-05-07 11:52:38,2019-05-09 15:26:26,2.0,Compliant,None,None,34.677982,-120.088944,Defensible Space Inspection Report,None,None,DSI,2019-05-09,Yes - Without Reflective,3350,Caballo Ln,None,Santa Ynez,Santa Barbara,CA,93460,US,3350 Caballo Ln Santa Ynez Santa Barbara CA 93...,SBC,SBA,Woodstock,None,2,32,Santa Ynez Valley (Outside Engine Co. Area),None,None,Yes,Email,15 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Not Applicable,yes,no,None,None,None,None,Utility or Miscellaneous Structure > 120 sqft,Metal,Unenclosed,No Vents,Metal,Single Pane,Masonry/Concrete,No Deck/Porch,No Patio Cover/Carport,No Fence,None,0,0,None,NaT,None,None,None,None,17322007-d5d1-4568-bde6-00ae169a0bbf,None,0.0,0.0,None,None,None,None,None,0.0,None,0.0,2019-05-09,None,None,None,None,None,None,None,0.0,0.0,None,2019-05-09,5,2019,3,135-310-075,"POLYGON ((-8201.866 -370989.432, -8201.866 -37...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
4,abe890ba-3269-4ef6-84d7-4a9b6bfd717e,2018-05-25 16:25:11,2019-12-17 14:16:14,2019-05-07 11:52:38,2019-12-18 11:43:23,5.0,Compliant,None,None,34.678469,-120.087539,Defensible Space Inspection Report,None,None,DSI,2019-12-17,Yes - Without Reflective,3320 A,Canada Este Rd,None,Santa Ynez,Santa Barbara,CA,93460,US,3320 A Canada Este Rd Santa Ynez Santa Barbara...,SBC,SBA,Woodstock,None,2,32,Santa Ynez Valley (Outside Engine Co. Area),None,None,No,Hardcopy,5 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,>30',yes,yes,Pond,None,None,None,Single Family Residence Multi Story,Asphalt,Unenclosed,"Mesh Screen > 1/8""",Wood,Single Pane,Masonry/Concrete,No Deck/Porch,Non Combustible,No Fence,None,0,0,None,NaT,None,None,None,None,50114b4c-e04a-4054-bd54-5a7dbca535af,None,0.0,0.0,None,None,None,None,None,2002.0,None,0.0,2019-05-08,None,None,None,None,None,None,None,0.0,0.0,None,2019-12-17,12,2019,4,135-310-042,"POLYGON ((-7966.144 -370818.558, -7966.144 -37...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67575,84e8125f-e471-4b03-9a60-5937b46cdee6,2022-04-05 17:00:00,2023-07-17 15:14:41,2022-04-06 10:24:02,NaT,7.0,Compliant,None,NaN,34.542929,-120.191819,NaN,None,NaN,NaN,2023-07-15 00:00:00,NaN,None,Old Coast Hwy,NaN,Buellton,Santa Barbara,CA,93117,US,2323 Old Coast Hwy Buellton Santa Barbara CA 9...,NaN,SBA,Buellton,NaN,3,NaN,NaN,NaN,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,NaN,Utility or Miscellaneous Structure > 120 sqft,NaN,Unenclosed,"Mesh Screen <= 1/8""",NaN,No Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1939.0,NaN,NaN,NaT,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,2023-07-15,7,2023,9786,None,"POLYGON ((-17643.855 -385952.979, -17556.337 -...",0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaT,2020-10-19,None,None,NaN,NaN,gis@sbcfire.com,burnpermits@sbcfire.tech,2023-07-17 15:14:43,None,Defensible Space Inspection Report,None,None,None,None,None,Brian,None,Burger,Engine,Yes - With Reflective,2323,SBC,None,31.0,31,198,Yes,No,Email,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Private Hydrant- Private Stored Water,yes,None,None,Habitable,Metal,Metal,No Deck/Porch,Wood,No Patio Cover/Carport,No Fence,Not Applicable,None,0,0,None,NaT,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-10-05
67576,5d7e3009-f388-47ac-b1b8-0c4cdbf7aa55,2022-04-04 17:00:00,2023-09-14 09:23:41,2022-04-05 13:56:02,NaT,6.0,Compliant,None,NaN,35.042135,-119.893337,NaN,None,NaN,NaN,2023-09-14 00:00:00,NaN,None,Cuyama Hwy,NaN,Cuyama,Santa Barbara,CA,93254,US,13750 Cuyama Hwy Cuyama Santa Barbara CA 93254 US,NaN,SBA,Cuyama,NaN,2,NaN,NaN,NaN,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,NaN,NaN,Single Family Residence Single Story,NaN,Unenclosed,"Mesh Screen <= 1/8""",NaN,Multi Pane,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaT,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,2023-09-14,9,2023,10810,None,"POLYGON ((9685.179 -330543.12, 9762.993 -33054...",0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaT,2020-07-05,None,None,NaN,NaN,gis@sbcfire.com,sbc.dsp.inspector@sbcfire.com,2023-09-14 09:25:54,None,Defensible Space Inspection Report,None,None,None,None,None,None,Gailey,None,Prevention,Yes - With Reflective,13750,SBC,None,27.0,27,257,Yes,No,Hardcopy,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Tank,yes,2500 - 5000 gallons,None,Habitable,Metal,Stucco/Brick/Cement,Not Observed,Not Observed,Non Combustible,No Fence,Not Applicable,None,None,None,None,NaT,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-08-15
67577,d63fc715-5bf5-4f52-ac9a-f9e2dee586d5,2022-04-04 17:00:00,2023-10-17 11:10:51,2022-04-05 13:58:12,NaT,7.0,Compliant,None,NaN,34.570209,-119.954035,NaN,None,NaN,NaN,2023-10-17 00:00:00,NaN,None,CA-154,NaN,Santa Barbara,Santa Barbara,CA,93105,US,2400 CA-154 Santa Barbara Santa Barbara CA 931...,NaN,SBA,Cachuma,NaN,3,NaN,NaN,NaN,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,no,NaN,NaN,NaN,NaN,Single Family Residence Single Story,NaN,Unenclosed,"Mesh Screen <= 1/8""",NaN,Single Pane,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaT,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,2023-10-17,10,2023,10891,None,"POLYGON ((4177.215 -382936.757, 4255.029 -3829...",0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaT,2020-09-21,None,None,NaN,NaN,gis@sbcfire.com,sbc.dsp.inspector@sbcfire.com,2023-10-17 11:15:33,None,Defensible Space Inspection Report,None,None,None,None,Charlotte,None,Endicott,None,DSI,No - Address Doesn't Exist,2400,SBC,None,32.0,32,290,Yes,No,Email,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Habitable,Asphalt,Wood,No Deck/Porch,No Deck/Porch,No Patio Cover/Carport,No Fence,>30',None,0,0,None,NaT,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-10-20
67578,16de4faa-96cf-461a-9579-87f373d7af64,2022-04-04 17:00:00,2023-08-29 11:13:34,2022-04-05 14:01:13,NaT,9.0,Compliant,None,NaN,34.601223,-120.201155,NaN,None,NaN,NaN,2023-08-28 00:00:00,NaN,None,Santa Rosa Rd,NaN,Buellton,Santa Barbara,CA,93427,US,9491 Santa Rosa Rd Buellton Santa Barbara CA 9...,NaN,SBA,None,NaN,3,NaN,NaN,NaN,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,Single Family Residence Single Story,NaN,Not Observed,"Mesh Screen <= 1/8""",NaN,Not Observed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaT,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,2023-08-28,8,2023,11240,None,"POLYGON ((-18480.724 -379475.928, -18402.911 -...",0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaT,2021-08-03,None,None,NaN,NaN,gis@sbcfire.com,sbc.dsp.inspector@sbcfire.com,2023-08-29 11:20:24,None,Defensible Space Inspection Report,None,None,None,None,Charlotte,None,Endicott,None,DSI,Yes - With Reflective,9491,SBC,None,0.0,31,241,Yes,No,Email,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Habitable,Metal,Not Observed,Not Observed,Not Observed,No Patio Cover/Carport,Not Observed,Not Observed,None,None,None,None,NaT,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-07-13
67579,3b6518cb-776a-4d6e-8f98-c43f633e29bf,2022-06-30 17:00:00,2023-08-22 17:27:06,2022-07-01 13:55:51,NaT,6.0,Compliant,None,NaN,34.919973,-119.512027,NaN,None,NaN,NaN,2023-08-22 00:00:00,NaN,None,CA-33,NaN,Santa Margarita,San Luis Obispo County,CA,93453,US,525 CA-33 Santa Margarita San Luis Obispo Coun...,NaN,SBA,Ventucopa,NaN,2,NaN,NaN,NaN,C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,Single Family Residence Single Story,NaN,Unenclosed,"Mesh Screen <= 1/8""",NaN,Single Pane,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,None,NaN,NaN,NaN,NaN,None,None,NaN,NaN,NaN,2023-08-22,8,2023,13357,None,"POLYGON ((44516.796 -343997.359, 44594.609 -34...",0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaT,2022-07-01,None,None,NaN,NaN,firedg27@sbcfire.com,sbc.dsp.inspector@sbcfire.com,2023-08-22 17:37:21,None,Defensible Space Inspection Report,None,None,Myles,Menegon,None,None,Gailey,None,Prevention,No - Not Visible,525,SBC,None,NaN,27,234,Yes,No,Hardcopy,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Habitable,Asphalt,Other,Masonry/Concrete,Not Observed,No Patio Cover/Carport,No Fence,>30',30-50',2,2,None,NaT,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-07-01

In [ ]:
# CHUNK FOR BUFFER_GEOMETRIES; RUN IF USING BUFFER_GEOMETRIES, NOT TRAINING_GEOMETRIES

# converting 'system_cre' column to display single days, instead of days and times
inspections["system_cre"] = pd.to_datetime(inspections["system_cre"]).dt.date

In [ ]:
# CHUNK FOR BUFFER_GEOMETRIES; RUN IF USING BUFFER_GEOMETRIES, NOT TRAINING_GEOMETRIES

# Some dates in the 'inspection' column have the format '2023-08-22 00:00:00'.
# This chunk is to remove the occurrences of '00:00:00' and remove trailing whitespace.

inspections["inspection"] = (
    inspections["inspection"]
    .astype(str)
    .str.replace(" 00:00:00", "", regex=False)
    .str.strip()
)

In [ ]:
# Fixing CRS to 3310, Albers

inspections = inspections.to_crs(epsg=3310)

print(inspections.crs)

EPSG:3310

In [ ]:
# adding address_id to be unique for every unique inspection
inspections["inspection_id"] = np.arange(1, len(inspections) + 1)

In [ ]:
inspections.inspection_id

0            1
1            2
2            3
3            4
4            5
         ...
67575    67576
67576    67577
67577    67578
67578    67579
67579    67580
Name: inspection_id, Length: 67580, dtype: int64

In [ ]:
inspections.to_file(
    "/capstone/wildfire_prep/data/PUZZLE_PIECES/inspections_master.geojson",
    driver="GeoJSON",
)

In [ ]:
# inspections.to_file(
#     "/capstone/wildfire_prep/data/PUZZLE_PIECES/inspections_master_training_geometries.geojson",
#     driver="GeoJSON",
# )

In [ ]:
# create dataframe of just compliance status and inspection_id

status = inspections.reindex(columns=["inspection_id", "status"])

status["status"] = status["status"].map({"Compliant": 0, "Non-Compliant": 1})

In [ ]:
status.shape

(67580, 2)

In [ ]:
status.to_csv(
    "/capstone/wildfire_prep/data/PUZZLE_PIECES/inspections_id_compliance_status.csv",
    index=False,
)