In [2]:
import os
import sys
import numpy as np
import pandas as pd
import geopandas as gpd

sys.path.append("../utils")

import config

pd.set_option("display.max_columns", None)

In [6]:
# CHUNK FOR BUFFER_GEOMETRIES; RUN IF USING BUFFER_GEOMETRIES, NOT TRAINING_GEOMETRIES
# Loading in inspections data with newly calculated geometries 4/29/25

# insp_19 = gpd.read_file(
#     "/capstone/wildfire_prep/data/buffer_geometries/buffer_geometries_2019.geojson"
# )
# insp_20 = gpd.read_file(
#     "/capstone/wildfire_prep/data/buffer_geometries/buffer_geometries_2020.geojson"
# )
# insp_21 = gpd.read_file(
#     "/capstone/wildfire_prep/data/buffer_geometries/buffer_geometries_2021.geojson"
# )
# insp_22 = gpd.read_file(
#     "/capstone/wildfire_prep/data/buffer_geometries/buffer_geometries_2022.geojson"
# )
# insp_23 = gpd.read_file(
#     "/capstone/wildfire_prep/data/buffer_geometries/buffer_geometries_2023.geojson"
# )

# insp_19.head()

,fulcrum_id,created_at,updated_at,system_cre,system_upd,version,status,project,assigned_t,latitude,longitude,report_tit,globalid,calculated,inspectorp,inspection,addressvis,address_su,address_th,address__1,address_lo,address__2,address_ad,address_po,address_co,address_fu,calfireuni,county,community,community_,battalion,enginenumb,stationnam,stationn_1,shift,occupantho,deliveryno,inspecti_1,a_removebr,b_removele,c_removede,d_removede,e_removedy,f_removefl,g_relocate,h_cutannua,i_reducefu,j_allexpos,k_deaddyin,l_logsstum,m_outbuild,n_addressd,o_chimneys,recommend_,propanetan,accessegre,waterstora,water_sour,can_engine,water_stor,water_comm,structuret,roofconstr,eaves,ventscreen,exteriorsi,windowpane,deckporchg,deckporche,patiocover,fenceattac,utilitymis,utilitym_1,nonhabitab,escalateto,reinspecti,clearreins,citationnu,citationda,deadtrees3,photoid,photoid_ca,le100numbe,inspecti_2,coredatafl,partner_di,principal_,firescopei,responsibi,yearbuilt,siteaddres,numberofst,appenddate,editstatus,createddat,createdby,editeddate,editedby,textfield1,textfield2,numberfiel,numberfi_1,core_with_,Date,apn,geometry
0,d9a4d031-d16d-4c84-b32c-f3fcd7d945df,2018-05-25 16:25:06,2019-06-05 11:57:49,2019-05-07 11:52:36,2019-06-05 16:35:26,2.0,Compliant,None,None,34.669616,-120.031160,Defensible Space Inspection Report,None,None,DSI,2019-06-05,Yes - Without Reflective,3462,Brinkerhoff Rd,None,Santa Ynez,Santa Barbara,CA,93460,US,3462 Brinkerhoff Rd Santa Ynez Santa Barbara C...,SBC,SBA,Woodstock,None,2,32,32,None,None,Yes,Hardcopy,30 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,>30',yes,yes,Private Hydrant- Private Stored Water,yes,Over 5000 gallons,None,Utility or Miscellaneous Structure > 120 sqft,Metal,Unenclosed,No Vents,Wood,No Windows,No Deck/Porch,No Deck/Porch,No Patio Cover/Carport,No Fence,30-50',0,0,None,NaT,None,None,None,0,None,None,0.0,0.0,None,None,None,None,None,2000.0,None,0.0,2019-06-05,None,None,None,None,None,None,None,0.0,0.0,None,2019-06-05,141-010-040,"POLYGON ((-2813.179 -371821.557, -2813.179 -37..."
1,7f9b6d98-548d-4b94-97c6-82cbddf84d99,2018-05-25 16:25:10,2019-05-15 12:26:44,2019-05-07 11:52:37,2019-05-15 12:26:45,3.0,Compliant,None,None,34.679129,-120.091914,Defensible Space Inspection Report,None,None,DSI,2019-05-09,Yes - Without Reflective,3290,Avenida Caballo,None,Santa Ynez,Santa Barbara,CA,93460,US,3290 Avenida Caballo Santa Ynez Santa Barbara ...,SBC,SBA,Woodstock,None,2,32,Santa Ynez Valley (Outside Engine Co. Area),None,None,No,Email,15 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Not Applicable,yes,yes,Private Hydrant- Private Stored Water,yes,None,None,Single Family Residence Multi Story,Metal,No Eaves,No Vents,Wood,Single Pane,No Deck/Porch,No Deck/Porch,No Patio Cover/Carport,No Fence,30-50',1,0,None,NaT,None,None,None,None,f1556c16-78c8-44bf-b6ce-a7ddb5908d96,None,0.0,0.0,None,None,None,None,None,0.0,None,0.0,2019-05-09,None,None,None,None,None,None,None,0.0,0.0,None,2019-05-09,135-310-022,"POLYGON ((-8368.416 -370860.259, -8475.394 -37..."
2,03afdf39-173a-4f02-bfdc-e0725e554959,2018-05-25 16:25:11,2019-05-09 14:20:04,2019-05-07 11:52:37,2019-05-09 15:26:24,2.0,Compliant,None,None,34.676197,-120.089553,Defensible Space Inspection Report,None,None,DSI,2019-05-09,Yes - Without Reflective,3350,Caballo Ln,None,Santa Ynez,Santa Barbara,CA,93460,US,3350 Caballo Ln Santa Ynez Santa Barbara CA 93...,SBC,SBA,Woodstock,None,2,32,Santa Ynez Valley (Outside Engine Co. Area),None,None,No,Email,15 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Not Applicable,yes,None,None,None,None,None,Single Family Residence Multi Story,Tile,Unenclosed,No Vents,Stucco/Brick/Cement,Multi Pane,No Deck/Porch,No Deck/Porch,No Patio Cover/Carport,No Fence,>50',2,0,None,NaT,None,None,None,None,None,None,0.0,0.0,None,None,None,None,None,0.0,None,0.0,2019-05-09,None,None,None,None,None,None,None,0.0,0.0,None,2019-05-09,135-310-075,"POLYGON ((-8253.618 -371073.707, -8136.129 -37..."
3,941e29b0-6cd3-4c7e-a919-b8f2410b4a2b,2018-05-25 16:25:11,2019-05-09 14:25:18,2019-05-07 11:52:38,2019-05-09 15:26:26,2.0,Compliant,None,None,34.677982,-120.088944,Defensible Space Inspection Report,None,None,DSI,2019-05-09,Yes - Without Reflective,3350,Caballo Ln,None,Santa Ynez,Santa Barbara,CA,93460,US,3350 Caballo Ln Santa Ynez Santa Barbara CA 93...,SBC,SBA,Woodstock,None,2,32,Santa Ynez Valley (Outside Engine Co. Area),None,None,Yes,Email,15 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Not Applicable,yes,no,None,None,None,None,Utility or Miscellaneous Structure > 120 sqft,Metal,Unenclosed,No Vents,Metal,Single Pane,Masonry/Concrete,No Deck/Porch,No Patio Cover/Carport,No Fence,None,0,0,None,NaT,None,None,None,None,17322007-d5d1-4568-bde6-00ae169a0bbf,None,0.0,0.0,None,None,None,None,None,0.0,None,0.0,2019-05-09,None,None,None,None,None,None,None,0.0,0.0,None,2019-05-09,135-310-075,"POLYGON ((-8201.866 -370989.432, -8201.866 -37..."
4,abe890ba-3269-4ef6-84d7-4a9b6bfd717e,2018-05-25 16:25:11,2019-12-17 14:16:14,2019-05-07 11:52:38,2019-12-18 11:43:23,5.0,Compliant,None,None,34.678469,-120.087539,Defensible Space Inspection Report,None,None,DSI,2019-12-17,Yes - Without Reflective,3320 A,Canada Este Rd,None,Santa Ynez,Santa Barbara,CA,93460,US,3320 A Canada Este Rd Santa Ynez Santa Barbara...,SBC,SBA,Woodstock,None,2,32,Santa Ynez Valley (Outside Engine Co. Area),None,None,No,Hardcopy,5 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,>30',yes,yes,Pond,None,None,None,Single Family Residence Multi Story,Asphalt,Unenclosed,"Mesh Screen > 1/8""",Wood,Single Pane,Masonry/Concrete,No Deck/Porch,Non Combustible,No Fence,None,0,0,None,NaT,None,None,None,None,50114b4c-e04a-4054-bd54-5a7dbca535af,None,0.0,0.0,None,None,None,None,None,2002.0,None,0.0,2019-05-08,None,None,None,None,None,None,None,0.0,0.0,None,2019-12-17,135-310-042,"POLYGON ((-7966.144 -370818.558, -7966.144 -37..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19541,None,NaT,NaT,NaT,NaT,0.0,Compliant,None,None,34.445966,-119.664047,None,None,None,Prevention,6/14/2019,Yes - Without Reflective,None,None,None,None,None,None,None,None,760 Chelham Way Santa Barbara CA 93108 US,SBC,SBA,Montecito,None,1,None,MTO,None,None,Yes,Unable to Assess,5 min,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Not Applicable,yes,yes,Hydrant- Municipal/Public Water Supply,yes,None,None,Single Family Residence Multi Story,Asphalt,No Eaves,No Vents,Wood,Multi Pane,Wood,No Deck/Porch,No Patio Cover/Carport,No Fence,30-50',1,0,None,NaT,None,None,None,0,https://web.fulcrumapp.com/photos/view?photos=...,None,0.0,0.0,None,None,None,None,None,0.0,None,0.0,NaT,None,None,None,None,None,None,None,0.0,0.0,None,2019-06-14,013-111-034,"POLYGON ((30900.797 -396635.44, 30870.644 -396..."
19542,None,NaT,NaT,NaT,NaT,0.0,Compliant,None,None,34.445633,-119.663265,None,None,None,Prevention,None,None,None,None,None,None,None,None,None,None,740 Chelham Way Santa Barbara CA 93108 US,SBC,SBA,Montecito,None,1,None,MTO,None,None,None,None,None,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaT,None,None,None,None,None,None,0.0,0.0,None,None,None,None,None,0.0,None,0.0,NaT,None,None,None,None,None,None,None,0.0,0.0,None,2019-08-01,013-111-030,"POLYGON ((30894.968 -396638.024, 30906.151 -39..."
19543,None,NaT,NaT,NaT,NaT,0.0,Non-Compliant,None,None,34.442984,-119.641537,None,None,None,Prevention,None,None,None,None,None,None,None,None,None,None,670 Hot Springs Rd Santa Barbara CA 93108 US,SBC,SBA,Montecito,None,1,None,MTO,None,None,None,None,None,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaT,None,None,None,None,None,None,0.0,0.0,None,None,None,None,None,0.0,None,0.0,NaT,None,None,None,None,None,None,None,0.0,0.0,None,2019-08-01,011-130-001,"POLYGON ((32892.059 -396994.879, 32892.059 -39..."
19544,None,NaT,NaT,NaT,NaT,0.0,Compliant,None,None,34.444497,-119.652660,None,None,None,Prevention,6/18/2019,Yes - Without Reflective,None,None,None,None,None,None,None,None,760 Ashley Rd Santa Barbara CA 93108 US,SBC,SBA,Montecito,None,1,None,MTO,None,None,No,Unable to Assess,5 min,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Not Applicable,yes,yes,Hydrant- Municipal/Public Water Supply,yes,None,None,Single Family Residence Multi Story,Tile,Unenclosed,Unable to Assess,Stucco/Brick/Cement,Multi Pane,Masonry/Concrete,Masonry/Concrete,Combustible,No Fence,<30',2,0,None,NaT,None,None,None,0,https://web.fulcrumapp.com/photos/view?photos=...,None,0.0,0.0,None,None,None,None,None,0.0,None,0.0,NaT,None,None,None,None,None,None,None,0.0,0.0,None,2019-06-18,011-120-052,"POLYGON ((31947.405 -396830.827, 31881.655 -39..."
19545,None,NaT,NaT,NaT,NaT,0.0,Compliant,None,None,34.437075,-119.634632,None,None,None,Prevention,6/25/2019,Yes - With Reflective,None,None,None,None,None,None,None,None,525 Santa Angela Ln Santa Barbara CA 93108 US,SBC,SBA,Montecito,None,1,None,MTO,None,None,None,Unable to Assess,5 min,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaT,None,None,None,None,None,None,0.0,0.0,None,None,None,None,None,0.0,None,0.0,NaT,None,None,None,None,None,None,None,0.0,0.0,None,2019-06-25,011-200-014,"POLYGON ((33547.639 -397629.247, 33541.607 -39..."

In [3]:
# LOADING TRAINING GEOMETRIES INSTEAD
insp_19 = gpd.read_file(
    "/capstone/wildfire_prep/data/training_geometries/training_geometries_2019.geojson"
)
insp_20 = gpd.read_file(
    "/capstone/wildfire_prep/data/training_geometries/training_geometries_2020.geojson"
)
insp_21 = gpd.read_file(
    "/capstone/wildfire_prep/data/training_geometries/training_geometries_2021.geojson"
)
insp_22 = gpd.read_file(
    "/capstone/wildfire_prep/data/training_geometries/training_geometries_2022.geojson"
)
insp_23 = gpd.read_file(
    "/capstone/wildfire_prep/data/training_geometries/training_geometries_2023.geojson"
)

In [4]:
rows19 = len(insp_19)
rows20 = len(insp_20)
rows21 = len(insp_21)
rows22 = len(insp_22)
rows23 = len(insp_23)

geometries_length = rows19 + rows20 + rows21 + rows22 + rows23
print(geometries_length)

67580

In [5]:
insp_19.head()

,fulcrum_id,apn,Date,year,month,status,geometry
0,d9a4d031-d16d-4c84-b32c-f3fcd7d945df,None,2019-06-05,2019,6,Compliant,"POLYGON ((-2892.357 -371905.217, -2813.179 -37..."
1,7f9b6d98-548d-4b94-97c6-82cbddf84d99,None,2019-05-09,2019,5,Compliant,"POLYGON ((-8475.394 -370860.259, -8368.416 -37..."
2,03afdf39-173a-4f02-bfdc-e0725e554959,None,2019-05-09,2019,5,Compliant,"POLYGON ((-8253.618 -371183.727, -8136.129 -37..."
3,941e29b0-6cd3-4c7e-a919-b8f2410b4a2b,None,2019-05-09,2019,5,Compliant,"POLYGON ((-8201.866 -370989.432, -8091.086 -37..."
4,abe890ba-3269-4ef6-84d7-4a9b6bfd717e,None,2019-12-17,2019,12,Compliant,"POLYGON ((-8065.883 -370931.624, -7966.144 -37..."

In [6]:
insp_23.head()

,fulcrum_id,apn,Date,year,month,status,geometry
0,48c58877-f0ce-438d-ac87-6434a2c15fe8,None,2023-06-05,2023,6,Compliant,"POLYGON ((20815.284 -394983.12, 20960.85 -3949..."
1,f351800c-fc5c-4b79-bf24-a41775b74d7c,None,2023-10-06,2023,10,Compliant,"POLYGON ((-10002.099 -371564.878, -9914.183 -3..."
2,b97b5b98-bda4-4b41-b850-3fdb36c9f689,None,2023-10-06,2023,10,Compliant,"POLYGON ((-10596.644 -372017.512, -10520.325 -..."
3,03dfcea7-bf0a-461f-92a0-42ac0d84d6ed,None,2023-10-06,2023,10,Compliant,"POLYGON ((-10648.129 -371898.998, -10567.616 -..."
4,e7d6b19a-e26b-4041-9a52-2138aed4d439,None,2023-10-06,2023,10,Compliant,"POLYGON ((-10813.384 -371767.703, -10712.259 -..."

In [7]:
colnames_23 = {
    "system_created_at": "system_cre",
    "address_suite": "address_su",
    "address_thoroughfare": "address_th",
    "address_locality": "address_lo",
    "address_sub_admin_area": "address__2",
    "address_postal_code": "address_po",
    "address_full": "address_fu",
    "inspectiondate_calculate": "inspection",
    "structuretype": "structuret",
    "address_admin_area": "address_ad",
    "address_country": "address_co"
}

insp_23 = insp_23.rename(columns=colnames_23)

In [8]:
insp_19["year"] = 2019
insp_20["year"] = 2020
insp_21["year"] = 2021
insp_22["year"] = 2022
insp_23["year"] = 2023

In [9]:
len(insp_19.columns)

7

In [10]:
len(insp_23.columns)

7

In [11]:
inspections = pd.concat(
    [insp_19, insp_20, insp_21, insp_22, insp_23], axis=0, ignore_index=True
)

In [12]:
inspections

,fulcrum_id,apn,Date,year,month,status,geometry
0,d9a4d031-d16d-4c84-b32c-f3fcd7d945df,None,2019-06-05,2019,6,Compliant,"POLYGON ((-2892.357 -371905.217, -2813.179 -37..."
1,7f9b6d98-548d-4b94-97c6-82cbddf84d99,None,2019-05-09,2019,5,Compliant,"POLYGON ((-8475.394 -370860.259, -8368.416 -37..."
2,03afdf39-173a-4f02-bfdc-e0725e554959,None,2019-05-09,2019,5,Compliant,"POLYGON ((-8253.618 -371183.727, -8136.129 -37..."
3,941e29b0-6cd3-4c7e-a919-b8f2410b4a2b,None,2019-05-09,2019,5,Compliant,"POLYGON ((-8201.866 -370989.432, -8091.086 -37..."
4,abe890ba-3269-4ef6-84d7-4a9b6bfd717e,None,2019-12-17,2019,12,Compliant,"POLYGON ((-8065.883 -370931.624, -7966.144 -37..."
...,...,...,...,...,...,...,...
67575,cb94e142-39a4-4f15-b197-4812a37e735e,None,2023-07-29,2023,7,Compliant,"POLYGON ((-46018.532 -375420.654, -45940.718 -..."
67576,c1eaacd2-8345-40de-ba23-8ac9d38d5154,None,2023-08-14,2023,8,Non-Compliant,"POLYGON ((29027.935 -341306.838, 29105.749 -34..."
67577,52354294-b805-4675-bee5-90c4027bad15,None,2023-08-23,2023,8,Compliant,"POLYGON ((9463.523 -337960.503, 9541.337 -3379..."
67578,75c11a67-cfce-4ff4-8759-d249c7c3cedd,None,2023-09-26,2023,9,Compliant,"POLYGON ((17004.118 -395314.022, 17081.932 -39..."
67579,3b9d56ac-899c-440d-8370-9ec2636cc40f,None,2023-10-31,2023,10,Compliant,"POLYGON ((-35016.129 -349482.828, -34938.315 -..."

In [14]:
# CHUNK FOR BUFFER_GEOMETRIES; RUN IF USING BUFFER_GEOMETRIES, NOT TRAINING_GEOMETRIES

# # converting 'system_cre' column to display single days, instead of days and times
# inspections["system_cre"] = pd.to_datetime(inspections["system_cre"]).dt.date

In [16]:
# CHUNK FOR BUFFER_GEOMETRIES; RUN IF USING BUFFER_GEOMETRIES, NOT TRAINING_GEOMETRIES

# Some dates in the 'inspection' column have the format '2023-08-22 00:00:00'.
# This chunk is to remove the occurrences of '00:00:00' and remove trailing whitespace.

# inspections["inspection"] = (
#     inspections["inspection"]
#     .astype(str)
#     .str.replace(" 00:00:00", "", regex=False)
#     .str.strip()
# )

In [17]:
# Fixing CRS to 3310, Albers

inspections = inspections.to_crs(epsg=3310)

print(inspections.crs)

EPSG:3310

In [18]:
# adding address_id to be unique for every unique inspection
inspections["inspection_id"] = np.arange(1, len(inspections) + 1)

In [19]:
inspections.inspection_id

0            1
1            2
2            3
3            4
4            5
         ...
67575    67576
67576    67577
67577    67578
67578    67579
67579    67580
Name: inspection_id, Length: 67580, dtype: int64

In [20]:
# inspections.to_file(
#     "/capstone/wildfire_prep/data/PUZZLE_PIECES/inspections_master.geojson",
#     driver="GeoJSON",
# )

In [22]:
inspections.to_file(
    "/capstone/wildfire_prep/data/PUZZLE_PIECES/inspections_master_training_geometries.geojson",
    driver="GeoJSON",
)

In [23]:
inspections.head()

,fulcrum_id,apn,Date,year,month,status,geometry,inspection_id
0,d9a4d031-d16d-4c84-b32c-f3fcd7d945df,None,2019-06-05,2019,6,Compliant,"POLYGON ((-2892.357 -371905.217, -2813.179 -37...",1
1,7f9b6d98-548d-4b94-97c6-82cbddf84d99,None,2019-05-09,2019,5,Compliant,"POLYGON ((-8475.394 -370860.259, -8368.416 -37...",2
2,03afdf39-173a-4f02-bfdc-e0725e554959,None,2019-05-09,2019,5,Compliant,"POLYGON ((-8253.618 -371183.727, -8136.129 -37...",3
3,941e29b0-6cd3-4c7e-a919-b8f2410b4a2b,None,2019-05-09,2019,5,Compliant,"POLYGON ((-8201.866 -370989.432, -8091.086 -37...",4
4,abe890ba-3269-4ef6-84d7-4a9b6bfd717e,None,2019-12-17,2019,12,Compliant,"POLYGON ((-8065.883 -370931.624, -7966.144 -37...",5

In [21]:
inspections.status.value_counts()

status
Compliant        67162
Non-Compliant      418
Name: count, dtype: int64

Investigation into differences in rows between buffer_geometries and Leilanie's dataset of training geometries

In [18]:
# loading in inspections_with_buildings .geojsons

inspections_with_buildings_2019 = gpd.read_file(
    "/capstone/wildfire_prep/data/joined_inspections_buildings/inspections_with_buildings_2019.geojson"
)
inspections_with_buildings_2020 = gpd.read_file(
    "/capstone/wildfire_prep/data/joined_inspections_buildings/inspections_with_buildings_2020.geojson"
)
inspections_with_buildings_2021 = gpd.read_file(
    "/capstone/wildfire_prep/data/joined_inspections_buildings/inspections_with_buildings_2021.geojson"
)
inspections_with_buildings_2022 = gpd.read_file(
    "/capstone/wildfire_prep/data/joined_inspections_buildings/inspections_with_buildings_2022.geojson"
)
inspections_with_buildings_2023 = gpd.read_file(
    "/capstone/wildfire_prep/data/joined_inspections_buildings/inspections_with_buildings_2023.geojson"
)

In [19]:
inspections_with_buildings_length = (
    len(inspections_with_buildings_2019)
    + len(inspections_with_buildings_2020)
    + len(inspections_with_buildings_2021)
    + len(inspections_with_buildings_2022)
    + len(inspections_with_buildings_2023)
)

inspections_with_buildings_length

67580

In [20]:
# length of buffer geometries combined, loaded at the top

buffer_geometries_length

89357

In [21]:
inspections_buffered_buildings_all = gpd.read_file(
    "/capstone/wildfire_prep/data/joined_inspections_parcels/inspections_buffered_buildings_all.geojson"
)
print(len(inspections_buffered_buildings_all))

88376

In [22]:
inspections_parcels_all = gpd.read_file(
    "/capstone/wildfire_prep/data/joined_inspections_parcels/inspections_parcels_all.geojson"
)
print(len(inspections_parcels_all))

68352

In [23]:
buffered_buildings_2022 = gpd.read_file(
    "/capstone/wildfire_prep/data/joined_inspections_parcels/buffered_buildings_2022.geojson"
)
print(len(buffered_buildings_2022))
print(len(inspections_with_buildings_2022))

9035
13642

In [24]:
inspections_2019 = gpd.read_file(
    "/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2019.geojson"
)
inspections_2020 = gpd.read_file(
    "/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2020.geojson"
)
inspections_2021 = gpd.read_file(
    "/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2021.geojson"
)
inspections_2022 = gpd.read_file(
    "/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2022.geojson"
)
inspections_2023 = gpd.read_file(
    "/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2023.geojson"
)

In [25]:
inspections_clean_status_length = (
    len(inspections_2019)
    + len(inspections_2020)
    + len(inspections_2021)
    + len(inspections_2022)
    + len(inspections_2023)
)

inspections_clean_status_length

67580

In [26]:
training_geometries_2019 = gpd.read_file(
    "/capstone/wildfire_prep/data/training_geometries/training_geometries_2019.geojson"
)
training_geometries_2020 = gpd.read_file(
    "/capstone/wildfire_prep/data/training_geometries/training_geometries_2020.geojson"
)
training_geometries_2021 = gpd.read_file(
    "/capstone/wildfire_prep/data/training_geometries/training_geometries_2021.geojson"
)
training_geometries_2022 = gpd.read_file(
    "/capstone/wildfire_prep/data/training_geometries/training_geometries_2022.geojson"
)
training_geometries_2023 = gpd.read_file(
    "/capstone/wildfire_prep/data/training_geometries/training_geometries_2023.geojson"
)

training_geometries_combined_length = (
    len(training_geometries_2019)
    + len(training_geometries_2020)
    + len(training_geometries_2021)
    + len(training_geometries_2022)
    + len(training_geometries_2023)
)

training_geometries_combined_length

67580

In [27]:
print(f"cleaned_status: Inspections files combined length: {inspections_clean_status_length}")
print(
    f"joined_inspections_buildings: Inspections with buildings files combined length: {inspections_with_buildings_length}"
)
print(
    f"joined_inspections_parcels: Inspections with parcels length: {len(inspections_parcels_all)}"
)
print(
    f"joined_inspections_parcels: Inspections with buffered buildings all length: {len(inspections_buffered_buildings_all)}"
)
print(
    f"buffer_geometries: Inspections with Buffered Geometries files combined length: {buffer_geometries_length}"
)
print(f"training_geometries: Training geometries combined length: {training_geometries_combined_length}")

cleaned_status: Inspections files combined length: 67580
joined_inspections_buildings: Inspections with buildings files combined length: 67580
joined_inspections_parcels: Inspections with parcels length: 68352
joined_inspections_parcels: Inspections with buffered buildings all length: 88376
buffer_geometries: Inspections with Buffered Geometries files combined length: 89357
training_geometries: Training geometries combined length: 67580

In [28]:

training_geometries_2019

,fulcrum_id,apn,Date,year,month,status,geometry
0,d9a4d031-d16d-4c84-b32c-f3fcd7d945df,None,2019-06-05,2019,6,Compliant,"POLYGON ((-2892.357 -371905.217, -2813.179 -37..."
1,7f9b6d98-548d-4b94-97c6-82cbddf84d99,None,2019-05-09,2019,5,Compliant,"POLYGON ((-8475.394 -370860.259, -8368.416 -37..."
2,03afdf39-173a-4f02-bfdc-e0725e554959,None,2019-05-09,2019,5,Compliant,"POLYGON ((-8253.618 -371183.727, -8136.129 -37..."
3,941e29b0-6cd3-4c7e-a919-b8f2410b4a2b,None,2019-05-09,2019,5,Compliant,"POLYGON ((-8201.866 -370989.432, -8091.086 -37..."
4,abe890ba-3269-4ef6-84d7-4a9b6bfd717e,None,2019-12-17,2019,12,Compliant,"POLYGON ((-8065.883 -370931.624, -7966.144 -37..."
...,...,...,...,...,...,...,...
14670,None,None,2019-06-14,2019,6,Compliant,"POLYGON ((30822.983 -396671.555, 30900.797 -39..."
14671,None,None,2019-08-01,2019,8,Compliant,"POLYGON ((30894.968 -396708.273, 30972.782 -39..."
14672,None,None,2019-08-01,2019,8,Non-Compliant,"POLYGON ((32892.059 -396994.879, 32969.873 -39..."
14673,None,None,2019-06-18,2019,6,Compliant,"POLYGON ((31869.591 -396830.827, 31947.405 -39..."
14674,None,None,2019-06-25,2019,6,Compliant,"POLYGON ((33528.875 -397648.221, 33606.689 -39..."