In [104]:
import os
import sys
import numpy as np 
import pandas as pd
import geopandas as gpd

sys.path.append("../utils")

import config

pd.set_option("display.max_columns", None)

In [105]:
def read_geojson_with_geopandas(file_path):
        gdf = gpd.read_file(file_path)
        return gdf

insp_19 = read_geojson_with_geopandas("/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2019.geojson")
insp_20 = read_geojson_with_geopandas("/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2020.geojson")
insp_21 = read_geojson_with_geopandas("/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2021.geojson")
insp_22 = read_geojson_with_geopandas("/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2022.geojson")
insp_23 = read_geojson_with_geopandas("/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2023.geojson")

In [106]:
# Select only necessary columns. Columns in 2023 dataframe are different, but will be renamed in a later chunk

needed_columns = ["system_cre", "status", "latitude", "longitude", 'address_su', 'address_th', 'address__1', 'address_lo', 'address__2', 'address_ad', 'address_po', 'address_co', 'address_fu', 'Date', 'geometry']
needed_columns_23 = ["updated_at", "status", "latitude", "longitude", 'address_sub_thoroughfare', 'address_thoroughfare', 'address_suite', 'address_locality', 'address_sub_admin_area', 'address_admin_area', 'address_postal_code', 'address_country', 'address_full', 'Date', 'geometry']

In [107]:
# Narrow down all inspections dataframes to the necessary columns defined above

insp_19_clean = insp_19[needed_columns]
insp_20_clean = insp_20[needed_columns]
insp_21_clean = insp_21[needed_columns]
insp_22_clean = insp_22[needed_columns]
insp_23_clean = insp_23[needed_columns_23]

In [108]:
# Rename 2023 dataframe columns to match the others

colnames_23 = ["system_cre", "status", "latitude", "longitude", 'address_su', 'address_th', 'address__1', 'address_lo', 'address__2', 'address_ad', 'address_po', 'address_co', 'address_fu', 'Date', 'geometry']

insp_23_clean.columns = colnames_23

# verify column names change
print(insp_23_clean.columns.tolist())

['system_cre', 'status', 'latitude', 'longitude', 'address_su', 'address_th', 'address__1', 'address_lo', 'address__2', 'address_ad', 'address_po', 'address_co', 'address_fu', 'Date', 'geometry']

In [109]:
# Making copies

insp_19_clean = insp_19_clean.copy()
insp_20_clean = insp_20_clean.copy()
insp_21_clean = insp_21_clean.copy()
insp_22_clean = insp_22_clean.copy()
insp_23_clean = insp_23_clean.copy()

# Adding inspection year column

insp_19_clean['year'] = 2019
insp_20_clean['year'] = 2020
insp_21_clean['year'] = 2021
insp_22_clean['year'] = 2022
insp_23_clean['year'] = 2023

In [110]:
# Joining all inspections dataframes

all_inspections = pd.concat([insp_19_clean, insp_20_clean, insp_21_clean, insp_22_clean, insp_23_clean], axis=0, ignore_index=True)

# Fixing CRS to 3310, Albers

all_inspections = all_inspections.to_crs(epsg=3310)

print(all_inspections.crs)

# Making a copy

all_inspections_copy = all_inspections.copy()

EPSG:3310

In [111]:
# Import parcel data

parcels = os.path.join(config.data_dir, "parcel_boundaries", "cbiinputs.gdb")
parcels = gpd.read_file(parcels).to_crs(config.albers_crs)

In [112]:
# Checking parcel column names, and narrowing down the dataframe to only necessary columns

print(parcels.columns.tolist())

parcels_copy = parcels.copy()

parcel_columns = ['situs1', 'shape_leng', 'shape_Length', 'shape_Area', 'geometry']
parcels_copy = parcels[parcel_columns]

['apn', 'layer', 'situs1', 'situs2', 'acreage', 'landuse', 'usecode', 'tra', 'docnum', 'docdate', 'pcttransf', 'valreason', 'nontaxcode', 'sbeno', 'agpres', 'landvalue', 'strimpr', 'tradefix', 'livimpr', 'perpropdec', 'perspropun', 'mobilehome', 'exemptions', 'exempcode', 'homeowex', 'netsecval', 'net_impr', 'net_pers', 'net_unx', 'net_av', 'mailx1', 'mailx2', 'mnumber', 'mfrac', 'mdir', 'mstreet', 'mstrsuffix', 'munittype', 'munitnumb', 'pobox', 'mcity', 'mzip', 'mzipext', 'mstate', 'country', 'snum', 'sfra', 'sdir', 'sstreet', 'sstreetsuf', 'sunittype', 'sunitnumb', 'scity', 'szip', 'szipext', 'm_address1', 'm_address2', 'asmrollid', 'apn9', 'propid', 'sqfootage', 'yearbuilt', 'bedrooms', 'bathrooms', 'taxbill', 'permit', 'bkpglnk', 'gen_inquir', 'web_link', 'maptype', 'recmapnum', 'tractname', 'recmapbook', 'recmapdate', 'blocksecti', 'lotnum', 'unitnum', 'cbiinputs_zachary_canter_assess', 'areaunit', 'recdatetim', 'recuserid', 'recuserlog', 'section', 'township', 'range', 'shape_leng', 'shape_Length', 'shape_Area', 'geometry']

In [113]:
# Joining parcels to inspections dataframe 

inspections_parcels = gpd.sjoin(
        parcels_copy, all_inspections_copy, how="inner", predicate="contains")

# Dropping an unnecessary column, could be done more neatly 

inspections_parcels = inspections_parcels.drop(columns=['address__1'])

print(parcels_copy.crs)
print(all_inspections_copy.crs)

EPSG:3310
EPSG:3310

In [114]:
inspections_parcels

,situs1,shape_leng,shape_Length,shape_Area,geometry,index_right,system_cre,status,latitude,longitude,address_su,address_th,address_lo,address__2,address_ad,address_po,address_co,address_fu,Date,year
203,1450 CAMINO MANADERO,903.335649,903.335649,40102.354471,"MULTIPOLYGON (((16347.387 -394504.877, 16342.5...",16177,2020-05-18 16:29:44,Compliant,34.466073,-119.821791,1450,Camino Manadero,Santa Barbara,Santa Barbara,CA,93111,US,1450 Camino Manadero Santa Barbara Santa Barba...,2020-06-27,2020
203,1450 CAMINO MANADERO,903.335649,903.335649,40102.354471,"MULTIPOLYGON (((16347.387 -394504.877, 16342.5...",1472,2019-05-28 15:21:11,Compliant,34.466073,-119.821791,1450,Camino Manadero,Santa Barbara,Santa Barbara,CA,93111,US,1450 Camino Manadero Santa Barbara Santa Barba...,2019-06-25,2019
203,1450 CAMINO MANADERO,903.335649,903.335649,40102.354471,"MULTIPOLYGON (((16347.387 -394504.877, 16342.5...",28016,2021-04-05 08:56:31,Compliant,34.466073,-119.821791,1450,Camino Manadero,Santa Barbara,Santa Barbara,CA,93111,US,1450 Camino Manadero Santa Barbara Santa Barba...,2021-06-26,2021
203,1450 CAMINO MANADERO,903.335649,903.335649,40102.354471,"MULTIPOLYGON (((16347.387 -394504.877, 16342.5...",46334,2022-04-06 09:59:33,Compliant,34.466073,-119.821791,1450,Camino Manadero,Santa Barbara,Santa Barbara,CA,93111,US,1450 Camino Manadero Santa Barbara Santa Barba...,2022-07-05,2022
205,1475 CAMINO MELENO,1113.961402,1113.961402,57984.774296,"MULTIPOLYGON (((16811.85 -394379.557, 16800.14...",1538,2019-05-28 15:21:27,Compliant,34.466445,-119.817230,1475,Camino Meleno,Santa Barbara,Santa Barbara,CA,93111,US,1475 Camino Meleno Santa Barbara Santa Barbara...,2019-06-25,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132303,2685 HWY 33,2962.102000,2962.102000,482989.154940,"MULTIPOLYGON (((46691.776 -350305.727, 46682.3...",54407,2023-08-22 17:28:10,Compliant,34.864993,-119.489451,2685,Highway 33,Maricopa,Santa Barbara,CA,93252,US,2685 Highway 33 Maricopa Santa Barbara CA 9325...,2023-08-22,2023
132303,2685 HWY 33,2962.102000,2962.102000,482989.154940,"MULTIPOLYGON (((46691.776 -350305.727, 46682.3...",40773,2022-04-05 13:47:50,Compliant,34.864993,-119.489451,2685,Highway 33,Maricopa,Santa Barbara,CA,93252,US,2685 Highway 33 Maricopa Santa Barbara CA 9325...,2022-06-28,2022
132303,2685 HWY 33,2962.102000,2962.102000,482989.154940,"MULTIPOLYGON (((46691.776 -350305.727, 46682.3...",36281,2021-04-05 09:30:25,Compliant,34.864993,-119.489451,2685,Highway 33,Maricopa,Santa Barbara,CA,93252,US,2685 Highway 33 Maricopa Santa Barbara CA 9325...,2021-08-17,2021
132303,2685 HWY 33,2962.102000,2962.102000,482989.154940,"MULTIPOLYGON (((46691.776 -350305.727, 46682.3...",9958,2019-05-28 16:13:31,Compliant,34.864993,-119.489451,2685,Highway 33,Maricopa,Santa Barbara,CA,93252,US,2685 Highway 33 Maricopa Santa Barbara CA 9325...,2019-06-11,2019
132303,2685 HWY 33,2962.102000,2962.102000,482989.154940,"MULTIPOLYGON (((46691.776 -350305.727, 46682.3...",23174,2020-05-19 14:58:02,Compliant,34.864993,-119.489451,2685,Highway 33,Maricopa,Santa Barbara,CA,93252,US,2685 Highway 33 Maricopa Santa Barbara CA 9325...,2020-06-20,2020

In [115]:
buffered_buildings = read_geojson_with_geopandas('/capstone/wildfire_prep/data/joined_inspections_parcels/buffered_buildings_2022.geojson')

In [116]:
buffered_buildings_copy = buffered_buildings.copy()

print(buffered_buildings.columns.tolist())

buff_buildings_columns = ['geometry']

buffered_buildings_copy = buffered_buildings_copy[buff_buildings_columns]

['release', 'capture_dates_range', 'STATEFP', 'COUNTYFP', 'COUNTYNS', 'GEOID', 'NAME', 'NAMELSAD', 'LSAD', 'CLASSFP', 'MTFCC', 'CSAFP', 'CBSAFP', 'METDIVFP', 'FUNCSTAT', 'ALAND', 'AWATER', 'INTPTLAT', 'INTPTLON', 'Shape_Leng', 'Shape_Area', 'index_right', 'apn_left_1', 'layer_1', 'situs1_1', 'situs2_1', 'acreage_1', 'landuse_1', 'usecode_1', 'tra_1', 'docnum_1', 'docdate_1', 'pcttransf_1', 'valreason_1', 'nontaxcode_1', 'sbeno_1', 'agpres_1', 'landvalue_1', 'strimpr_1', 'tradefix_1', 'livimpr_1', 'perpropdec_1', 'perspropun_1', 'mobilehome_1', 'exemptions_1', 'exempcode_1', 'homeowex_1', 'netsecval_1', 'net_impr_1', 'net_pers_1', 'net_unx_1', 'net_av_1', 'mailx1_1', 'mailx2_1', 'mnumber_1', 'mfrac_1', 'mdir_1', 'mstreet_1', 'mstrsuffix_1', 'munittype_1', 'munitnumb_1', 'pobox_1', 'mcity_1', 'mzip_1', 'mzipext_1', 'mstate_1', 'country_1', 'snum_1', 'sfra_1', 'sdir_1', 'sstreet_1', 'sstreetsuf_1', 'sunittype_1', 'sunitnumb_1', 'scity_1', 'szip_1', 'szipext_1', 'm_address1_1', 'm_address2_1', 'asmrollid_1', 'apn9_1', 'propid_1', 'sqfootage_1', 'yearbuilt_left_1', 'bedrooms_1', 'bathrooms_1', 'taxbill_1', 'permit_1', 'bkpglnk_1', 'gen_inquir_1', 'web_link_1', 'maptype_1', 'recmapnum_1', 'tractname_1', 'recmapbook_1', 'recmapdate_1', 'blocksecti_1', 'lotnum_1', 'unitnum_1', 'cbiinputs_zachary_canter_assess_1', 'areaunit_1', 'recdatetim_1', 'recuserid_1', 'recuserlog_1', 'section_1', 'township_1', 'range_1', 'shape_leng_1', 'shape_Length_1', 'shape_Area_1', 'log_acreage_1', 'fulcrum_id_1', 'created_at_1', 'updated_at_1', 'system_cre_1', 'system_upd_1', 'version_1', 'status_1', 'project_1', 'assigned_t_1', 'latitude_1', 'longitude_1', 'report_tit_1', 'globalid_1', 'keyid_1', 'propertyst_1', 'inspection_1', 'inspectorp_1', 'inspecti_1_1', 'addressvis_1', 'address_su_1', 'address_th_1', 'address__1_1', 'address_lo_1', 'address__2_1', 'address_ad_1', 'address_po_1', 'address_co_1', 'address_fu_1', 'calfireuni_1', 'county_1', 'community_1', 'community__1', 'battalion_1', 'enginenumb_1', 'stationnam_1', 'shift_1', 'shift_juli_1', 'accessegre_1', 'occupantho_1', 'deliveryno_1', 'inspecti_2_1', 'a_removebr_1', 'b_removele_1', 'c_removede_1', 'd_removede_1', 'e_removefl_1', 'f_removefl_1', 'g_relocate_1', 'h_cutannua_1', 'i_removefu_1', 'j_exposedw_1', 'k_removede_1', 'l_removelo_1', 'm_outbuild_1', 'n_displaya_1', 'o_stovepip_1', 'recommendc_1', 'waterstora_1', 'water_sour_1', 'can_engine_1', 'water_stor_1', 'water_comm_1', 'structuret_1', 'structureh_1', 'roofconstr_1', 'eaves_1', 'ventscreen_1', 'exteriorsi_1', 'windowpane_1', 'deckporchg_1', 'deckporche_1', 'patiocover_1', 'fenceattac_1', 'propanetan_1', 'utilitymis_1', 'utilitym_1_1', 'nonhabitab_1', 'escalateto_1', 'reinspecti_1', 'citationnu_1', 'number_of__1', 'photoid_1', 'photoid_ca_1', 'le100numbe_1', 'inspecti_3_1', 'coredata_1', 'firescopei_1', 'apn_right_1', 'yearbuilt_right_1', 'siteaddres_1', 'numberofst_1', 'appenddate_1', 'editstatus_1', 'calculated_1', 'calculat_1_1', 'calculat_2_1', 'textfield1_1', 'textfield2_1', 'numberfiel_1', 'numberfi_1_1', 'previousyr_1', 'previous_1_1', 'calculat_3_1', 'calculat_4_1', 'creationda_1', 'editdate_1', 'creator_1', 'editor_1', 'Date_1', 'apn_left_2', 'layer_2', 'situs1_2', 'situs2_2', 'acreage_2', 'landuse_2', 'usecode_2', 'tra_2', 'docnum_2', 'docdate_2', 'pcttransf_2', 'valreason_2', 'nontaxcode_2', 'sbeno_2', 'agpres_2', 'landvalue_2', 'strimpr_2', 'tradefix_2', 'livimpr_2', 'perpropdec_2', 'perspropun_2', 'mobilehome_2', 'exemptions_2', 'exempcode_2', 'homeowex_2', 'netsecval_2', 'net_impr_2', 'net_pers_2', 'net_unx_2', 'net_av_2', 'mailx1_2', 'mailx2_2', 'mnumber_2', 'mfrac_2', 'mdir_2', 'mstreet_2', 'mstrsuffix_2', 'munittype_2', 'munitnumb_2', 'pobox_2', 'mcity_2', 'mzip_2', 'mzipext_2', 'mstate_2', 'country_2', 'snum_2', 'sfra_2', 'sdir_2', 'sstreet_2', 'sstreetsuf_2', 'sunittype_2', 'sunitnumb_2', 'scity_2', 'szip_2', 'szipext_2', 'm_address1_2', 'm_address2_2', 'asmrollid_2', 'apn9_2', 'propid_2', 'sqfootage_2', 'yearbuilt_left_2', 'bedrooms_2', 'bathrooms_2', 'taxbill_2', 'permit_2', 'bkpglnk_2', 'gen_inquir_2', 'web_link_2', 'maptype_2', 'recmapnum_2', 'tractname_2', 'recmapbook_2', 'recmapdate_2', 'blocksecti_2', 'lotnum_2', 'unitnum_2', 'cbiinputs_zachary_canter_assess_2', 'areaunit_2', 'recdatetim_2', 'recuserid_2', 'recuserlog_2', 'section_2', 'township_2', 'range_2', 'shape_leng_2', 'shape_Length_2', 'shape_Area_2', 'log_acreage_2', 'fulcrum_id_2', 'created_at_2', 'updated_at_2', 'system_cre_2', 'system_upd_2', 'version_2', 'status_2', 'project_2', 'assigned_t_2', 'latitude_2', 'longitude_2', 'report_tit_2', 'globalid_2', 'keyid_2', 'propertyst_2', 'inspection_2', 'inspectorp_2', 'inspecti_1_2', 'addressvis_2', 'address_su_2', 'address_th_2', 'address__1_2', 'address_lo_2', 'address__2_2', 'address_ad_2', 'address_po_2', 'address_co_2', 'address_fu_2', 'calfireuni_2', 'county_2', 'community_2', 'community__2', 'battalion_2', 'enginenumb_2', 'stationnam_2', 'shift_2', 'shift_juli_2', 'accessegre_2', 'occupantho_2', 'deliveryno_2', 'inspecti_2_2', 'a_removebr_2', 'b_removele_2', 'c_removede_2', 'd_removede_2', 'e_removefl_2', 'f_removefl_2', 'g_relocate_2', 'h_cutannua_2', 'i_removefu_2', 'j_exposedw_2', 'k_removede_2', 'l_removelo_2', 'm_outbuild_2', 'n_displaya_2', 'o_stovepip_2', 'recommendc_2', 'waterstora_2', 'water_sour_2', 'can_engine_2', 'water_stor_2', 'water_comm_2', 'structuret_2', 'structureh_2', 'roofconstr_2', 'eaves_2', 'ventscreen_2', 'exteriorsi_2', 'windowpane_2', 'deckporchg_2', 'deckporche_2', 'patiocover_2', 'fenceattac_2', 'propanetan_2', 'utilitymis_2', 'utilitym_1_2', 'nonhabitab_2', 'escalateto_2', 'reinspecti_2', 'citationnu_2', 'number_of__2', 'photoid_2', 'photoid_ca_2', 'le100numbe_2', 'inspecti_3_2', 'coredata_2', 'firescopei_2', 'apn_right_2', 'yearbuilt_right_2', 'siteaddres_2', 'numberofst_2', 'appenddate_2', 'editstatus_2', 'calculated_2', 'calculat_1_2', 'calculat_2_2', 'textfield1_2', 'textfield2_2', 'numberfiel_2', 'numberfi_1_2', 'previousyr_2', 'previous_1_2', 'calculat_3_2', 'calculat_4_2', 'creationda_2', 'editdate_2', 'creator_2', 'editor_2', 'Date_2', 'area', 'geometry']

In [117]:
buffered_buildings_copy

                                               geometry
0     POLYGON ((-22767.476 -375448.119, -23014.787 -...
1     POLYGON ((-9290.574 -378632.312, -9035.561 -37...
2     POLYGON ((-38766.251 -371421.02, -38538.65 -37...
3     POLYGON ((-11561.332 -372335.927, -11718.559 -...
4     POLYGON ((-23742.879 -348820.427, -23927.393 -...
...                                                 ...
9030  POLYGON ((-42570.319 -369065.356, -42570.319 -...
9031  POLYGON ((-42539.328 -367092.847, -42539.446 -...
9032  POLYGON ((-8759.709 -378740.536, -8759.709 -37...
9033  POLYGON ((-42551.126 -367015.662, -42551.159 -...
9034  POLYGON ((13217.108 -395211.873, 13217.061 -39...

[9035 rows x 1 columns]

In [118]:
inspections_buffbuildings = gpd.sjoin(
        buffered_buildings_copy, all_inspections_copy, how="inner", predicate="contains")

In [119]:
inspections_buffbuildings

,geometry,index_right,system_cre,status,latitude,longitude,address_su,address_th,address__1,address_lo,address__2,address_ad,address_po,address_co,address_fu,Date,year
1,"POLYGON ((-9290.574 -378632.312, -9035.561 -37...",37274,2021-04-05 09:33:18,Compliant,34.608120,-120.099620,2975,Mission Dr,None,Solvang,Santa Barbara,CA,93463,US,2975 Mission Dr Solvang Santa Barbara CA 93463 US,2021-07-08,2021
1,"POLYGON ((-9290.574 -378632.312, -9035.561 -37...",10929,2019-05-28 16:18:04,Compliant,34.608120,-120.099620,2975,Mission Dr,None,Solvang,Santa Barbara,CA,93463,US,2975 Mission Dr Solvang Santa Barbara CA 93463 US,2019-10-10,2019
1,"POLYGON ((-9290.574 -378632.312, -9035.561 -37...",23982,2020-05-19 15:01:53,Compliant,34.608120,-120.099620,2975,Mission Dr,None,Solvang,Santa Barbara,CA,93463,US,2975 Mission Dr Solvang Santa Barbara CA 93463 US,2020-07-10,2020
1,"POLYGON ((-9290.574 -378632.312, -9035.561 -37...",41709,2022-04-05 13:50:56,Compliant,34.608120,-120.099620,2975,Mission Dr,None,Solvang,Santa Barbara,CA,93463,US,2975 Mission Dr Solvang Santa Barbara CA 93463 US,2022-08-15,2022
1,"POLYGON ((-9290.574 -378632.312, -9035.561 -37...",55317,2023-08-15 12:41:48,Compliant,34.608120,-120.099620,2975,Mission Dr,None,Solvang,Santa Barbara,CA,93463,US,2975 Mission Dr Solvang Santa Barbara CA 93463 US,2023-08-14,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8945,"POLYGON ((22007.218 -395742.615, 22004.059 -39...",45920,2022-04-06 09:58:21,Compliant,34.454282,-119.760424,4120,Via Andorra,None,Santa Barbara,Santa Barbara,CA,93110,US,4120 Via Andorra Santa Barbara Santa Barbara C...,2022-06-29,2022
8945,"POLYGON ((22007.218 -395742.615, 22004.059 -39...",59408,2023-06-21 17:00:00,Compliant,34.454282,-119.760424,4120,Via Andorra,None,Santa Barbara,Santa Barbara,CA,93110,US,4120 Via Andorra Santa Barbara Santa Barbara C...,2023-06-21,2023
8945,"POLYGON ((22007.218 -395742.615, 22004.059 -39...",27596,2021-04-05 08:55:38,Compliant,34.454282,-119.760424,4120,Via Andorra,None,Santa Barbara,Santa Barbara,CA,93110,US,4120 Via Andorra Santa Barbara Santa Barbara C...,2021-06-12,2021
8945,"POLYGON ((22007.218 -395742.615, 22004.059 -39...",1053,2019-05-28 15:19:48,Compliant,34.454282,-119.760424,4120,Via Andorra,None,Santa Barbara,Santa Barbara,CA,93110,US,4120 Via Andorra Santa Barbara Santa Barbara C...,2019-06-07,2019
8945,"POLYGON ((22007.218 -395742.615, 22004.059 -39...",15760,2020-05-18 16:28:16,Compliant,34.454282,-119.760424,4120,Via Andorra,None,Santa Barbara,Santa Barbara,CA,93110,US,4120 Via Andorra Santa Barbara Santa Barbara C...,2020-07-29,2020

In [120]:
inspections_parcels

,situs1,shape_leng,shape_Length,shape_Area,geometry,index_right,system_cre,status,latitude,longitude,address_su,address_th,address_lo,address__2,address_ad,address_po,address_co,address_fu,Date,year
203,1450 CAMINO MANADERO,903.335649,903.335649,40102.354471,"MULTIPOLYGON (((16347.387 -394504.877, 16342.5...",16177,2020-05-18 16:29:44,Compliant,34.466073,-119.821791,1450,Camino Manadero,Santa Barbara,Santa Barbara,CA,93111,US,1450 Camino Manadero Santa Barbara Santa Barba...,2020-06-27,2020
203,1450 CAMINO MANADERO,903.335649,903.335649,40102.354471,"MULTIPOLYGON (((16347.387 -394504.877, 16342.5...",1472,2019-05-28 15:21:11,Compliant,34.466073,-119.821791,1450,Camino Manadero,Santa Barbara,Santa Barbara,CA,93111,US,1450 Camino Manadero Santa Barbara Santa Barba...,2019-06-25,2019
203,1450 CAMINO MANADERO,903.335649,903.335649,40102.354471,"MULTIPOLYGON (((16347.387 -394504.877, 16342.5...",28016,2021-04-05 08:56:31,Compliant,34.466073,-119.821791,1450,Camino Manadero,Santa Barbara,Santa Barbara,CA,93111,US,1450 Camino Manadero Santa Barbara Santa Barba...,2021-06-26,2021
203,1450 CAMINO MANADERO,903.335649,903.335649,40102.354471,"MULTIPOLYGON (((16347.387 -394504.877, 16342.5...",46334,2022-04-06 09:59:33,Compliant,34.466073,-119.821791,1450,Camino Manadero,Santa Barbara,Santa Barbara,CA,93111,US,1450 Camino Manadero Santa Barbara Santa Barba...,2022-07-05,2022
205,1475 CAMINO MELENO,1113.961402,1113.961402,57984.774296,"MULTIPOLYGON (((16811.85 -394379.557, 16800.14...",1538,2019-05-28 15:21:27,Compliant,34.466445,-119.817230,1475,Camino Meleno,Santa Barbara,Santa Barbara,CA,93111,US,1475 Camino Meleno Santa Barbara Santa Barbara...,2019-06-25,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132303,2685 HWY 33,2962.102000,2962.102000,482989.154940,"MULTIPOLYGON (((46691.776 -350305.727, 46682.3...",54407,2023-08-22 17:28:10,Compliant,34.864993,-119.489451,2685,Highway 33,Maricopa,Santa Barbara,CA,93252,US,2685 Highway 33 Maricopa Santa Barbara CA 9325...,2023-08-22,2023
132303,2685 HWY 33,2962.102000,2962.102000,482989.154940,"MULTIPOLYGON (((46691.776 -350305.727, 46682.3...",40773,2022-04-05 13:47:50,Compliant,34.864993,-119.489451,2685,Highway 33,Maricopa,Santa Barbara,CA,93252,US,2685 Highway 33 Maricopa Santa Barbara CA 9325...,2022-06-28,2022
132303,2685 HWY 33,2962.102000,2962.102000,482989.154940,"MULTIPOLYGON (((46691.776 -350305.727, 46682.3...",36281,2021-04-05 09:30:25,Compliant,34.864993,-119.489451,2685,Highway 33,Maricopa,Santa Barbara,CA,93252,US,2685 Highway 33 Maricopa Santa Barbara CA 9325...,2021-08-17,2021
132303,2685 HWY 33,2962.102000,2962.102000,482989.154940,"MULTIPOLYGON (((46691.776 -350305.727, 46682.3...",9958,2019-05-28 16:13:31,Compliant,34.864993,-119.489451,2685,Highway 33,Maricopa,Santa Barbara,CA,93252,US,2685 Highway 33 Maricopa Santa Barbara CA 9325...,2019-06-11,2019
132303,2685 HWY 33,2962.102000,2962.102000,482989.154940,"MULTIPOLYGON (((46691.776 -350305.727, 46682.3...",23174,2020-05-19 14:58:02,Compliant,34.864993,-119.489451,2685,Highway 33,Maricopa,Santa Barbara,CA,93252,US,2685 Highway 33 Maricopa Santa Barbara CA 9325...,2020-06-20,2020

In [121]:
print("Percent of values in columns that are unique: \n")
for col in insp_21:
    print(
        f"{col}: {
            round(
                (insp_21[col].unique().shape[0])/(len(insp_21)) * 100, 
                4)
            }%"
    )

Percent of values in columns that are unique:

fulcrum_id: 100.0%
created_at: 28.0403%
updated_at: 99.7788%
system_cre: 14.9657%
system_upd: 98.694%
version: 0.0571%
status: 0.0143%
project: 0.0071%
assigned_t: 0.0071%
latitude: 96.8598%
longitude: 97.2524%
report_tit: 0.0071%
globalid: 0.0071%
keyid: 0.0071%
propertyst: 0.0071%
inspection: 0.0071%
inspectorp: 0.0214%
inspecti_1: 0.8279%
addressvis: 0.0285%
address_su: 35.2269%
address_th: 7.3223%
address__1: 0.0357%
address_lo: 0.157%
address__2: 0.0214%
address_ad: 0.0357%
address_po: 0.1213%
address_co: 0.0357%
address_fu: 86.8113%
calfireuni: 0.0071%
county: 0.0071%
community: 0.4353%
community_: 0.0071%
battalion: 0.0214%
enginenumb: 0.1713%
stationnam: 0.1142%
shift: 0.0428%
accessegre: 0.0143%
occupantho: 0.0143%
deliveryno: 0.0214%
inspecti_2: 0.0357%
a_removebr: 0.0143%
b_removele: 0.0143%
c_removede: 0.0143%
d_removede: 0.0143%
e_removefl: 0.0143%
f_removefl: 0.0143%
g_relocate: 0.0143%
h_cutannua: 0.0143%
i_removefu: 0.0143%
j_exposedw: 0.0143%
k_removede: 0.0143%
l_removelo: 0.0143%
m_outbuild: 0.0143%
n_displaya: 0.0143%
o_stovepip: 0.0143%
recommendc: 0.0214%
waterstora: 0.0214%
water_sour: 0.7708%
can_engine: 0.0214%
water_stor: 0.0428%
water_comm: 1.7271%
structuret: 0.1071%
structureh: 0.0357%
roofconstr: 0.0571%
eaves: 0.0357%
ventscreen: 0.0428%
exteriorsi: 0.05%
windowpane: 0.0357%
deckporchg: 0.0357%
deckporche: 0.0357%
patiocover: 0.0285%
fenceattac: 0.0357%
propanetan: 0.05%
utilitymis: 0.0285%
utilitym_1: 0.0856%
nonhabitab: 0.0785%
escalateto: 0.0071%
reinspecti: 0.0071%
citationnu: 0.0071%
number_of_: 0.0785%
photoid: 0.1427%
photoid_ca: 0.0357%
le100numbe: 0.0071%
inspecti_3: 0.0071%
coredata: 0.0071%
firescopei: 0.0071%
responsibi: 0.0143%
apn: 0.7422%
yearbuilt: 0.9064%
siteaddres: 0.0071%
numberofst: 0.0071%
appenddate: 0.0071%
editstatus: 0.0071%
calculated: 0.0071%
calculat_1: 0.0071%
calculat_2: 0.0071%
textfield1: 0.0071%
textfield2: 0.0071%
numberfiel: 0.0071%
numberfi_1: 0.0071%
previousyr: 0.0071%
previous_1: 0.0071%
calculat_3: 0.0071%
calculat_4: 0.0071%
creationda: 0.8207%
editdate: 1.2632%
creator: 0.0071%
editor: 0.0071%
Date: 0.8279%
geometry: 99.9144%

#### Josh's opinion

Keep columns by default if they have (or at least mark them for likely usefulness)...
* % unique values > 0.1% 
* % unique values < 80%

For the rest of the columns, investigate whether to keep them on a case by case basis...
* high uniqueness may indicate some kind of unique identifier
* low uniqueness column may still be important