In [91]:
import os
import sys
import numpy as np 
import pandas as pd
import geopandas as gpd

sys.path.append("../utils")

import config

pd.set_option("display.max_columns", None)

In [92]:
# OLD GEOMETRIES -- don't use these.

# def read_geojson_with_geopandas(file_path):
#         gdf = gpd.read_file(file_path)
#         return gdf

# insp_19 = read_geojson_with_geopandas("/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2019.geojson")
# insp_20 = read_geojson_with_geopandas("/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2020.geojson")
# insp_21 = read_geojson_with_geopandas("/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2021.geojson")
# insp_22 = read_geojson_with_geopandas("/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2022.geojson")
# insp_23 = read_geojson_with_geopandas("/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2023.geojson")

In [93]:
# Loading in inspections data with newly calculated geometries 4/28/25

insp_19 = gpd.read_file(
    "/capstone/wildfire_prep/data/buffer_geometries/buffer_geometries_2019.geojson"
)
insp_20 = gpd.read_file(
    "/capstone/wildfire_prep/data/buffer_geometries/buffer_geometries_2020.geojson"
)
insp_21 = gpd.read_file(
    "/capstone/wildfire_prep/data/buffer_geometries/buffer_geometries_2021.geojson"
)
insp_22 = gpd.read_file(
    "/capstone/wildfire_prep/data/buffer_geometries/buffer_geometries_2022.geojson"
)
insp_23 = gpd.read_file(
    "/capstone/wildfire_prep/data/buffer_geometries/buffer_geometries_2023.geojson"
)

In [94]:
# Select only necessary columns. Columns in 2023 dataframe are different, but will be renamed in a later chunk

needed_columns = [
    "system_cre",
    "status",
    "latitude",
    "longitude",
    "address_su",
    "address_th",
    "address__1",
    "address_lo",
    "address__2",
    "address_po",
    "address_fu",
    "Date",
    "geometry",
    "inspection",
    "structuret"
]
needed_columns_23 = [
    "updated_at",
    "status",
    "latitude",
    "longitude",
    "address_sub_thoroughfare",
    "address_thoroughfare",
    "address_suite",
    "address_locality",
    "address_sub_admin_area",
    "address_postal_code",
    "address_full",
    "Date",
    "geometry",
    "inspectiondate_calculate",
    "structuretype"
]

In [95]:
# Narrow down all inspections dataframes to the necessary columns defined above

insp_19_clean = insp_19[needed_columns]
insp_20_clean = insp_20[needed_columns]
insp_21_clean = insp_21[needed_columns]
insp_22_clean = insp_22[needed_columns]
insp_23_clean = insp_23[needed_columns_23]

In [96]:
# Rename 2023 dataframe columns to match the others

colnames_23 = [
    "system_cre",
    "status",
    "latitude",
    "longitude",
    "address_su",
    "address_th",
    "address__1",
    "address_lo",
    "address__2",
    "address_po",
    "address_fu",
    "Date",
    "geometry",
    "inspection",
    "structuret"
]

insp_23_clean.columns = colnames_23

# verify column names change
print(insp_23_clean.columns.tolist())

['system_cre', 'status', 'latitude', 'longitude', 'address_su', 'address_th', 'address__1', 'address_lo', 'address__2', 'address_po', 'address_fu', 'Date', 'geometry', 'inspection', 'structuret']

In [97]:
# Adding inspection year column

insp_19_clean['year'] = 2019
insp_20_clean['year'] = 2020
insp_21_clean['year'] = 2021
insp_22_clean['year'] = 2022
insp_23_clean['year'] = 2023

/Users/ryangreen/.conda/envs/prg/lib/python3.12/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/ryangreen/.conda/envs/prg/lib/python3.12/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/ryangreen/.conda/envs/prg/lib/python3.12/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/ryangreen/.conda/envs/prg/lib/python3.12/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)
/Users/ryangreen/.conda/envs/prg/lib/python3.12/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [98]:
# Joining all inspections dataframes

all_inspections = pd.concat([insp_19_clean, insp_20_clean, insp_21_clean, insp_22_clean, insp_23_clean], axis=0, ignore_index=True)

# converting 'system_cre' column to display single days, instead of days and times
all_inspections["system_cre"] = pd.to_datetime(all_inspections["system_cre"]).dt.date

In [99]:
all_inspections

,system_cre,status,latitude,longitude,address_su,address_th,address__1,address_lo,address__2,address_po,address_fu,Date,geometry,inspection,structuret,year
0,2019-05-07,Compliant,34.669616,-120.031160,3462,Brinkerhoff Rd,None,Santa Ynez,Santa Barbara,93460,3462 Brinkerhoff Rd Santa Ynez Santa Barbara C...,2019-06-05,"POLYGON ((-2813.179 -371821.557, -2813.179 -37...",2019-06-05,Utility or Miscellaneous Structure > 120 sqft,2019
1,2019-05-07,Compliant,34.679129,-120.091914,3290,Avenida Caballo,None,Santa Ynez,Santa Barbara,93460,3290 Avenida Caballo Santa Ynez Santa Barbara ...,2019-05-09,"POLYGON ((-8368.416 -370860.259, -8475.394 -37...",2019-05-09,Single Family Residence Multi Story,2019
2,2019-05-07,Compliant,34.676197,-120.089553,3350,Caballo Ln,None,Santa Ynez,Santa Barbara,93460,3350 Caballo Ln Santa Ynez Santa Barbara CA 93...,2019-05-09,"POLYGON ((-8253.618 -371073.707, -8136.129 -37...",2019-05-09,Single Family Residence Multi Story,2019
3,2019-05-07,Compliant,34.677982,-120.088944,3350,Caballo Ln,None,Santa Ynez,Santa Barbara,93460,3350 Caballo Ln Santa Ynez Santa Barbara CA 93...,2019-05-09,"POLYGON ((-8201.866 -370989.432, -8201.866 -37...",2019-05-09,Utility or Miscellaneous Structure > 120 sqft,2019
4,2019-05-07,Compliant,34.678469,-120.087539,3320 A,Canada Este Rd,None,Santa Ynez,Santa Barbara,93460,3320 A Canada Este Rd Santa Ynez Santa Barbara...,2019-12-17,"POLYGON ((-7966.144 -370818.558, -7966.144 -37...",2019-12-17,Single Family Residence Multi Story,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89352,2023-08-24,Non-Compliant,34.944801,-119.681560,71,Newsome St,None,New Cuyama,Santa Barbara County,93254,71 Newsome St New Cuyama Santa Barbara County ...,2023-08-14,"POLYGON ((29027.935 -341229.025, 29105.749 -34...",2023-08-14 00:00:00,Infrastructure (Essential Services),2023
89353,2023-08-23,Compliant,34.975333,-119.895858,2875,Cottonwood Canyon Rd,None,New Cuyama,Santa Barbara County,93454,2875 Cottonwood Canyon Rd New Cuyama Santa Bar...,2023-08-23,"POLYGON ((9463.523 -337882.689, 9541.337 -3378...",2023-08-23 00:00:00,Single Family Residence Single Story,2023
89354,2023-09-26,Compliant,34.458542,-119.814448,1118,N Patterson Ave,None,Santa Barbara,Santa Barbara County,93111,1118 N Patterson Ave Santa Barbara Santa Barba...,2023-09-26,"POLYGON ((17054.544 -395291.334, 17052.114 -39...",2023-09-26 00:00:00,Single Family Residence Single Story,2023
89355,2023-09-26,Compliant,34.458542,-119.814448,1118,N Patterson Ave,None,Santa Barbara,Santa Barbara County,93111,1118 N Patterson Ave Santa Barbara Santa Barba...,2023-09-26,"POLYGON ((17081.932 -395302.172, 17079.044 -39...",2023-09-26 00:00:00,Single Family Residence Single Story,2023
89356,2023-11-06,Compliant,34.870960,-120.382833,2114,Fallen Leaf Drive,None,Santa Maria,Santa Barbara,93455,2114 Fallen Leaf Drive Santa Maria Santa Barba...,2023-10-31,"POLYGON ((-34938.315 -349478.543, -34991.669 -...",2023-10-31 00:00:00,Single Family Residence Multi Story,2023

In [100]:
# rename columns to be more readable

rename_map = {
    "system_cre": "system_created",
    "status": "inspection_status",
    "latitude": "latitude",
    "longitude": "longitude",
    "address_su": "address_number",
    "address_th": "street",
    "address__1": "apt_number",
    "address_lo": "city",
    "address__2": "county",
    "address_ad": "state",
    "address_po": "zip_code",
    "address_co": "country",
    "address_fu": "address_full",
    "Date": "date",
    "geometry": "geometry",
    "inspection": "inspection_date",
    "structuret": "structure_type"
}

all_inspections = all_inspections.rename(columns=rename_map)

In [101]:
# Some dates in the 'inspection' column have the format '2023-08-22 00:00:00'.
# This chunk is to remove the occurrences of '00:00:00' and remove trailing whitespace.

all_inspections["inspection_date"] = (
    all_inspections["inspection_date"]
    .astype(str)
    .str.replace(" 00:00:00", "", regex=False)
    .str.strip()
)

In [102]:
all_inspections

,system_created,inspection_status,latitude,longitude,address_number,street,apt_number,city,county,zip_code,address_full,date,geometry,inspection_date,structure_type,year
0,2019-05-07,Compliant,34.669616,-120.031160,3462,Brinkerhoff Rd,None,Santa Ynez,Santa Barbara,93460,3462 Brinkerhoff Rd Santa Ynez Santa Barbara C...,2019-06-05,"POLYGON ((-2813.179 -371821.557, -2813.179 -37...",2019-06-05,Utility or Miscellaneous Structure > 120 sqft,2019
1,2019-05-07,Compliant,34.679129,-120.091914,3290,Avenida Caballo,None,Santa Ynez,Santa Barbara,93460,3290 Avenida Caballo Santa Ynez Santa Barbara ...,2019-05-09,"POLYGON ((-8368.416 -370860.259, -8475.394 -37...",2019-05-09,Single Family Residence Multi Story,2019
2,2019-05-07,Compliant,34.676197,-120.089553,3350,Caballo Ln,None,Santa Ynez,Santa Barbara,93460,3350 Caballo Ln Santa Ynez Santa Barbara CA 93...,2019-05-09,"POLYGON ((-8253.618 -371073.707, -8136.129 -37...",2019-05-09,Single Family Residence Multi Story,2019
3,2019-05-07,Compliant,34.677982,-120.088944,3350,Caballo Ln,None,Santa Ynez,Santa Barbara,93460,3350 Caballo Ln Santa Ynez Santa Barbara CA 93...,2019-05-09,"POLYGON ((-8201.866 -370989.432, -8201.866 -37...",2019-05-09,Utility or Miscellaneous Structure > 120 sqft,2019
4,2019-05-07,Compliant,34.678469,-120.087539,3320 A,Canada Este Rd,None,Santa Ynez,Santa Barbara,93460,3320 A Canada Este Rd Santa Ynez Santa Barbara...,2019-12-17,"POLYGON ((-7966.144 -370818.558, -7966.144 -37...",2019-12-17,Single Family Residence Multi Story,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89352,2023-08-24,Non-Compliant,34.944801,-119.681560,71,Newsome St,None,New Cuyama,Santa Barbara County,93254,71 Newsome St New Cuyama Santa Barbara County ...,2023-08-14,"POLYGON ((29027.935 -341229.025, 29105.749 -34...",2023-08-14,Infrastructure (Essential Services),2023
89353,2023-08-23,Compliant,34.975333,-119.895858,2875,Cottonwood Canyon Rd,None,New Cuyama,Santa Barbara County,93454,2875 Cottonwood Canyon Rd New Cuyama Santa Bar...,2023-08-23,"POLYGON ((9463.523 -337882.689, 9541.337 -3378...",2023-08-23,Single Family Residence Single Story,2023
89354,2023-09-26,Compliant,34.458542,-119.814448,1118,N Patterson Ave,None,Santa Barbara,Santa Barbara County,93111,1118 N Patterson Ave Santa Barbara Santa Barba...,2023-09-26,"POLYGON ((17054.544 -395291.334, 17052.114 -39...",2023-09-26,Single Family Residence Single Story,2023
89355,2023-09-26,Compliant,34.458542,-119.814448,1118,N Patterson Ave,None,Santa Barbara,Santa Barbara County,93111,1118 N Patterson Ave Santa Barbara Santa Barba...,2023-09-26,"POLYGON ((17081.932 -395302.172, 17079.044 -39...",2023-09-26,Single Family Residence Single Story,2023
89356,2023-11-06,Compliant,34.870960,-120.382833,2114,Fallen Leaf Drive,None,Santa Maria,Santa Barbara,93455,2114 Fallen Leaf Drive Santa Maria Santa Barba...,2023-10-31,"POLYGON ((-34938.315 -349478.543, -34991.669 -...",2023-10-31,Single Family Residence Multi Story,2023

In [104]:
# adding address_id to be unique for every unique inspection
all_inspections["address_id"] = np.arange(1, len(all_inspections) + 1)

In [105]:
# Fixing CRS to 3310, Albers

all_inspections = all_inspections.to_crs(epsg=3310)

print(all_inspections.crs)

EPSG:3310

In [120]:
all_inspections.to_file(
    "/capstone/wildfire_prep/data/MASTER_DATAFRAME/inspections_master.geojson",
    driver="GeoJSON",
)

all_inspections.to_file(
    "/capstone/wildfire_prep/data/MASTER_DATAFRAME/inspections_master_copy.geojson",
    driver="GeoJSON",
)

BREAKPOINT

In [107]:
# Import parcel data

# parcels = os.path.join(config.data_dir, "parcel_boundaries", "cbiinputs.gdb")
# parcels = gpd.read_file(parcels).to_crs(config.albers_crs)

In [108]:
# Checking parcel column names, and narrowing down the dataframe to only necessary columns

# print(parcels.columns.tolist())

# parcels_copy = parcels.copy()

# parcel_columns = ['situs1', 'shape_leng', 'shape_Length', 'shape_Area', 'geometry']
# parcels_copy = parcels[parcel_columns]

In [109]:
# Joining parcels to inspections dataframe 

# inspections_parcels = gpd.sjoin(
#         parcels_copy, all_inspections_copy, how="inner", predicate="contains")

In [110]:
# inspections_parcels.drop("index_right", axis=1, inplace=True)

In [111]:
# buffered_buildings = read_geojson_with_geopandas('/capstone/wildfire_prep/data/joined_inspections_parcels/buffered_buildings_2022.geojson')

In [112]:
# buffered_buildings_copy = buffered_buildings.copy()

# print(buffered_buildings.columns.tolist())

# buff_buildings_columns = ['geometry']

# buffered_buildings_copy = buffered_buildings_copy[buff_buildings_columns]

In [113]:
# inspections_buffbuildings = gpd.sjoin(
#         buffered_buildings_copy, all_inspections_copy, how="inner", predicate="contains")

In [114]:
# inspections_buffbuildings.drop("index_right", axis=1, inplace=True)

/capstone/wildfire_prep/data/inspections_data/cleaned_status_with_id

In [115]:
# inspections_buffbuildings.to_file(
#     "/capstone/wildfire_prep/data/inspections_data/cleaned_status_with_id/inspections_buffered_buildings.geojson",
#     driver="GeoJSON",
# )

# inspections_parcels.to_file(
#     "/capstone/wildfire_prep/data/inspections_data/cleaned_status_with_id/inspections_parcels.geojson",
#     driver="GeoJSON",
# )

In [116]:
# making a dataframe with ALL columns from the inspection data. This cannot include 2023 data, as the column names had changed.

# inspections_no_2023 = pd.concat(
#     [insp_19, insp_20, insp_21, insp_22],
#     axis=0,
#     ignore_index=True,
# )

# inspections_no_2023 = inspections_no_2023.to_crs(epsg=3310)

# inspections_no_2023.head()

In [118]:
# inspections_no_2023 = gpd.sjoin(
#     buffered_buildings_copy, inspections_no_2023, how="inner", predicate="contains"
# )

# inspections_no_2023.shape

In [119]:
# inspections_no_2023.to_file(
#     "/capstone/wildfire_prep/data/inspections_data/cleaned_status_with_id/inspections_buffbuild_no_2023.geojson",
#     driver="GeoJSON",
# )