In [1]:
import os
import sys
import numpy as np 
import pandas as pd
import geopandas as gpd

sys.path.append("../utils")

import config

pd.set_option("display.max_columns", None)

In [2]:
def read_geojson_with_geopandas(file_path):
        gdf = gpd.read_file(file_path)
        return gdf

insp_19 = read_geojson_with_geopandas("/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2019.geojson")
insp_20 = read_geojson_with_geopandas("/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2020.geojson")
insp_21 = read_geojson_with_geopandas("/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2021.geojson")
insp_22 = read_geojson_with_geopandas("/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2022.geojson")
insp_23 = read_geojson_with_geopandas("/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2023.geojson")

In [3]:
insp_19[insp_19["status"] == "Non-Compliant"]
#insp_19[insp_19["inspection"] == "None"]

,fulcrum_id,created_at,updated_at,system_cre,system_upd,version,status,project,assigned_t,latitude,longitude,report_tit,globalid,calculated,inspectorp,inspection,addressvis,address_su,address_th,address__1,address_lo,address__2,address_ad,address_po,address_co,address_fu,calfireuni,county,community,community_,battalion,enginenumb,stationnam,stationn_1,shift,occupantho,deliveryno,inspecti_1,a_removebr,b_removele,c_removede,d_removede,e_removedy,f_removefl,g_relocate,h_cutannua,i_reducefu,j_allexpos,k_deaddyin,l_logsstum,m_outbuild,n_addressd,o_chimneys,recommend_,propanetan,accessegre,waterstora,water_sour,can_engine,water_stor,water_comm,structuret,roofconstr,eaves,ventscreen,exteriorsi,windowpane,deckporchg,deckporche,patiocover,fenceattac,utilitymis,utilitym_1,nonhabitab,escalateto,reinspecti,clearreins,citationnu,citationda,deadtrees3,photoid,photoid_ca,le100numbe,inspecti_2,coredatafl,partner_di,principal_,firescopei,responsibi,apn,yearbuilt,siteaddres,numberofst,appenddate,editstatus,createddat,createdby,editeddate,editedby,textfield1,textfield2,numberfiel,numberfi_1,core_with_,Date,geometry
7,d75d672f-cdba-4aa2-a4bc-b72e2aaf5b81,2018-05-25 16:25:12,2019-12-20 11:37:23,2019-05-07 11:52:39,2019-12-20 11:37:23,5.0,Non-Compliant,None,None,34.683028,-120.087480,Defensible Space Inspection Report,None,None,DSI,2019-12-11,Yes - With Reflective,3515,W Oak Trail Rd,None,Santa Ynez,Santa Barbara,CA,93460,US,3515 W Oak Trail Rd Santa Ynez Santa Barbara C...,SBC,SBA,Woodstock,None,2,32,32,None,None,No,Hardcopy,5 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Unable to Assess,yes,yes,Pool,None,None,None,Single Family Residence Single Story,Metal,Enclosed,No Vents,Other,Single Pane,No Deck/Porch,No Deck/Porch,No Patio Cover/Carport,No Fence,None,0,0,Yes - Locked Gate,NaT,None,None,None,0,a38a15cc-41aa-48e3-91cb-3ce368640133,None,0.0,0.0,None,None,None,None,None,None,2002.0,None,0.0,2019-05-16,None,None,None,None,None,None,None,0.0,0.0,None,2019-12-11,POINT (-120.08748 34.68303)
79,6c5977d8-862a-44de-b48b-1cba952996c0,2018-05-25 16:25:26,2019-12-20 11:38:02,2019-05-07 11:53:05,2019-12-20 11:38:03,5.0,Non-Compliant,None,None,34.670765,-120.083017,Defensible Space Inspection Report,None,None,DSI,2019-12-11,Yes - With Reflective,3115,Box Canyon Rd,None,Santa Ynez,Santa Barbara,CA,93460,US,3115 Box Canyon Rd Santa Ynez Santa Barbara CA...,SBC,SBA,Woodstock,None,2,32,Santa Ynez Valley (Outside Engine Co. Area),None,A,No,Email,5 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Unable to Assess,Unable to Assess,None,None,None,None,None,Unable to Assess,Unable to Assess,Unable to Assess,Unable to Assess,Unable to Assess,Unable to Assess,Unable to Assess,Unable to Assess,Unable to Assess,Unable to Assess,None,0,0,Yes - Locked Gate,NaT,None,None,None,0,a758dd40-bcd5-4b67-badf-f25f0e8a6caf,None,0.0,0.0,None,None,None,None,None,None,0.0,None,0.0,2019-05-22,None,None,None,None,None,None,None,0.0,0.0,None,2019-12-11,POINT (-120.08302 34.67076)
81,15066ff1-6927-4e40-a125-ad27fed6736d,2018-05-25 16:25:26,2019-12-20 11:34:07,2019-05-07 11:53:05,2019-12-20 11:34:08,6.0,Non-Compliant,None,None,34.666110,-120.082647,Defensible Space Inspection Report,None,None,DSI,2019-12-12,Yes - Without Reflective,2915,Woodstock Rd,None,Santa Ynez,Santa Barbara,CA,93460,US,2915 Woodstock Rd Santa Ynez Santa Barbara CA ...,SBC,SBA,Woodstock,None,2,32,Santa Ynez Valley (Outside Engine Co. Area),None,A,No,Hardcopy,5 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Not Applicable,yes,yes,"Hydrant- Municipal/Public Water Supply,Pool",yes,None,None,Unable to Assess,Unable to Assess,Unable to Assess,Unable to Assess,Unable to Assess,Unable to Assess,Unable to Assess,Unable to Assess,Unable to Assess,Unable to Assess,None,0,0,None,NaT,None,None,None,None,8035a9cf-aaea-4db2-83c5-34865a09120c,None,0.0,0.0,None,None,None,None,None,None,1981.0,None,0.0,2019-06-12,None,None,None,None,None,None,None,0.0,0.0,None,2019-12-12,POINT (-120.08265 34.66611)
82,af84038b-8483-4234-9482-2babfb26fd78,2018-05-25 16:25:26,2019-12-20 11:34:12,2019-05-07 11:53:05,2019-12-20 11:34:12,5.0,Non-Compliant,None,None,34.664804,-120.083184,Defensible Space Inspection Report,None,None,DSI,2019-12-12,Yes - Without Reflective,2875,Woodstock Rd,None,Santa Ynez,Santa Barbara,CA,93460,US,2875 Woodstock Rd Santa Ynez Santa Barbara CA ...,SBC,SBA,Woodstock,None,2,32,Santa Ynez Valley (Outside Engine Co. Area),None,A,No,Hardcopy,5 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Not Applicable,yes,yes,Pool,yes,None,None,Unable to Assess,Unable to Assess,Unable to Assess,Unable to Assess,Unable to Assess,Unable to Assess,Unable to Assess,Unable to Assess,Unable to Assess,Unable to Assess,None,0,0,Yes - Locked Gate,NaT,None,None,None,None,03a2066f-b3e4-4a41-a6f1-9627aa1cfa50,None,0.0,0.0,None,None,None,None,None,None,1981.0,None,0.0,2019-06-12,None,None,None,None,None,None,None,0.0,0.0,None,2019-12-12,POINT (-120.08318 34.6648)
98,1ba7b20a-19fb-4a4e-ab28-54ccb0c86041,2018-05-25 16:25:29,2019-12-20 11:35:30,2019-05-07 11:53:11,2019-12-20 11:35:30,6.0,Non-Compliant,None,None,34.668338,-120.069167,Defensible Space Inspection Report,None,None,DSI,2019-12-11,Yes - Without Reflective,3055,Long Canyon Rd,None,Santa Ynez,Santa Barbara,CA,93460,US,3055 Long Canyon Rd Santa Ynez Santa Barbara C...,SBC,SBA,Woodstock,None,2,32,32,None,None,No,Hardcopy,5 min,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Not Applicable,yes,None,None,None,None,None,Single Family Residence Multi Story,Asphalt,Enclosed,No Vents,Wood,Multi Pane,No Deck/Porch,No Deck/Porch,No Patio Cover/Carport,No Fence,None,0,1,Yes - Locked Gate,NaT,None,None,None,None,5c4375b4-eaff-46c1-a19f-0d2891974e14,None,0.0,0.0,None,None,None,None,None,None,0.0,None,0.0,2019-06-19,None,None,None,None,None,None,None,0.0,0.0,None,2019-12-11,POINT (-120.06917 34.66834)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14668,None,NaT,NaT,NaT,NaT,0.0,Non-Compliant,None,None,34.450607,-119.641651,None,None,None,Prevention,None,None,None,None,None,None,None,None,None,None,936 Hot Springs Ln Santa Barbara CA 93108 US,SBC,SBA,Montecito,None,1,None,MTO,None,None,None,None,None,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaT,None,None,None,None,None,None,0.0,0.0,None,None,None,None,None,None,0.0,None,0.0,NaT,None,None,None,None,None,None,None,0.0,0.0,None,2019-08-01,POINT (-119.64165 34.45061)
14669,None,NaT,NaT,NaT,NaT,0.0,Non-Compliant,None,None,34.442984,-119.641537,None,None,None,Prevention,None,None,None,None,None,None,None,None,None,None,670 Hot Springs Rd Santa Barbara CA 93108 US,SBC,SBA,Montecito,None,1,None,MTO,None,None,None,None,None,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaT,None,None,None,None,None,None,0.0,0.0,None,None,None,None,None,None,0.0,None,0.0,NaT,None,None,None,None,None,None,None,0.0,0.0,None,2019-08-01,POINT (-119.64154 34.44298)
14670,None,NaT,NaT,NaT,NaT,0.0,Non-Compliant,None,None,34.441790,-119.640843,None,None,None,Prevention,None,None,None,None,None,None,None,None,None,None,660 Hot Springs Rd Santa Barbara CA 93108 US,SBC,SBA,Montecito,None,1,None,MTO,None,None,None,None,None,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaT,None,None,None,None,None,None,0.0,0.0,None,None,None,None,None,None,0.0,None,0.0,NaT,None,None,None,None,None,None,None,0.0,0.0,None,2019-08-01,POINT (-119.64084 34.44179)
14671,None,NaT,NaT,NaT,NaT,0.0,Non-Compliant,None,None,34.440635,-119.641100,None,None,None,Prevention,None,None,None,None,None,None,None,None,None,None,630 Hot Springs Rd Santa Barbara CA 93108 US,SBC,SBA,Montecito,None,1,None,MTO,None,None,None,None,None,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaT,None,None,None,None,None,None,0.0,0.0,None,None,None,None,None,None,0.0,None,0.0,NaT,None,None,None,None,None,None,None,0.0,0.0,None,2019-08-01,POINT (-119.6411 34.44063)
14672,None,NaT,NaT,NaT,NaT,0.0,Non-Compliant,None,None,34.444095,-119.637895,None,None,None,Engine,7/6/2019,None,None,None,None,None,None,None,None,None,767 Picacho Ln Santa Barbara CA 93108 US,SBC,SBA,Montecito,None,1,None,MTO,None,None,None,None,None,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,Compliant,No,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaT,None,None,None,None,None,None,0.0,0.0,None,None,None,None,None,None,0.0,None,0.0,NaT,None,None,None,None,None,None,None,0.0,0.0,None,2019-07-06,POINT (-119.6379 34.4441)

ADD, in order:
19: 
inspection
structuret

23: 
inspectiondate_calculate
structuretype

In [4]:
insp_23[insp_23["status"] == "Non-Compliant"]

,fulcrum_id,created_at,updated_at,created_by,updated_by,system_created_at,system_updated_at,version,status,project,assigned_to,latitude,longitude,report_title,globalid,keyid,propertystatus,inspectionstatus,inspectorfirstname,inspectorlastname,prevention_inspectorfirstname,prevention_inspectorfirstname_other,prevention_inspectorlastname,prevention_inspectorlastname_other,inspectorposition,inspectiondate_calculate,addressvisible,address_sub_thoroughfare,address_thoroughfare,address_suite,address_locality,address_sub_admin_area,address_admin_area,address_postal_code,address_country,address_full,calfireunit,county,community,community_other,battalion,enginenumber,stationname,shift,shift_julian,accessegress,occupanthome,deliverynotificationmethod,inspectionhours,a_removebranchesfromstovepipe,b_removeleavesneedlesveg,c_removedeaddyingtrees,d_removedeaddyinggrassplants,e_removeflammablegroundcover,f_removeflammablevegetation,g_relocateexposedwoodpiles,h_cutannualgrassesforbs,i_removefuelsusingctguidelines,j_exposedwoodpiles,k_removedeaddyingwoodyfuels,l_removelogstumpsembeddedsoil,m_outbuildingsliquidpropanegas,n_displayaddresscontrasting,o_stovepipemetalscreenopenings,recommendclearvegetation,waterstora,water_source,can_engine_access_water_source,water_storage_size_stored_water_on_individual_parcels_only,water_comments,structuretype,structurehabitable,roofconstruction,eaves,ventscreen,exteriorsiding,windowpane,deckporchgrade,deckporchelevated,patiocovercarport,fenceattachedtostructure,propanetankdistance,utilitymiscstructuredistance,utilitymiscstucturecount,nonhabitableoutbuildings,escalatetocoordinator,reinspectiondate,citationnumber,number_of_dead_trees_within_300_ft_of_residence,gatecode,comments,photoid,photoid_caption,photoid_url,le100number,inspectioncount,coredata,firescopeid,apn,yearbuilt,siteaddress,numberofstructures,appenddate,editstatus,calculatedglobalid,calculateddate,calculateduid,textfield1,textfield2,numberfield1,numberfield2,previousyrinspecteddata,previousyrinspectionstatus,calculatededitor,calculatededitdate,creationdate,editdate,creator,editor,Date,geometry
53,cb6c5509-0cf2-4c52-af41-93548c835f79,2022-04-04 17:00:00,2023-06-13 17:00:00,gis@sbcfire.com,gis@sbcfire.com,2022-04-05 13:47:20,2023-07-13 08:12:55,7,Non-Compliant,None,None,34.868556,-119.511721,Defensible Space Inspection Report,None,0.0,None,None,Clint,Reif,None,None,None,None,Engine,2023-06-14,No - Not Visible,2400,Santa Barbara Canyon Rd,None,Maricopa,Santa Barbara,CA,93252,US,2400 Santa Barbara Canyon Rd Maricopa Santa Ba...,SBC,SBA,Ventucopa,None,2,27.0,27,A,165,Yes,No,Email,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,no,None,None,None,None,Single Family Residence Single Story,Habitable,Asphalt,Unenclosed,No Vents,Wood,Single Pane,No Deck/Porch,No Deck/Porch,Combustible,No Fence,Not Applicable,<30',1,1,None,NaT,None,0,None,None,a78234d7-8adc-498e-89a7-5e7027f543ba,,https://web.fulcrumapp.com/photos/view?photos=...,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-07-05,2020-06-20,None,None,2023-06-14,POINT (-119.51172 34.86856)
73,934a3ea8-0033-47d8-b770-8d29b06d23e6,2022-04-04 17:00:00,2023-10-26 14:55:14,gis@sbcfire.com,burnpermits@sbcfire.tech,2022-04-05 13:47:24,2023-10-26 14:55:29,6,Non-Compliant,None,None,34.694485,-120.387892,Defensible Space Inspection Report,None,0.0,None,None,None,Steiner,None,None,None,None,Engine,2022-08-21,Yes - With Reflective,3300,Catalina Rd,None,Lompoc,Santa Barbara,CA,93436,US,3300 Catalina Rd Lompoc Santa Barbara CA 93436 US,SBC,SBA,Cebada Canyon,None,3,0.0,34,B,299,No,No,Hardcopy,15,None,None,None,violation,violation,None,None,violation,None,None,None,None,violation,None,None,Yes,yes,Tank,yes,Over 5000 gallons,None,Single Family Residence Single Story,Habitable,Tile,Unenclosed,No Vents,Stucco/Brick/Cement,Single Pane,Masonry/Concrete,No Deck/Porch,Combustible,No Fence,>30',None,0,0,None,NaT,None,0,None,6/9/2021 - notice to schedule inspection left ...,None,None,None,None,None,None,None,None,2009.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-08-21,2020-06-15,None,None,2022-08-21,POINT (-120.38789 34.69449)
251,a85e65ea-3bed-4a4c-88c0-e53a843ee801,2022-04-04 17:00:00,2023-09-02 13:37:34,gis@sbcfire.com,burnpermits@sbcfire.tech,2022-04-05 13:48:00,2023-09-02 13:37:36,8,Non-Compliant,None,None,34.628065,-120.285815,Defensible Space Inspection Report,None,0.0,None,None,Dan,Rasper,None,None,None,None,Engine,2023-09-02,Yes - Without Reflective,7261,Domingos Rd,None,Lompoc,Santa Barbara,CA,93436,US,7261 Domingos Rd Lompoc Santa Barbara CA 93436 US,SBC,SBA,Lompoc Valley,None,3,31.0,31,C,245,Yes,No,Email,15,None,None,violation,violation,None,None,None,violation,violation,None,None,None,None,None,None,Yes,yes,"Tank,Private Hydrant- Private Stored Water",yes,None,None,Utility or Miscellaneous Structure > 120 sqft,Habitable,Metal,Unenclosed,No Vents,Wood,Single Pane,No Deck/Porch,No Deck/Porch,No Patio Cover/Carport,No Fence,Not Applicable,>50',10,0,None,NaT,None,0,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-06-27,2020-06-30,None,None,2023-09-02,POINT (-120.28582 34.62807)
726,ad4a7f44-cd86-4f7c-aa5d-47035ee388a4,2022-04-04 17:00:00,2023-10-11 10:39:57,gis@sbcfire.com,sbc.dsp.inspector@sbcfire.com,2022-04-05 13:49:33,2023-10-11 10:40:54,5,Non-Compliant,None,None,34.609466,-120.133646,Defensible Space Inspection Report,None,0.0,None,None,None,None,Charlotte,None,Endicott,None,DSI,2023-10-11,Yes - Without Reflective,970,College Canyon Rd,None,Solvang,Santa Barbara,CA,93463,US,970 College Canyon Rd Solvang Santa Barbara CA...,SBC,SBA,Solvang,None,3,30.0,30,C,284,Yes,No,Hardcopy,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,yes,Hydrant- Municipal/Public Water Supply,yes,None,None,Single Family Residence Single Story,Habitable,Asphalt,Unenclosed,"Mesh Screen > 1/8""",Wood,Single Pane,Wood,No Deck/Porch,Combustible,No Fence,Not Applicable,>50',1,0,None,NaT,None,0,None,None,None,None,None,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-10-06,2020-08-27,None,None,2023-10-11,POINT (-120.13365 34.60947)
871,706124cc-e588-44fb-8d0b-8d34d5a87648,2022-04-04 17:00:00,2023-06-20 17:00:00,gis@sbcfire.com,gis@sbcfire.com,2022-04-05 13:50:10,2023-07-13 08:15:29,5,Non-Compliant,None,None,34.913661,-120.196086,Defensible Space Inspection Report,None,0.0,None,None,Larry,Terrones,None,None,None,None,Engine,2023-06-21,No - Not Visible,3668,Tepusquet Rd,None,Santa Maria,Santa Barbara,CA,93454,US,3668 Tepusquet Rd Santa Maria Santa Barbara CA...,SBC,SBA,Tepusquet,None,2,0.0,23,B,172,No,No,Hardcopy,15,None,violation,violation,violation,None,violation,None,violation,None,None,None,None,None,None,None,Yes,yes,Tank,yes,None,None,Commercial Building Single Story,Habitable,Wood,Unenclosed,"Mesh Screen <= 1/8""",Other,Single Pane,No Deck/Porch,Wood,No Patio Cover/Carport,No Fence,Not Applicable,None,6,0,None,NaT,None,0,None,None,"121d029a-5802-43f1-9412-66b949fd111e,218a2321-...",",",https://web.fulcrumapp.com/photos/view?photos=...,None,None,None,None,None,0.0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2022-10-22,2020-11-03,None,None,2023-06-21,POINT (-120.19609 34.91366)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13349,2d3befae-3b7c-465f-8643-217c0d781ef8,2023-07-13 08:24:06,2023-09-27 11:19:35,firedg21@sbcfire.com,sbc.dsp.inspector@sbcfire.com,2023-07-13 08:44:38,2023-09-27 13:33:14,12,Non-Compliant,None,None,34.862257,-120.442771,Defensible Space Inspection Report,None,NaN,None,None,None,Taylor,Tim,None,Gailey,None,Engine,2023-08-06,Yes - Without Reflective,451,Soares Ave,None,Santa Maria,Santa Barbara County,CA,93455,US,451 Soares Ave Santa Maria Santa Barbara Count...,SBC,SBA,Orcutt,None,2,NaN,21,B,270,Yes,No,Hardcopy,15,Violation,violation,violation,violation,violation,violation,None,violation,violation,None,violation,None,None,None,None,No,yes,None,yes,None,None,Single Family Residence Single Story,Habitable,Asphalt,Unenclosed,Not Observed,Wood,Not Observed,Not Observed,Not Observed,Combustible,Combustible,Not Observed,30-50',None,None,Yes - Other (explain in the Comments),NaT,None,0,None,Fire hazard complaint for unoccupied home in L...,"cb49a3b7-7b83-409b-94e3-6dd505c29391,d2e8899d-...",",,,",https://web.fulcrumapp.com/photos/view?photos=...,None,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2023-07-13,2023-07-13,None,None,2023-08-06,POINT (-120.44277 34.86226)
13356,c1eaacd2-8345-40de-ba23-8ac9d38d5154,2023-08-14 13:42:52,2023-08-24 08:24:12,burnpermits@sbcfire.tech,burnpermits@sbcfire.tech,2023-08-14 13:57:06,2023-08-24 08:24:21,4,Non-Compliant,None,None,34.944801,-119.681560,Defensible Space Inspection Report,None,NaN,None,None,Clint,Reif,None,None,None,None,Engine,2023-08-14,No - Not Visible,71,Newsome St,None,New Cuyama,Santa Barbara County,CA,93254,US,71 Newsome St New Cuyama Santa Barbara County ...,SBC,SBA,Cuyama,None,2,NaN,27,C,236,Yes,No,Email,15,None,None,None,None,None,None,None,violation,None,None,None,None,None,None,None,None,None,None,None,None,None,Infrastructure (Essential Services),Habitable,Other,No Eaves,"Mesh Screen <= 1/8""",Other,No Windows,No Deck/Porch,No Deck/Porch,No Patio Cover/Carport,No Fence,Not Applicable,None,None,None,None,NaT,None,0,None,Please mow Annual grasses @ 71 Newsome Street....,"829c4838-e03e-47e6-88a0-85c9b4dcfa0f,588d2bbb-...",",,,",https://web.fulcrumapp.com/photos/view?photos=...,None,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2023-08-14,2023-08-14,None,None,2023-08-14,POINT (-119.68156 34.9448)
13361,85262fcb-42d3-4b21-829e-d90f1ca8c426,2023-09-27 11:03:52,2023-09-29 08:26:36,sbc.dsp.inspector@sbcfire.com,sbc.dsp.inspector@sbcfire.com,2023-09-27 11:10:51,2023-09-29 08:27:31,3,Non-Compliant,None,None,34.934430,-119.611427,Defensible Space Inspection Report,None,NaN,None,None,None,None,Tim,None,Gailey,None,Engine,2023-08-21,No - Not Visible,3134,Wylie St,None,Cuyama,Santa Barbara County,CA,93254,US,3134 Wylie St Cuyama Santa Barbara County CA 9...,SBC,SBA,Cuyama,None,2,NaN,27,C,271,Yes,No,Hardcopy,15,None,violation,violation,violation,violation,violation,None,violation,violation,violation,violation,None,violation,violation,None,Yes,no,None,None,None,None,Single Family Residence Single Story,Habitable,Wood,Unenclosed,"Mesh Screen <= 1/8""",Wood,Single Pane,Not Observed,Not Observed,No Patio Cover/Carport,Not Observed,Not Observed,None,None,None,None,NaT,None,0,None,Left Dsp notice and is abandoned. 3 inspectio...,"498c616f-23c5-4eea-b6dc-fccbd790a0fa,36fd8989-...",",",https://web.fulcrumapp.com/photos/view?photos=...,None,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2023-09-27,2023-09-27,None,None,2023-08-21,POINT (-119.61143 34.93443)
13362,246672f2-03f3-4df6-9fed-56b15b9c5344,2023-09-27 11:00:14,2023-09-28 13:12:29,sbc.dsp.inspector@sbcfire.com,sbc.dsp.inspector@sbcfire.com,2023-09-27 11:10:55,2023-09-29 08:27:28,2,Non-Compliant,None,None,34.934445,-119.611164,Defensible Space Inspection Report,None,NaN,None,None,None,None,Tim,None,Gailey,None,Engine,2023-08-21,No - Not Visible,3132,Wylie St,None,Cuyama,Santa Barbara County,CA,93254,US,3132 Wylie St Cuyama Santa Barbara County CA 9...,SBC,SBA,Cuyama,None,2,NaN,27,C,271,Yes,No,Hardcopy,15,Violation,violation,violation,violation,violation,violation,violation,violation,violation,violation,violation,violation,violation,violation,None,Yes,no,None,None,None,None,Single Family Residence Single Story,Habitable,Wood,Unenclosed,"Mesh Screen <= 1/8""",Wood,Single Pane,Not Observed,Not Observed,No Patio Cover/Carport,Not Observed,Not Observed,None,None,None,None,NaT,None,0,None,Left DSP flyer - appears abandoned and have no...,"aefd4c13-e6f6-4f49-b987-f4ba2b166d85,924288d7-...",",,,",https://web.fulcrumapp.com/photos/view?photos=...,None,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2023-09-27,2023-09-27,None,None,2023-08-21,POINT (-119.61116 34.93444)
13364,6f934f62-086e-4f6c-a55e-e9b217f4f20c,2023-10-12 14:00:01,2023-10-12 14:01:42,sbc.dsp.inspector@sbcfire.com,sbc.dsp.inspector@sbcfire.com,2023-10-12 14:03:43,2023-10-12 14:03:43,1,Non-Compliant,None,None,34.616152,-120.354778,Defensible Space Inspection Report,None,NaN,None,None,None,None,None,None,Gailey,None,Prevention,2023-10-12,No - Not Visible,None,Sweeney Rd,None,Lompoc,Santa Barbara County,CA,93436,US,Sweeney Rd Lompoc Santa Barbara County CA 9343...,SBC,SBA,Lompoc Valley,None,2,NaN,34,A,285,Yes,No,Email,15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,no,None,None,None,None,Single Family Residence Single Story,Habitable,Asphalt,Not Observed,"Mesh Screen <= 1/8""",Stucco/Brick/Cement,Not Observed,Not Observed,Not Observed,Combustible,No Fence,Not Observed,None,None,None,None,NaT,None,0,None,None,fcaeaa9b-cbd5-454c-bdd0-aa2f1bf2192d,,https://web.fulcrumapp.com/photos/view?photos=...,None,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2023-10-12,2023-10-12,None,None,2023-10-12,POINT (-120.35478 34.61615)

In [5]:
# Select only necessary columns. Columns in 2023 dataframe are different, but will be renamed in a later chunk

needed_columns = [
    "system_cre",
    "status",
    "latitude",
    "longitude",
    "address_su",
    "address_th",
    "address__1",
    "address_lo",
    "address__2",
    "address_ad",
    "address_po",
    "address_co",
    "address_fu",
    "Date",
    "geometry",
    "inspection",
    "structuret"
]
needed_columns_23 = [
    "updated_at",
    "status",
    "latitude",
    "longitude",
    "address_sub_thoroughfare",
    "address_thoroughfare",
    "address_suite",
    "address_locality",
    "address_sub_admin_area",
    "address_admin_area",
    "address_postal_code",
    "address_country",
    "address_full",
    "Date",
    "geometry",
    "inspectiondate_calculate",
    "structuretype"
]

In [6]:
# Narrow down all inspections dataframes to the necessary columns defined above

insp_19_clean = insp_19[needed_columns]
insp_20_clean = insp_20[needed_columns]
insp_21_clean = insp_21[needed_columns]
insp_22_clean = insp_22[needed_columns]
insp_23_clean = insp_23[needed_columns_23]

In [7]:
# Rename 2023 dataframe columns to match the others

colnames_23 = [
    "system_cre",
    "status",
    "latitude",
    "longitude",
    "address_su",
    "address_th",
    "address__1",
    "address_lo",
    "address__2",
    "address_ad",
    "address_po",
    "address_co",
    "address_fu",
    "Date",
    "geometry",
    "inspection",
    "structuret"
]

insp_23_clean.columns = colnames_23

# verify column names change
print(insp_23_clean.columns.tolist())

['system_cre', 'status', 'latitude', 'longitude', 'address_su', 'address_th', 'address__1', 'address_lo', 'address__2', 'address_ad', 'address_po', 'address_co', 'address_fu', 'Date', 'geometry', 'inspection', 'structuret']

In [8]:
# Making copies

insp_19_clean = insp_19_clean.copy()
insp_20_clean = insp_20_clean.copy()
insp_21_clean = insp_21_clean.copy()
insp_22_clean = insp_22_clean.copy()
insp_23_clean = insp_23_clean.copy()

# Adding inspection year column

insp_19_clean['year'] = 2019
insp_20_clean['year'] = 2020
insp_21_clean['year'] = 2021
insp_22_clean['year'] = 2022
insp_23_clean['year'] = 2023

In [9]:
# Joining all inspections dataframes

all_inspections = pd.concat([insp_19_clean, insp_20_clean, insp_21_clean, insp_22_clean, insp_23_clean], axis=0, ignore_index=True)

codes, uniques = pd.factorize(all_inspections['address_fu'])
all_inspections['address_id'] = codes + 1

In [10]:
all_inspections

,system_cre,status,latitude,longitude,address_su,address_th,address__1,address_lo,address__2,address_ad,address_po,address_co,address_fu,Date,geometry,inspection,structuret,year,address_id
0,2019-05-07 11:52:36,Compliant,34.669616,-120.031160,3462,Brinkerhoff Rd,None,Santa Ynez,Santa Barbara,CA,93460,US,3462 Brinkerhoff Rd Santa Ynez Santa Barbara C...,2019-06-05,POINT (-120.03116 34.66962),2019-06-05,Utility or Miscellaneous Structure > 120 sqft,2019,1
1,2019-05-07 11:52:37,Compliant,34.679129,-120.091914,3290,Avenida Caballo,None,Santa Ynez,Santa Barbara,CA,93460,US,3290 Avenida Caballo Santa Ynez Santa Barbara ...,2019-05-09,POINT (-120.09191 34.67913),2019-05-09,Single Family Residence Multi Story,2019,2
2,2019-05-07 11:52:37,Compliant,34.676197,-120.089553,3350,Caballo Ln,None,Santa Ynez,Santa Barbara,CA,93460,US,3350 Caballo Ln Santa Ynez Santa Barbara CA 93...,2019-05-09,POINT (-120.08955 34.6762),2019-05-09,Single Family Residence Multi Story,2019,3
3,2019-05-07 11:52:38,Compliant,34.677982,-120.088944,3350,Caballo Ln,None,Santa Ynez,Santa Barbara,CA,93460,US,3350 Caballo Ln Santa Ynez Santa Barbara CA 93...,2019-05-09,POINT (-120.08894 34.67798),2019-05-09,Utility or Miscellaneous Structure > 120 sqft,2019,3
4,2019-05-07 11:52:38,Compliant,34.678469,-120.087539,3320 A,Canada Este Rd,None,Santa Ynez,Santa Barbara,CA,93460,US,3320 A Canada Este Rd Santa Ynez Santa Barbara...,2019-12-17,POINT (-120.08754 34.67847),2019-12-17,Single Family Residence Multi Story,2019,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67575,2023-11-06 13:09:08,Compliant,34.870960,-120.382833,2114,Fallen Leaf Drive,None,Santa Maria,Santa Barbara,CA,93455,None,2114 Fallen Leaf Drive Santa Maria Santa Barba...,2023-10-31,POINT (-120.38283 34.87096),2023-10-31 00:00:00,Single Family Residence Multi Story,2023,14762
67576,2023-11-15 14:21:12,Compliant,34.863251,-120.399151,1600,East Clark,Space 158,Orcutt,Santa Barbara,CA,93455,None,1600 East Clark Space 158 Orcutt Santa Barba...,2023-11-15,POINT (-120.39915 34.86325),2023-11-15 00:00:00,None,2023,14763
67577,2023-11-20 10:27:11,Compliant,34.901260,-120.424188,3210,Santa Maria Way,Space 153,Orcutt,Santa Barbara,CA,93455,None,3210 Santa Maria Way Space 153 Orcutt Santa B...,2023-11-15,POINT (-120.42419 34.90126),2023-11-15 00:00:00,Mobile Home Double Wide,2023,14764
67578,2023-11-15 16:18:32,Compliant,34.900785,-120.426280,3210,Santa Maria Way,Space 153,Orcutt,Santa Barbara,CA,93455,None,3210 Santa Maria Way Space 153 Orcutt Santa Ba...,2023-11-15,POINT (-120.42628 34.90078),2023-11-15 00:00:00,Mobile Home Double Wide,2023,14765
67579,2023-12-01 14:01:34,Compliant,34.860787,-120.434805,206,Jullien Drive,None,Santa Maria,Santa Barbara,CA,93455,None,206 Jullien Drive Santa Maria Santa Barbara CA...,2023-12-01,POINT (-120.4348 34.86079),2023-12-01 00:00:00,Single Family Residence Single Story,2023,14766

In [11]:
# rename columns to be more readable

rename_map = {
    "system_cre": "system_created",
    "status": "inspection_status",
    "latitude": "latitude",
    "longitude": "longitude",
    "address_su": "address_number",
    "address_th": "street",
    "address__1": "apt_number",
    "address_lo": "city",
    "address__2": "county",
    "address_ad": "state",
    "address_po": "zip_code",
    "address_co": "country",
    "address_fu": "address_full",
    "Date": "date",
    "geometry": "geometry",
    "inspection": "inspection_date",
    "structuret": "structure_type"
}

all_inspections = all_inspections.rename(columns=rename_map)

In [12]:
# Some dates in the 'inspection' column have the format '2023-08-22 00:00:00'.
# This chunk is to remove the occurrences of '00:00:00' and remove trailing whitespace.

all_inspections["inspection_date"] = (
    all_inspections["inspection_date"]
    .astype(str)
    .str.replace(" 00:00:00", "", regex=False)
    .str.strip()
)

In [13]:
all_inspections

,system_created,inspection_status,latitude,longitude,address_number,street,apt_number,city,county,state,zip_code,country,address_full,date,geometry,inspection_date,structure_type,year,address_id
0,2019-05-07 11:52:36,Compliant,34.669616,-120.031160,3462,Brinkerhoff Rd,None,Santa Ynez,Santa Barbara,CA,93460,US,3462 Brinkerhoff Rd Santa Ynez Santa Barbara C...,2019-06-05,POINT (-120.03116 34.66962),2019-06-05,Utility or Miscellaneous Structure > 120 sqft,2019,1
1,2019-05-07 11:52:37,Compliant,34.679129,-120.091914,3290,Avenida Caballo,None,Santa Ynez,Santa Barbara,CA,93460,US,3290 Avenida Caballo Santa Ynez Santa Barbara ...,2019-05-09,POINT (-120.09191 34.67913),2019-05-09,Single Family Residence Multi Story,2019,2
2,2019-05-07 11:52:37,Compliant,34.676197,-120.089553,3350,Caballo Ln,None,Santa Ynez,Santa Barbara,CA,93460,US,3350 Caballo Ln Santa Ynez Santa Barbara CA 93...,2019-05-09,POINT (-120.08955 34.6762),2019-05-09,Single Family Residence Multi Story,2019,3
3,2019-05-07 11:52:38,Compliant,34.677982,-120.088944,3350,Caballo Ln,None,Santa Ynez,Santa Barbara,CA,93460,US,3350 Caballo Ln Santa Ynez Santa Barbara CA 93...,2019-05-09,POINT (-120.08894 34.67798),2019-05-09,Utility or Miscellaneous Structure > 120 sqft,2019,3
4,2019-05-07 11:52:38,Compliant,34.678469,-120.087539,3320 A,Canada Este Rd,None,Santa Ynez,Santa Barbara,CA,93460,US,3320 A Canada Este Rd Santa Ynez Santa Barbara...,2019-12-17,POINT (-120.08754 34.67847),2019-12-17,Single Family Residence Multi Story,2019,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67575,2023-11-06 13:09:08,Compliant,34.870960,-120.382833,2114,Fallen Leaf Drive,None,Santa Maria,Santa Barbara,CA,93455,None,2114 Fallen Leaf Drive Santa Maria Santa Barba...,2023-10-31,POINT (-120.38283 34.87096),2023-10-31,Single Family Residence Multi Story,2023,14762
67576,2023-11-15 14:21:12,Compliant,34.863251,-120.399151,1600,East Clark,Space 158,Orcutt,Santa Barbara,CA,93455,None,1600 East Clark Space 158 Orcutt Santa Barba...,2023-11-15,POINT (-120.39915 34.86325),2023-11-15,None,2023,14763
67577,2023-11-20 10:27:11,Compliant,34.901260,-120.424188,3210,Santa Maria Way,Space 153,Orcutt,Santa Barbara,CA,93455,None,3210 Santa Maria Way Space 153 Orcutt Santa B...,2023-11-15,POINT (-120.42419 34.90126),2023-11-15,Mobile Home Double Wide,2023,14764
67578,2023-11-15 16:18:32,Compliant,34.900785,-120.426280,3210,Santa Maria Way,Space 153,Orcutt,Santa Barbara,CA,93455,None,3210 Santa Maria Way Space 153 Orcutt Santa Ba...,2023-11-15,POINT (-120.42628 34.90078),2023-11-15,Mobile Home Double Wide,2023,14765
67579,2023-12-01 14:01:34,Compliant,34.860787,-120.434805,206,Jullien Drive,None,Santa Maria,Santa Barbara,CA,93455,None,206 Jullien Drive Santa Maria Santa Barbara CA...,2023-12-01,POINT (-120.4348 34.86079),2023-12-01,Single Family Residence Single Story,2023,14766

In [14]:
# Fixing CRS to 3310, Albers

all_inspections = all_inspections.to_crs(epsg=3310)

print(all_inspections.crs)

# Making a copy

all_inspections_copy = all_inspections.copy()

EPSG:3310

In [15]:
# Import parcel data

parcels = os.path.join(config.data_dir, "parcel_boundaries", "cbiinputs.gdb")
parcels = gpd.read_file(parcels).to_crs(config.albers_crs)

In [16]:
# Checking parcel column names, and narrowing down the dataframe to only necessary columns

print(parcels.columns.tolist())

parcels_copy = parcels.copy()

parcel_columns = ['situs1', 'shape_leng', 'shape_Length', 'shape_Area', 'geometry']
parcels_copy = parcels[parcel_columns]

['apn', 'layer', 'situs1', 'situs2', 'acreage', 'landuse', 'usecode', 'tra', 'docnum', 'docdate', 'pcttransf', 'valreason', 'nontaxcode', 'sbeno', 'agpres', 'landvalue', 'strimpr', 'tradefix', 'livimpr', 'perpropdec', 'perspropun', 'mobilehome', 'exemptions', 'exempcode', 'homeowex', 'netsecval', 'net_impr', 'net_pers', 'net_unx', 'net_av', 'mailx1', 'mailx2', 'mnumber', 'mfrac', 'mdir', 'mstreet', 'mstrsuffix', 'munittype', 'munitnumb', 'pobox', 'mcity', 'mzip', 'mzipext', 'mstate', 'country', 'snum', 'sfra', 'sdir', 'sstreet', 'sstreetsuf', 'sunittype', 'sunitnumb', 'scity', 'szip', 'szipext', 'm_address1', 'm_address2', 'asmrollid', 'apn9', 'propid', 'sqfootage', 'yearbuilt', 'bedrooms', 'bathrooms', 'taxbill', 'permit', 'bkpglnk', 'gen_inquir', 'web_link', 'maptype', 'recmapnum', 'tractname', 'recmapbook', 'recmapdate', 'blocksecti', 'lotnum', 'unitnum', 'cbiinputs_zachary_canter_assess', 'areaunit', 'recdatetim', 'recuserid', 'recuserlog', 'section', 'township', 'range', 'shape_leng', 'shape_Length', 'shape_Area', 'geometry']

In [17]:
# Joining parcels to inspections dataframe 

inspections_parcels = gpd.sjoin(
        parcels_copy, all_inspections_copy, how="inner", predicate="contains")


print(parcels_copy.crs)
print(all_inspections_copy.crs)

EPSG:3310
EPSG:3310

In [18]:
inspections_parcels.drop("index_right", axis=1, inplace=True)
inspections_parcels

,situs1,shape_leng,shape_Length,shape_Area,geometry,system_created,inspection_status,latitude,longitude,address_number,street,apt_number,city,county,state,zip_code,country,address_full,date,inspection_date,structure_type,year,address_id
203,1450 CAMINO MANADERO,903.335649,903.335649,40102.354471,"MULTIPOLYGON (((16347.387 -394504.877, 16342.5...",2020-05-18 16:29:44,Compliant,34.466073,-119.821791,1450,Camino Manadero,None,Santa Barbara,Santa Barbara,CA,93111,US,1450 Camino Manadero Santa Barbara Santa Barba...,2020-06-27,None,Single Family Residence Single Story,2020,1311
203,1450 CAMINO MANADERO,903.335649,903.335649,40102.354471,"MULTIPOLYGON (((16347.387 -394504.877, 16342.5...",2019-05-28 15:21:11,Compliant,34.466073,-119.821791,1450,Camino Manadero,None,Santa Barbara,Santa Barbara,CA,93111,US,1450 Camino Manadero Santa Barbara Santa Barba...,2019-06-25,2019-06-25,Single Family Residence Single Story,2019,1311
203,1450 CAMINO MANADERO,903.335649,903.335649,40102.354471,"MULTIPOLYGON (((16347.387 -394504.877, 16342.5...",2021-04-05 08:56:31,Compliant,34.466073,-119.821791,1450,Camino Manadero,None,Santa Barbara,Santa Barbara,CA,93111,US,1450 Camino Manadero Santa Barbara Santa Barba...,2021-06-26,None,Single Family Residence Single Story,2021,1311
203,1450 CAMINO MANADERO,903.335649,903.335649,40102.354471,"MULTIPOLYGON (((16347.387 -394504.877, 16342.5...",2022-04-06 09:59:33,Compliant,34.466073,-119.821791,1450,Camino Manadero,None,Santa Barbara,Santa Barbara,CA,93111,US,1450 Camino Manadero Santa Barbara Santa Barba...,2022-07-05,None,Single Family Residence Single Story,2022,1311
205,1475 CAMINO MELENO,1113.961402,1113.961402,57984.774296,"MULTIPOLYGON (((16811.85 -394379.557, 16800.14...",2019-05-28 15:21:27,Compliant,34.466445,-119.817230,1475,Camino Meleno,None,Santa Barbara,Santa Barbara,CA,93111,US,1475 Camino Meleno Santa Barbara Santa Barbara...,2019-06-25,2019-06-25,Single Family Residence Single Story,2019,1376
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132303,2685 HWY 33,2962.102000,2962.102000,482989.154940,"MULTIPOLYGON (((46691.776 -350305.727, 46682.3...",2023-08-22 17:28:10,Compliant,34.864993,-119.489451,2685,Highway 33,None,Maricopa,Santa Barbara,CA,93252,US,2685 Highway 33 Maricopa Santa Barbara CA 9325...,2023-08-22,2023-08-22,Single Family Residence Single Story,2023,8981
132303,2685 HWY 33,2962.102000,2962.102000,482989.154940,"MULTIPOLYGON (((46691.776 -350305.727, 46682.3...",2022-04-05 13:47:50,Compliant,34.864993,-119.489451,2685,Highway 33,None,Maricopa,Santa Barbara,CA,93252,US,2685 Highway 33 Maricopa Santa Barbara CA 9325...,2022-06-28,None,Single Family Residence Single Story,2022,8981
132303,2685 HWY 33,2962.102000,2962.102000,482989.154940,"MULTIPOLYGON (((46691.776 -350305.727, 46682.3...",2021-04-05 09:30:25,Compliant,34.864993,-119.489451,2685,Highway 33,None,Maricopa,Santa Barbara,CA,93252,US,2685 Highway 33 Maricopa Santa Barbara CA 9325...,2021-08-17,None,Single Family Residence Single Story,2021,8981
132303,2685 HWY 33,2962.102000,2962.102000,482989.154940,"MULTIPOLYGON (((46691.776 -350305.727, 46682.3...",2019-05-28 16:13:31,Compliant,34.864993,-119.489451,2685,Highway 33,None,Maricopa,Santa Barbara,CA,93252,US,2685 Highway 33 Maricopa Santa Barbara CA 9325...,2019-06-11,2019-06-11,Single Family Residence Single Story,2019,8981
132303,2685 HWY 33,2962.102000,2962.102000,482989.154940,"MULTIPOLYGON (((46691.776 -350305.727, 46682.3...",2020-05-19 14:58:02,Compliant,34.864993,-119.489451,2685,Highway 33,None,Maricopa,Santa Barbara,CA,93252,US,2685 Highway 33 Maricopa Santa Barbara CA 9325...,2020-06-20,None,Single Family Residence Single Story,2020,8981

In [19]:
buffered_buildings = read_geojson_with_geopandas('/capstone/wildfire_prep/data/joined_inspections_parcels/buffered_buildings_2022.geojson')

In [20]:
buffered_buildings_copy = buffered_buildings.copy()

print(buffered_buildings.columns.tolist())

buff_buildings_columns = ['geometry']

buffered_buildings_copy = buffered_buildings_copy[buff_buildings_columns]

['release', 'capture_dates_range', 'STATEFP', 'COUNTYFP', 'COUNTYNS', 'GEOID', 'NAME', 'NAMELSAD', 'LSAD', 'CLASSFP', 'MTFCC', 'CSAFP', 'CBSAFP', 'METDIVFP', 'FUNCSTAT', 'ALAND', 'AWATER', 'INTPTLAT', 'INTPTLON', 'Shape_Leng', 'Shape_Area', 'index_right', 'apn_left_1', 'layer_1', 'situs1_1', 'situs2_1', 'acreage_1', 'landuse_1', 'usecode_1', 'tra_1', 'docnum_1', 'docdate_1', 'pcttransf_1', 'valreason_1', 'nontaxcode_1', 'sbeno_1', 'agpres_1', 'landvalue_1', 'strimpr_1', 'tradefix_1', 'livimpr_1', 'perpropdec_1', 'perspropun_1', 'mobilehome_1', 'exemptions_1', 'exempcode_1', 'homeowex_1', 'netsecval_1', 'net_impr_1', 'net_pers_1', 'net_unx_1', 'net_av_1', 'mailx1_1', 'mailx2_1', 'mnumber_1', 'mfrac_1', 'mdir_1', 'mstreet_1', 'mstrsuffix_1', 'munittype_1', 'munitnumb_1', 'pobox_1', 'mcity_1', 'mzip_1', 'mzipext_1', 'mstate_1', 'country_1', 'snum_1', 'sfra_1', 'sdir_1', 'sstreet_1', 'sstreetsuf_1', 'sunittype_1', 'sunitnumb_1', 'scity_1', 'szip_1', 'szipext_1', 'm_address1_1', 'm_address2_1', 'asmrollid_1', 'apn9_1', 'propid_1', 'sqfootage_1', 'yearbuilt_left_1', 'bedrooms_1', 'bathrooms_1', 'taxbill_1', 'permit_1', 'bkpglnk_1', 'gen_inquir_1', 'web_link_1', 'maptype_1', 'recmapnum_1', 'tractname_1', 'recmapbook_1', 'recmapdate_1', 'blocksecti_1', 'lotnum_1', 'unitnum_1', 'cbiinputs_zachary_canter_assess_1', 'areaunit_1', 'recdatetim_1', 'recuserid_1', 'recuserlog_1', 'section_1', 'township_1', 'range_1', 'shape_leng_1', 'shape_Length_1', 'shape_Area_1', 'log_acreage_1', 'fulcrum_id_1', 'created_at_1', 'updated_at_1', 'system_cre_1', 'system_upd_1', 'version_1', 'status_1', 'project_1', 'assigned_t_1', 'latitude_1', 'longitude_1', 'report_tit_1', 'globalid_1', 'keyid_1', 'propertyst_1', 'inspection_1', 'inspectorp_1', 'inspecti_1_1', 'addressvis_1', 'address_su_1', 'address_th_1', 'address__1_1', 'address_lo_1', 'address__2_1', 'address_ad_1', 'address_po_1', 'address_co_1', 'address_fu_1', 'calfireuni_1', 'county_1', 'community_1', 'community__1', 'battalion_1', 'enginenumb_1', 'stationnam_1', 'shift_1', 'shift_juli_1', 'accessegre_1', 'occupantho_1', 'deliveryno_1', 'inspecti_2_1', 'a_removebr_1', 'b_removele_1', 'c_removede_1', 'd_removede_1', 'e_removefl_1', 'f_removefl_1', 'g_relocate_1', 'h_cutannua_1', 'i_removefu_1', 'j_exposedw_1', 'k_removede_1', 'l_removelo_1', 'm_outbuild_1', 'n_displaya_1', 'o_stovepip_1', 'recommendc_1', 'waterstora_1', 'water_sour_1', 'can_engine_1', 'water_stor_1', 'water_comm_1', 'structuret_1', 'structureh_1', 'roofconstr_1', 'eaves_1', 'ventscreen_1', 'exteriorsi_1', 'windowpane_1', 'deckporchg_1', 'deckporche_1', 'patiocover_1', 'fenceattac_1', 'propanetan_1', 'utilitymis_1', 'utilitym_1_1', 'nonhabitab_1', 'escalateto_1', 'reinspecti_1', 'citationnu_1', 'number_of__1', 'photoid_1', 'photoid_ca_1', 'le100numbe_1', 'inspecti_3_1', 'coredata_1', 'firescopei_1', 'apn_right_1', 'yearbuilt_right_1', 'siteaddres_1', 'numberofst_1', 'appenddate_1', 'editstatus_1', 'calculated_1', 'calculat_1_1', 'calculat_2_1', 'textfield1_1', 'textfield2_1', 'numberfiel_1', 'numberfi_1_1', 'previousyr_1', 'previous_1_1', 'calculat_3_1', 'calculat_4_1', 'creationda_1', 'editdate_1', 'creator_1', 'editor_1', 'Date_1', 'apn_left_2', 'layer_2', 'situs1_2', 'situs2_2', 'acreage_2', 'landuse_2', 'usecode_2', 'tra_2', 'docnum_2', 'docdate_2', 'pcttransf_2', 'valreason_2', 'nontaxcode_2', 'sbeno_2', 'agpres_2', 'landvalue_2', 'strimpr_2', 'tradefix_2', 'livimpr_2', 'perpropdec_2', 'perspropun_2', 'mobilehome_2', 'exemptions_2', 'exempcode_2', 'homeowex_2', 'netsecval_2', 'net_impr_2', 'net_pers_2', 'net_unx_2', 'net_av_2', 'mailx1_2', 'mailx2_2', 'mnumber_2', 'mfrac_2', 'mdir_2', 'mstreet_2', 'mstrsuffix_2', 'munittype_2', 'munitnumb_2', 'pobox_2', 'mcity_2', 'mzip_2', 'mzipext_2', 'mstate_2', 'country_2', 'snum_2', 'sfra_2', 'sdir_2', 'sstreet_2', 'sstreetsuf_2', 'sunittype_2', 'sunitnumb_2', 'scity_2', 'szip_2', 'szipext_2', 'm_address1_2', 'm_address2_2', 'asmrollid_2', 'apn9_2', 'propid_2', 'sqfootage_2', 'yearbuilt_left_2', 'bedrooms_2', 'bathrooms_2', 'taxbill_2', 'permit_2', 'bkpglnk_2', 'gen_inquir_2', 'web_link_2', 'maptype_2', 'recmapnum_2', 'tractname_2', 'recmapbook_2', 'recmapdate_2', 'blocksecti_2', 'lotnum_2', 'unitnum_2', 'cbiinputs_zachary_canter_assess_2', 'areaunit_2', 'recdatetim_2', 'recuserid_2', 'recuserlog_2', 'section_2', 'township_2', 'range_2', 'shape_leng_2', 'shape_Length_2', 'shape_Area_2', 'log_acreage_2', 'fulcrum_id_2', 'created_at_2', 'updated_at_2', 'system_cre_2', 'system_upd_2', 'version_2', 'status_2', 'project_2', 'assigned_t_2', 'latitude_2', 'longitude_2', 'report_tit_2', 'globalid_2', 'keyid_2', 'propertyst_2', 'inspection_2', 'inspectorp_2', 'inspecti_1_2', 'addressvis_2', 'address_su_2', 'address_th_2', 'address__1_2', 'address_lo_2', 'address__2_2', 'address_ad_2', 'address_po_2', 'address_co_2', 'address_fu_2', 'calfireuni_2', 'county_2', 'community_2', 'community__2', 'battalion_2', 'enginenumb_2', 'stationnam_2', 'shift_2', 'shift_juli_2', 'accessegre_2', 'occupantho_2', 'deliveryno_2', 'inspecti_2_2', 'a_removebr_2', 'b_removele_2', 'c_removede_2', 'd_removede_2', 'e_removefl_2', 'f_removefl_2', 'g_relocate_2', 'h_cutannua_2', 'i_removefu_2', 'j_exposedw_2', 'k_removede_2', 'l_removelo_2', 'm_outbuild_2', 'n_displaya_2', 'o_stovepip_2', 'recommendc_2', 'waterstora_2', 'water_sour_2', 'can_engine_2', 'water_stor_2', 'water_comm_2', 'structuret_2', 'structureh_2', 'roofconstr_2', 'eaves_2', 'ventscreen_2', 'exteriorsi_2', 'windowpane_2', 'deckporchg_2', 'deckporche_2', 'patiocover_2', 'fenceattac_2', 'propanetan_2', 'utilitymis_2', 'utilitym_1_2', 'nonhabitab_2', 'escalateto_2', 'reinspecti_2', 'citationnu_2', 'number_of__2', 'photoid_2', 'photoid_ca_2', 'le100numbe_2', 'inspecti_3_2', 'coredata_2', 'firescopei_2', 'apn_right_2', 'yearbuilt_right_2', 'siteaddres_2', 'numberofst_2', 'appenddate_2', 'editstatus_2', 'calculated_2', 'calculat_1_2', 'calculat_2_2', 'textfield1_2', 'textfield2_2', 'numberfiel_2', 'numberfi_1_2', 'previousyr_2', 'previous_1_2', 'calculat_3_2', 'calculat_4_2', 'creationda_2', 'editdate_2', 'creator_2', 'editor_2', 'Date_2', 'area', 'geometry']

In [21]:
buffered_buildings_copy

                                               geometry
0     POLYGON ((-22767.476 -375448.119, -23014.787 -...
1     POLYGON ((-9290.574 -378632.312, -9035.561 -37...
2     POLYGON ((-38766.251 -371421.02, -38538.65 -37...
3     POLYGON ((-11561.332 -372335.927, -11718.559 -...
4     POLYGON ((-23742.879 -348820.427, -23927.393 -...
...                                                 ...
9030  POLYGON ((-42570.319 -369065.356, -42570.319 -...
9031  POLYGON ((-42539.328 -367092.847, -42539.446 -...
9032  POLYGON ((-8759.709 -378740.536, -8759.709 -37...
9033  POLYGON ((-42551.126 -367015.662, -42551.159 -...
9034  POLYGON ((13217.108 -395211.873, 13217.061 -39...

[9035 rows x 1 columns]

In [22]:
inspections_buffbuildings = gpd.sjoin(
        buffered_buildings_copy, all_inspections_copy, how="inner", predicate="contains")

In [23]:
inspections_buffbuildings.dtypes

geometry                   geometry
index_right                   int64
system_created       datetime64[ms]
inspection_status            object
latitude                    float64
longitude                   float64
address_number               object
street                       object
apt_number                   object
city                         object
county                       object
state                        object
zip_code                     object
country                      object
address_full                 object
date                 datetime64[ms]
inspection_date              object
structure_type               object
year                          int64
address_id                    int64
dtype: object

In [24]:
inspections_buffbuildings.drop("index_right", axis=1, inplace=True)
inspections_buffbuildings

,geometry,system_created,inspection_status,latitude,longitude,address_number,street,apt_number,city,county,state,zip_code,country,address_full,date,inspection_date,structure_type,year,address_id
1,"POLYGON ((-9290.574 -378632.312, -9035.561 -37...",2021-04-05 09:33:18,Compliant,34.608120,-120.099620,2975,Mission Dr,None,Solvang,Santa Barbara,CA,93463,US,2975 Mission Dr Solvang Santa Barbara CA 93463 US,2021-07-08,None,School,2021,9978
1,"POLYGON ((-9290.574 -378632.312, -9035.561 -37...",2019-05-28 16:18:04,Compliant,34.608120,-120.099620,2975,Mission Dr,None,Solvang,Santa Barbara,CA,93463,US,2975 Mission Dr Solvang Santa Barbara CA 93463 US,2019-10-10,2019-10-10,School,2019,9978
1,"POLYGON ((-9290.574 -378632.312, -9035.561 -37...",2020-05-19 15:01:53,Compliant,34.608120,-120.099620,2975,Mission Dr,None,Solvang,Santa Barbara,CA,93463,US,2975 Mission Dr Solvang Santa Barbara CA 93463 US,2020-07-10,None,School,2020,9978
1,"POLYGON ((-9290.574 -378632.312, -9035.561 -37...",2022-04-05 13:50:56,Compliant,34.608120,-120.099620,2975,Mission Dr,None,Solvang,Santa Barbara,CA,93463,US,2975 Mission Dr Solvang Santa Barbara CA 93463 US,2022-08-15,None,School,2022,9978
1,"POLYGON ((-9290.574 -378632.312, -9035.561 -37...",2023-08-15 12:41:48,Compliant,34.608120,-120.099620,2975,Mission Dr,None,Solvang,Santa Barbara,CA,93463,US,2975 Mission Dr Solvang Santa Barbara CA 93463 US,2023-08-14,2023-08-14,School,2023,9978
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8945,"POLYGON ((22007.218 -395742.615, 22004.059 -39...",2022-04-06 09:58:21,Compliant,34.454282,-119.760424,4120,Via Andorra,None,Santa Barbara,Santa Barbara,CA,93110,US,4120 Via Andorra Santa Barbara Santa Barbara C...,2022-06-29,None,Multi Family Residence Multi Story,2022,911
8945,"POLYGON ((22007.218 -395742.615, 22004.059 -39...",2023-06-21 17:00:00,Compliant,34.454282,-119.760424,4120,Via Andorra,None,Santa Barbara,Santa Barbara,CA,93110,US,4120 Via Andorra Santa Barbara Santa Barbara C...,2023-06-21,2023-06-21,Multi Family Residence Multi Story,2023,911
8945,"POLYGON ((22007.218 -395742.615, 22004.059 -39...",2021-04-05 08:55:38,Compliant,34.454282,-119.760424,4120,Via Andorra,None,Santa Barbara,Santa Barbara,CA,93110,US,4120 Via Andorra Santa Barbara Santa Barbara C...,2021-06-12,None,Multi Family Residence Multi Story,2021,911
8945,"POLYGON ((22007.218 -395742.615, 22004.059 -39...",2019-05-28 15:19:48,Compliant,34.454282,-119.760424,4120,Via Andorra,None,Santa Barbara,Santa Barbara,CA,93110,US,4120 Via Andorra Santa Barbara Santa Barbara C...,2019-06-07,2019-06-07,Multi Family Residence Multi Story,2019,911
8945,"POLYGON ((22007.218 -395742.615, 22004.059 -39...",2020-05-18 16:28:16,Compliant,34.454282,-119.760424,4120,Via Andorra,None,Santa Barbara,Santa Barbara,CA,93110,US,4120 Via Andorra Santa Barbara Santa Barbara C...,2020-07-29,None,Multi Family Residence Multi Story,2020,911

In [25]:
inspections_parcels

,situs1,shape_leng,shape_Length,shape_Area,geometry,system_created,inspection_status,latitude,longitude,address_number,street,apt_number,city,county,state,zip_code,country,address_full,date,inspection_date,structure_type,year,address_id
203,1450 CAMINO MANADERO,903.335649,903.335649,40102.354471,"MULTIPOLYGON (((16347.387 -394504.877, 16342.5...",2020-05-18 16:29:44,Compliant,34.466073,-119.821791,1450,Camino Manadero,None,Santa Barbara,Santa Barbara,CA,93111,US,1450 Camino Manadero Santa Barbara Santa Barba...,2020-06-27,None,Single Family Residence Single Story,2020,1311
203,1450 CAMINO MANADERO,903.335649,903.335649,40102.354471,"MULTIPOLYGON (((16347.387 -394504.877, 16342.5...",2019-05-28 15:21:11,Compliant,34.466073,-119.821791,1450,Camino Manadero,None,Santa Barbara,Santa Barbara,CA,93111,US,1450 Camino Manadero Santa Barbara Santa Barba...,2019-06-25,2019-06-25,Single Family Residence Single Story,2019,1311
203,1450 CAMINO MANADERO,903.335649,903.335649,40102.354471,"MULTIPOLYGON (((16347.387 -394504.877, 16342.5...",2021-04-05 08:56:31,Compliant,34.466073,-119.821791,1450,Camino Manadero,None,Santa Barbara,Santa Barbara,CA,93111,US,1450 Camino Manadero Santa Barbara Santa Barba...,2021-06-26,None,Single Family Residence Single Story,2021,1311
203,1450 CAMINO MANADERO,903.335649,903.335649,40102.354471,"MULTIPOLYGON (((16347.387 -394504.877, 16342.5...",2022-04-06 09:59:33,Compliant,34.466073,-119.821791,1450,Camino Manadero,None,Santa Barbara,Santa Barbara,CA,93111,US,1450 Camino Manadero Santa Barbara Santa Barba...,2022-07-05,None,Single Family Residence Single Story,2022,1311
205,1475 CAMINO MELENO,1113.961402,1113.961402,57984.774296,"MULTIPOLYGON (((16811.85 -394379.557, 16800.14...",2019-05-28 15:21:27,Compliant,34.466445,-119.817230,1475,Camino Meleno,None,Santa Barbara,Santa Barbara,CA,93111,US,1475 Camino Meleno Santa Barbara Santa Barbara...,2019-06-25,2019-06-25,Single Family Residence Single Story,2019,1376
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132303,2685 HWY 33,2962.102000,2962.102000,482989.154940,"MULTIPOLYGON (((46691.776 -350305.727, 46682.3...",2023-08-22 17:28:10,Compliant,34.864993,-119.489451,2685,Highway 33,None,Maricopa,Santa Barbara,CA,93252,US,2685 Highway 33 Maricopa Santa Barbara CA 9325...,2023-08-22,2023-08-22,Single Family Residence Single Story,2023,8981
132303,2685 HWY 33,2962.102000,2962.102000,482989.154940,"MULTIPOLYGON (((46691.776 -350305.727, 46682.3...",2022-04-05 13:47:50,Compliant,34.864993,-119.489451,2685,Highway 33,None,Maricopa,Santa Barbara,CA,93252,US,2685 Highway 33 Maricopa Santa Barbara CA 9325...,2022-06-28,None,Single Family Residence Single Story,2022,8981
132303,2685 HWY 33,2962.102000,2962.102000,482989.154940,"MULTIPOLYGON (((46691.776 -350305.727, 46682.3...",2021-04-05 09:30:25,Compliant,34.864993,-119.489451,2685,Highway 33,None,Maricopa,Santa Barbara,CA,93252,US,2685 Highway 33 Maricopa Santa Barbara CA 9325...,2021-08-17,None,Single Family Residence Single Story,2021,8981
132303,2685 HWY 33,2962.102000,2962.102000,482989.154940,"MULTIPOLYGON (((46691.776 -350305.727, 46682.3...",2019-05-28 16:13:31,Compliant,34.864993,-119.489451,2685,Highway 33,None,Maricopa,Santa Barbara,CA,93252,US,2685 Highway 33 Maricopa Santa Barbara CA 9325...,2019-06-11,2019-06-11,Single Family Residence Single Story,2019,8981
132303,2685 HWY 33,2962.102000,2962.102000,482989.154940,"MULTIPOLYGON (((46691.776 -350305.727, 46682.3...",2020-05-19 14:58:02,Compliant,34.864993,-119.489451,2685,Highway 33,None,Maricopa,Santa Barbara,CA,93252,US,2685 Highway 33 Maricopa Santa Barbara CA 9325...,2020-06-20,None,Single Family Residence Single Story,2020,8981

/capstone/wildfire_prep/data/inspections_data/cleaned_status_with_id

In [26]:
inspections_buffbuildings.to_file(
    "/capstone/wildfire_prep/data/inspections_data/cleaned_status_with_id/inspections_buffered_buildings.geojson",
    driver="GeoJSON",
)

inspections_parcels.to_file(
    "/capstone/wildfire_prep/data/inspections_data/cleaned_status_with_id/inspections_parcels.geojson",
    driver="GeoJSON",
)