# Create unique ID and concatenate separate years into one dataframe

In [17]:
import os
import sys

import geopandas as gpd
import numpy as np
import pandas as pd

sys.path.append("../utils")

import config

pd.set_option("display.max_columns", None)

### Import unclipped training geometries

In [18]:
def process_training_geometries(start_year, end_year):
    """
    Process training geometries for a range of years, standardize columns, and combine them into a single GeoDataFrame.
    Preserves the existing inspection_id values and sorts the final result by inspection_id.

    Args:
        start_year (int): The starting year of the range.
        end_year (int): The ending year of the range.

    Returns:
        GeoDataFrame: Combined, processed, and sorted GeoDataFrame.
    """

    def import_training_geometries(year):
        """
        Function to read in buffer geometry data for a given year and convert to Albers CRS.
        """
        training_geometries = os.path.join(
            config.data_dir,
            "training_geometries",
            f"training_geometries_{year}.geojson",
        )
        return gpd.read_file(training_geometries).to_crs(config.albers_crs)

    # Import and process geometries for each year
    inspections_dict = {
        year: import_training_geometries(year)
        for year in range(start_year, end_year + 1)
    }

    # Add a `year` column to each dataframe
    for year, df in inspections_dict.items():
        df["year"] = year

    # Combine all years into one dataframe
    training_inspections = pd.concat(
        inspections_dict.values(), axis=0, ignore_index=True
    )
    
    # Sort by inspection_id to ensure consistent ordering
    training_inspections = training_inspections.sort_values('inspection_id').reset_index(drop=True)

    return training_inspections

In [19]:
training_inspections = process_training_geometries(2019, 2023)
training_inspections

,inspection_id,apn,Date,year,month,status,geometry
0,1,None,2019-06-05,2019,6,Compliant,"POLYGON ((-2892.357 -371905.217, -2813.179 -37..."
1,2,None,2019-05-09,2019,5,Compliant,"POLYGON ((-8475.394 -370860.259, -8368.416 -37..."
2,3,None,2019-05-09,2019,5,Compliant,"POLYGON ((-8253.618 -371183.727, -8136.129 -37..."
3,4,None,2019-05-09,2019,5,Compliant,"POLYGON ((-8201.866 -370989.432, -8091.086 -37..."
4,5,None,2019-12-17,2019,12,Compliant,"POLYGON ((-8065.883 -370931.624, -7966.144 -37..."
...,...,...,...,...,...,...,...
67575,67576,None,2023-10-31,2023,10,Compliant,"POLYGON ((-35016.13 -349482.83, -34938.314 -34..."
67576,67577,None,2023-11-15,2023,11,Compliant,"POLYGON ((-36511.881 -350331.419, -36432.622 -..."
67577,67578,None,2023-11-15,2023,11,Compliant,"POLYGON ((-38782.099 -346106.741, -38702.857 -..."
67578,67579,None,2023-11-15,2023,11,Compliant,"POLYGON ((-38988.592 -346166.568, -38884.895 -..."
67579,67580,None,2023-12-01,2023,12,Compliant,"POLYGON ((-39771.728 -350587.563, -39690.963 -..."

In [20]:
# Write to file
training_inspections.to_file(
    os.path.join(
        config.data_dir,
        "PUZZLE_PIECES",
        "inspections_master_training_geometries.geojson",
    ),
    driver="GeoJSON",
)

### Import clipped geometries

In [21]:
def process_buffer_geometries(start_year, end_year):
    """
    Process buffer geometries for a range of years, standardize columns, and combine them into a single GeoDataFrame.
    Preserves the existing inspection_id values and sorts the final result by inspection_id.

    Args:
        start_year (int): The starting year of the range.
        end_year (int): The ending year of the range.

    Returns:
        GeoDataFrame: Combined, processed, and sorted GeoDataFrame.
    """

    def import_buffer_geometries(year):
        """
        Function to read in buffer geometry data for a given year and convert to Albers CRS.
        """
        buffer_geometries = os.path.join(
            config.data_dir,
            "buffer_geometries",
            f"buffer_geometries_{year}.geojson",
        )
        return gpd.read_file(buffer_geometries).to_crs(config.albers_crs)

    # Import and process geometries for each year
    inspections_dict = {
        year: import_buffer_geometries(year) for year in range(start_year, end_year + 1)
    }

    # Add a `year` column to each dataframe
    for year, df in inspections_dict.items():
        df["year"] = year
        # Reset index to ensure unique indices before concatenation
        inspections_dict[year] = df.reset_index(drop=True)

    # Find common columns across all dataframes
    common_cols = set.intersection(
        *[set(df.columns) for df in inspections_dict.values()]
    )

    # Only keep common columns before concatenation
    for year in inspections_dict:
        inspections_dict[year] = inspections_dict[year][list(common_cols)]

    # Combine all years into one dataframe
    buffer_inspections = pd.concat(inspections_dict.values(), axis=0, ignore_index=True)
    
    # Sort by inspection_id to ensure consistent ordering
    buffer_inspections = buffer_inspections.sort_values('inspection_id').reset_index(drop=True)

    return buffer_inspections

In [22]:
buffer_inspections = process_buffer_geometries(2019, 2023)
buffer_inspections

/tmp/ipykernel_560387/4052484543.py:46: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  buffer_inspections = pd.concat(inspections_dict.values(), axis=0, ignore_index=True)
/tmp/ipykernel_560387/4052484543.py:46: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  buffer_inspections = pd.concat(inspections_dict.values(), axis=0, ignore_index=True)
/tmp/ipykernel_560387/4052484543.py:46: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  buffer_inspections = pd.concat(inspections_dict.values(), axis=0, ignore_index=True)

,occupantho,inspecti_3,number_of_dead_trees_within_300_ft_of_residence,project,shift_juli,enginenumber,calfireuni,creationdate,water_source,clearreins,firescopeid,c_removede,community,n_addressd,deckporchelevated,previous_1,appenddate,previousyr,recommend_,e_removedy,calculat_2,apn,prevention_inspectorlastname,keyid,system_upd,address_lo,calculat_3,address_sub_thoroughfare,water_comments,h_cutannua,stationname,l_removelogstumpsembeddedsoil,structuretype,i_reducefu,community_,assigned_to,inspectionstatus,k_removedeaddyingwoodyfuels,partner_di,water_comm,j_allexpos,exteriorsi,editedby,photoid_url,addressvisible,system_created_at,inspectioncount,numberfield2,citationda,textfield2,addressvis,f_removefl,utilitym_1,photoid,address_th,le100number,siteaddres,editstatus,k_removede,month,updated_at,l_removelo,principal_,calculatedglobalid,created_by,address_co,reinspecti,n_displayaddresscontrasting,address_po,deckporchgrade,calculat_1,county,reinspectiondate,stationn_1,coredatafl,nonhabitableoutbuildings,stationnam,year,numberfield1,le100numbe,e_removefl,address_country,water_sour,address__2,b_removeleavesneedlesveg,inspectiondate_calculate,number_of_,comments,prevention_inspectorlastname_other,latitude,exteriorsiding,address_postal_code,structurehabitable,inspection,utilitymis,h_cutannualgrassesforbs,editor,address__1,version,updated_by,b_removele,i_removefuelsusingctguidelines,geometry,calculateduid,c_removedeaddyingtrees,gatecode,system_cre,system_updated_at,firescopei,o_stovepip,address_thoroughfare,battalion,deliverynotificationmethod,textfield1,enginenumb,address_locality,j_exposedw,address_fu,address_admin_area,water_stor,createddat,eaves,ventscreen,waterstora,propanetankdistance,status,fulcrum_id,assigned_t,propertyst,n_displaya,coredata,patiocovercarport,g_relocateexposedwoodpiles,numberofstructures,inspectorp,m_outbuild,createdby,address_suite,a_removebranchesfromstovepipe,calfireunit,creator,o_stovepipemetalscreenopenings,deadtrees3,address_su,core_with_,address_full,inspecti_1,calculatededitor,previousyrinspecteddata,prevention_inspectorfirstname_other,shift,citationnu,inspectorfirstname,photoid_caption,inspection_id,j_exposedwoodpiles,a_removebr,prevention_inspectorfirstname,address_sub_admin_area,shift_julian,roofconstruction,utilitymiscstucturecount,roofconstr,inspectorlastname,escalatetocoordinator,numberfiel,longitude,e_removeflammablegroundcover,creationda,editdate,fenceattachedtostructure,propertystatus,l_logsstum,deckporche,created_at,nonhabitab,i_removefu,recommendc,inspectorposition,m_outbuildingsliquidpropanegas,o_chimneys,fenceattac,calculatededitdate,editeddate,windowpane,can_engine,k_deaddyin,calculat_4,citationnumber,siteaddress,inspecti_2,accessegre,patiocover,yearbuilt,address_ad,responsibi,structuret,numberofst,d_removede,deliveryno,g_relocate,accessegress,previousyrinspectionstatus,f_removeflammablevegetation,report_title,calculated,recommendclearvegetation,report_tit,escalateto,water_storage_size_stored_water_on_individual_parcels_only,occupanthome,inspectionhours,d_removedeaddyinggrassplants,deckporchg,numberfi_1,calculateddate,community_other,structureh,photoid_ca,can_engine_access_water_source,propanetan,Date,globalid,utilitymiscstructuredistance
0,Yes,NaN,NaN,None,None,NaN,SBC,NaT,None,None,None,None,Woodstock,None,None,None,2019-06-05,None,None,None,None,141-010-040,None,NaN,2019-06-05 16:35:26,Santa Ynez,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Wood,None,None,None,NaT,None,None,None,None,Yes - Without Reflective,None,0,None,Brinkerhoff Rd,None,None,None,None,6,2019-06-05 11:57:49,None,None,None,None,US,NaT,None,93460,None,None,SBA,NaT,None,None,None,32,2019,None,0.0,None,None,Private Hydrant- Private Stored Water,Santa Barbara,None,NaT,NaN,None,None,34.669616,None,None,None,2019-06-05,30-50',None,None,None,2.0,None,None,None,"POLYGON ((-2813.179 -371821.557, -2813.179 -37...",None,None,None,2019-05-07 11:52:36,NaT,None,None,None,2,None,None,32,None,None,3462 Brinkerhoff Rd Santa Ynez Santa Barbara C...,None,Over 5000 gallons,None,Unenclosed,No Vents,yes,None,Compliant,d9a4d031-d16d-4c84-b32c-f3fcd7d945df,None,None,None,None,None,None,None,DSI,None,None,None,None,None,None,None,0,3462,None,None,30 min,None,None,None,None,None,None,None,1,None,None,None,None,None,None,None,Metal,None,None,0.0,-120.031160,None,NaT,NaT,None,None,None,No Deck/Porch,2018-05-25 16:25:06,0,None,None,None,None,None,No Fence,None,None,No Windows,yes,None,None,None,None,0.0,yes,No Patio Cover/Carport,2000.0,CA,None,Utility or Miscellaneous Structure > 120 sqft,0.0,None,Hardcopy,None,None,None,None,None,None,None,Defensible Space Inspection Report,None,None,None,None,None,No Deck/Porch,0.0,None,None,None,None,None,>30',2019-06-05,None,None
1,No,NaN,NaN,None,None,NaN,SBC,NaT,None,None,None,None,Woodstock,None,None,None,2019-05-09,None,None,None,None,135-310-022,None,NaN,2019-05-15 12:26:45,Santa Ynez,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Wood,None,None,None,NaT,None,None,None,None,Yes - Without Reflective,None,1,f1556c16-78c8-44bf-b6ce-a7ddb5908d96,Avenida Caballo,None,None,None,None,5,2019-05-15 12:26:44,None,None,None,None,US,NaT,None,93460,None,None,SBA,NaT,None,None,None,Santa Ynez Valley (Outside Engine Co. Area),2019,None,0.0,None,None,Private Hydrant- Private Stored Water,Santa Barbara,None,NaT,NaN,None,None,34.679129,None,None,None,2019-05-09,30-50',None,None,None,3.0,None,None,None,"POLYGON ((-8368.416 -370860.259, -8475.394 -37...",None,None,None,2019-05-07 11:52:37,NaT,None,None,None,2,None,None,32,None,None,3290 Avenida Caballo Santa Ynez Santa Barbara ...,None,None,None,No Eaves,No Vents,yes,None,Compliant,7f9b6d98-548d-4b94-97c6-82cbddf84d99,None,None,None,None,None,None,None,DSI,None,None,None,None,None,None,None,None,3290,None,None,15 min,None,None,None,None,None,None,None,2,None,None,None,None,None,None,None,Metal,None,None,0.0,-120.091914,None,NaT,NaT,None,None,None,No Deck/Porch,2018-05-25 16:25:10,0,None,None,None,None,None,No Fence,None,None,Single Pane,yes,None,None,None,None,0.0,yes,No Patio Cover/Carport,0.0,CA,None,Single Family Residence Multi Story,0.0,None,Email,None,None,None,None,None,None,None,Defensible Space Inspection Report,None,None,None,None,None,No Deck/Porch,0.0,None,None,None,None,None,Not Applicable,2019-05-09,None,None
2,No,NaN,NaN,None,None,NaN,SBC,NaT,None,None,None,None,Woodstock,None,None,None,2019-05-09,None,None,None,None,135-310-075,None,NaN,2019-05-09 15:26:24,Santa Ynez,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Stucco/Brick/Cement,None,None,None,NaT,None,None,None,None,Yes - Without Reflective,None,2,None,Caballo Ln,None,None,None,None,5,2019-05-09 14:20:04,None,None,None,None,US,NaT,None,93460,None,None,SBA,NaT,None,None,None,Santa Ynez Valley (Outside Engine Co. Area),2019,None,0.0,None,None,None,Santa Barbara,None,NaT,NaN,None,None,34.676197,None,None,None,2019-05-09,>50',None,None,None,2.0,None,None,None,"POLYGON ((-8253.618 -371073.707, -8136.129 -37...",None,None,None,2019-05-07 11:52:37,NaT,None,None,None,2,None,None,32,None,None,3350 Caballo Ln Santa Ynez Santa Barbara CA 93...,None,None,None,Unenclosed,No Vents,None,None,Compliant,03afdf39-173a-4f02-bfdc-e0725e554959,None,None,None,None,None,None,None,DSI,None,None,None,None,None,None,None,None,3350,None,None,15 min,None,None,None,None,None,None,None,3,None,None,None,None,None,None,None,Tile,None,None,0.0,-120.089553,None,NaT,NaT,None,None,None,No Deck/Porch,2018-05-25 16:25:11,0,None,None,None,None,None,No Fence,None,None,Multi Pane,None,None,None,None,None,0.0,yes,No Patio Cover/Carport,0.0,CA,None,Single Family Residence Multi Story,0.0,None,Email,None,None,None,None,None,None,None,Defensible Space Inspection Report,None,None,None,None,None,No Deck/Porch,0.0,None,None,None,None,None,Not Applicable,2019-05-09,None,None
3,Yes,NaN,NaN,None,None,NaN,SBC,NaT,None,None,None,None,Woodstock,None,None,None,2019-05-09,None,None,None,None,135-310-075,None,NaN,2019-05-09 15:26:26,Santa Ynez,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Metal,None,None,None,NaT,None,None,None,None,Yes - Without Reflective,None,0,17322007-d5d1-4568-bde6-00ae169a0bbf,Caballo Ln,None,None,None,None,5,2019-05-09 14:25:18,None,None,None,None,US,NaT,None,93460,None,None,SBA,NaT,None,None,None,Santa Ynez Valley (Outside Engine Co. Area),2019,None,0.0,None,None,None,Santa Barbara,None,NaT,NaN,None,None,34.677982,None,None,None,2019-05-09,None,None,None,None,2.0,None,None,None,"POLYGON ((-8201.866 -370989.432, -8201.866 -37...",None,None,None,2019-05-07 11:52:38,NaT,None,None,None,2,None,None,32,None,None,3350 Caballo Ln Santa Ynez Santa Barbara CA 93...,None,None,None,Unenclosed,No Vents,no,None,Compliant,941e29b0-6cd3-4c7e-a919-b8f2410b4a2b,None,None,None,None,None,None,None,DSI,None,None,None,None,None,None,None,None,3350,None,None,15 min,None,None,None,None,None,None,None,4,None,None,None,None,None,None,None,Metal,None,None,0.0,-120.088944,None,NaT,NaT,None,None,None,No Deck/Porch,2018-05-25 16:25:11,0,None,None,None,None,None,No Fence,None,None,Single Pane,None,None,None,None,None,0.0,yes,No Patio Cover/Carport,0.0,CA,None,Utility or Miscellaneous Structure > 120 sqft,0.0,None,Email,None,None,None,None,None,None,None,Defensible Space Inspection Report,None,None,None,None,None,Masonry/Concrete,0.0,None,None,None,None,None,Not Applicable,2019-05-09,None,None
4,No,NaN,NaN,None,None,NaN,SBC,NaT,None,None,None,None,Woodstock,None,None,None,2019-05-08,None,None,None,None,135-310-042,None,NaN,2019-12-18 11:43:23,Santa Ynez,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Wood,None,None,None,NaT,None,None,None,None,Yes - Without Reflective,None,0,50114b4c-e04a-4054-bd54-5a7dbca535af,Canada Este Rd,None,None,None,None,12,2019-12-17 14:16:14,None,None,None,None,US,NaT,None,93460,None,None,SBA,NaT,None,None,None,Santa Ynez Valley (Outside Engine Co. Area),2019,None,0.0,None,None,Pond,Santa Barbara,None,NaT,NaN,None,None,34.678469,None,None,None,2019-12-17,None,None,None,None,5.0,None,None,None,"POLYGON ((-7966.144 -370818.558, -7966.144 -37...",None,None,None,2019-05-07 11:52:38,NaT,None,None,None,2,None,None,32,None,None,3320 A Canada Este Rd Santa Ynez Santa Barbara...,None,None,None,Unenclosed,"Mesh Screen > 1/8""",yes,None,Compliant,abe890ba-3269-4ef6-84d7-4a9b6bfd717e,None,None,None,None,None,None,None,DSI,None,None,None,None,None,None,None,None,3320 A,None,None,5 min,None,None,None,None,None,None,None,5,None,None,None,None,None,None,None,Asphalt,None,None,0.0,-120.087539,None,NaT,NaT,None,None,None,No Deck/Porch,2018-05-25 16:25:11,0,None,None,None,None,None,No Fence,None,None,Single Pane,None,None,None,None,None,0.0,yes,Non Combustible,2002.0,CA,None,Single Family Residence Multi Story,0.0,None,Hardcopy,None,None,None,None,None,None,None,Defensible Space Inspection Report,None,None,None,None,None,Masonry/Concrete,0.0,None,None,None,None,None,>30',2019-12-17,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67575,None,NaN,0.0,None,None,NaN,None,2023-10-30,None,None,None,None,None,None,None,None,NaT,None,None,None,None,129-132-001,Gailey,NaN,NaT,None,None,2114,None,None,26,None,Single Family Residence Multi Story,None,None,None,None,None,None,None,None,None,None,None,None,2023-10-30 16:45:18,None,None,None,None,None,None,None,None,None,None,None,None,None,10,2023-11-06 13:09:08,None,None,None,anne.mitcham@sbcfire.com,None,NaT,None,None,None,None,SBA,NaT,None,None,None,None,2023,None,NaN,None,None,None,None,None,2023-10-31,NaN,None,None,34.870960,None,93455,Habitable,None,None,None,None,None,2.0,anne.mitcham@sbcfire.com,None,None,"POLYGON ((-34938.314 -349478.543, -34991.669 -...",None,None,None,NaT,2023-11-06 13:09:08,None,None,Fallen Leaf Drive,2,Email,None,None,Santa Maria,None,None,CA,None,None,None,"Mesh Screen <= 1/8""",None,None,Compliant,3b9d56ac-899c-440d-8370-9ec2636cc40f,None,None,None,None,None,None,None,None,None,None,None,None,SBC,None,None,None,None,None,2114 Fallen Leaf Drive Santa Maria Santa Barba...,None,None,None,None,C,None,None,None,67576,None,None,Tim,Santa Barbara,310,None,None,None,None,None,NaN,-120.382833,None,NaT,2023-10-30,None,None,None,None,2023-10-30 16:45:17,None,None,None,Prevention,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,None,None,Yes,None,None,Defensible Space Inspection Report,None,None,None,None,None,No,15,None,None,NaN,None,None,None,None,None,None,2023-10-31,None,None
67576,None,NaN,0.0,None,None,NaN,None,2023-11-15,None,None,None,None,Orcutt,None,None,None,NaT,None,None,None,None,129-280-026,Gailey,NaN,NaT,None,None,1600,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,2023-11-15 13:38:59,None,None,None,None,None,None,None,None,None,None,None,None,None,11,2023-11-15 14:21:12,None,None,None,anne.mitcham@sbcfire.com,None,NaT,None,None,None,None,SBA,NaT,None,None,None,None,2023,None,NaN,None,None,None,None,None,2023-11-15,NaN,None,None,34.863251,None,93455,Habitable,None,None,None,None,None,2.0,anne.mitcham@sbcfire.com,None,None,"POLYGON ((-36511.881 -350331.419, -36511.881 -...",None,None,None,NaT,2023-11-15 14:21:12,None,None,East Clark,2,Email,None,None,Orcutt,None,None,CA,None,None,None,"Mesh Screen <= 1/8""",None,None,Compliant,5ba57641-41b8-4d9c-adee-098dbe4876b0,None,None,None,None,None,None,None,None,None,None,Space 158,None,SBC,None,None,None,None,None,1600 East Clark Space 158 Orcutt Santa Barba...,None,None,None,None,C,None,None,None,67577,None,None,Tim,Santa Barbara,319,None,None,None,None,None,NaN,-120.399151,None,NaT,2023-11-15,None,None,None,None,2023-11-15 13:38:59,None,None,None,Prevention,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,None,None,Yes,None,None,Defensible Space Inspection Report,None,None,None,None,None,No,15,None,None,NaN,None,None,None,None,None,None,2023-11-15,None,None
67577,None,NaN,0.0,None,None,NaN,None,2023-11-15,None,None,None,None,Orcutt,None,None,None,NaT,None,None,None,None,109-200-026,Gailey,NaN,NaT,None,None,3210,None,None,None,None,Mobile Home Double Wide,None,None,None,None,None,None,None,None,None,None,None,None,2023-11-15 14:49:41,None,None,None,None,None,None,None,None,None,None,None,None,None,11,2023-11-20 10:27:11,None,None,None,anne.mitcham@sbcfire.com,None,NaT,None,None,None,None,SBA,NaT,None,None,None,None,2023,None,NaN,None,None,None,None,None,2023-11-15,NaN,None,None,34.901260,None,93455,Habitable,None,None,None,None,None,3.0,anne.mitcham@sbcfire.com,None,None,"POLYGON ((-38702.857 -346029.921, -38702.857 -...",None,None,None,NaT,2023-11-20 10:27:12,None,None,Santa Maria Way,2,Email,None,None,Orcutt,None,None,CA,None,None,None,"Mesh Screen <= 1/8""",None,None,Compliant,bd357572-7828-4f55-b827-fc4d63d0f69b,None,None,None,None,None,None,None,None,None,None,Space 153,None,SBC,None,None,None,None,None,3210 Santa Maria Way Space 153 Orcutt Santa B...,None,None,None,None,A,None,None,None,67578,None,None,Tim,Santa Barbara,324,None,None,None,None,None,NaN,-120.424188,None,NaT,2023-11-15,None,None,None,None,2023-11-15 14:49:40,None,None,None,Prevention,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,None,None,Yes,None,None,Defensible Space Inspection Report,None,None,None,None,None,No,15,None,None,NaN,None,None,None,None,None,None,2023-11-15,None,None
67578,None,NaN,0.0,None,None,NaN,None,2023-11-15,None,None,None,None,Orcutt,None,None,None,NaT,None,None,None,None,109-200-023,Gailey,NaN,NaT,None,None,3210,None,None,None,None,Mobile Home Double Wide,None,None,None,None,None,None,None,None,None,None,None,None,2023-11-15 14:59:17,None,None,None,None,None,None,None,None,None,None,None,None,None,11,2023-11-15 16:18:32,None,None,None,anne.mitcham@sbcfire.com,None,NaT,None,None,None,None,SBA,NaT,None,None,None,None,2023,None,NaN,None,None,None,None,None,2023-11-15,NaN,None,None,34.900785,None,93455,Habitable,None,None,None,None,None,2.0,anne.mitcham@sbcfire.com,None,None,"POLYGON ((-38988.592 -346062.709, -38884.895 -...",None,None,None,NaT,2023-11-15 16:18:32,None,None,Santa Maria Way,2,Email,None,None,Orcutt,None,None,CA,None,None,None,"Mesh Screen <= 1/8""",None,None,Compliant,9830aba3-0c5e-4fa4-a704-d565da2f8519,None,None,None,None,None,None,None,None,None,None,Space 153,None,SBC,None,None,None,None,None,3210 Santa Maria Way Space 153 Orcutt Santa Ba...,None,None,None,None,C,None,None,None,67579,None,None,Tim,Santa Barbara,319,None,None,None,None,None,NaN,-120.426280,None,NaT,2023-11-15,None,None,None,None,2023-11-15 14:59:11,None,None,None,Engine,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,None,None,Yes,None,None,Defensible Space Inspection Report,None,None,None,None,None,No,15,None,None,NaN,None,None,None,None,None,None,2023-11-15,None,None
67579,None,NaN,0.0,None,None,NaN,None,2023-12-01,None,None,None,None,Rice Ranch,None,None,None,NaT,None,None,None,None,103-192-003,Gailey,NaN,NaT,None,None,206,None,None,21,None,Single Family Residence Single Story,None,None,None,None,None,None,None,None,None,None,None,None,2023-12-01 09:32:19,None,None,None,None,None,None,None,None,None,None,None,None,None,12,2023-12-01 14:01:34,None,None,None,anne.mitcham@sbcfire.com,None,NaT,None,None,None,None,SBA,NaT,None,None,None,None,2023,None,NaN,None,None,None,None,None,2023-12-01,NaN,None,None,34.860787,None,93455,Habitable,None,None,None,None,None,2.0,anne.mitcham@sbcfire.com,None,None,"POLYGON ((-39719.563 -350572.198, -39740.188 -...",None,None,None,NaT,2023-12-01 14:01:42,None,None,Jullien Drive,2,Email,None,None,Santa Maria,None,None,CA,None,None,None,Not Observed,None,None,Compliant,c5c84bb9-c0e3-42c2-8d1b-895bc56f2f12,None,None,None,None,None,None,None,None,None,None,None,None,SBC,None,None,None,None,None,206 Jullien Drive Santa Maria Santa Barbara CA...,None,None,None,None,A,None,None,None,67580,None,None,Tim,Santa Barbara,335,None,None,None,None,None,NaN,-120.434805,None,NaT,2023-12-01,None,None,None,None,2023-12-01 09:32:18,None,None,None,Prevention,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,None,NaN,None,None,None,Yes,None,None,Defensible Space Inspection Report,None,None,None,None,None,No,15,None,None,NaN,None,None,None,None,None,None,2023-12-01,None,None

In [23]:
# Sort columns alphabetically
buffer_inspections = buffer_inspections[sorted(buffer_inspections.columns)]

# Reorder columns
front_cols = ["inspection_id", "status", "year", "month"]
end_col   = ["geometry"]
middle_cols = [c for c in buffer_inspections.columns
               if c not in (*front_cols, *end_col)]
buffer_inspections = buffer_inspections[front_cols + middle_cols + end_col]

buffer_inspections

,inspection_id,status,year,month,Date,a_removebr,a_removebranchesfromstovepipe,accessegre,accessegress,address__1,address__2,address_ad,address_admin_area,address_co,address_country,address_fu,address_full,address_lo,address_locality,address_po,address_postal_code,address_su,address_sub_admin_area,address_sub_thoroughfare,address_suite,address_th,address_thoroughfare,addressvis,addressvisible,apn,appenddate,assigned_t,assigned_to,b_removele,b_removeleavesneedlesveg,battalion,c_removede,c_removedeaddyingtrees,calculat_1,calculat_2,calculat_3,calculat_4,calculated,calculateddate,calculatededitdate,calculatededitor,calculatedglobalid,calculateduid,calfireuni,calfireunit,can_engine,can_engine_access_water_source,citationda,citationnu,citationnumber,clearreins,comments,community,community_,community_other,core_with_,coredata,coredatafl,county,created_at,created_by,createdby,createddat,creationda,creationdate,creator,d_removede,d_removedeaddyinggrassplants,deadtrees3,deckporche,deckporchelevated,deckporchg,deckporchgrade,deliveryno,deliverynotificationmethod,e_removedy,e_removefl,e_removeflammablegroundcover,eaves,editdate,editedby,editeddate,editor,editstatus,enginenumb,enginenumber,escalateto,escalatetocoordinator,exteriorsi,exteriorsiding,f_removefl,f_removeflammablevegetation,fenceattac,fenceattachedtostructure,firescopei,firescopeid,fulcrum_id,g_relocate,g_relocateexposedwoodpiles,gatecode,globalid,h_cutannua,h_cutannualgrassesforbs,i_reducefu,i_removefu,i_removefuelsusingctguidelines,inspecti_1,inspecti_2,inspecti_3,inspection,inspectioncount,inspectiondate_calculate,inspectionhours,inspectionstatus,inspectorfirstname,inspectorlastname,inspectorp,inspectorposition,j_allexpos,j_exposedw,j_exposedwoodpiles,k_deaddyin,k_removede,k_removedeaddyingwoodyfuels,keyid,l_logsstum,l_removelo,l_removelogstumpsembeddedsoil,latitude,le100numbe,le100number,longitude,m_outbuild,m_outbuildingsliquidpropanegas,n_addressd,n_displaya,n_displayaddresscontrasting,nonhabitab,nonhabitableoutbuildings,number_of_,number_of_dead_trees_within_300_ft_of_residence,numberfi_1,numberfiel,numberfield1,numberfield2,numberofst,numberofstructures,o_chimneys,o_stovepip,o_stovepipemetalscreenopenings,occupantho,occupanthome,partner_di,patiocover,patiocovercarport,photoid,photoid_ca,photoid_caption,photoid_url,prevention_inspectorfirstname,prevention_inspectorfirstname_other,prevention_inspectorlastname,prevention_inspectorlastname_other,previous_1,previousyr,previousyrinspecteddata,previousyrinspectionstatus,principal_,project,propanetan,propanetankdistance,propertyst,propertystatus,recommend_,recommendc,recommendclearvegetation,reinspecti,reinspectiondate,report_tit,report_title,responsibi,roofconstr,roofconstruction,shift,shift_juli,shift_julian,siteaddres,siteaddress,stationn_1,stationnam,stationname,structureh,structurehabitable,structuret,structuretype,system_cre,system_created_at,system_upd,system_updated_at,textfield1,textfield2,updated_at,updated_by,utilitym_1,utilitymis,utilitymiscstructuredistance,utilitymiscstucturecount,ventscreen,version,water_comm,water_comments,water_sour,water_source,water_stor,water_storage_size_stored_water_on_individual_parcels_only,waterstora,windowpane,yearbuilt,geometry
0,1,Compliant,2019,6,2019-06-05,None,None,yes,None,None,Santa Barbara,CA,None,US,None,3462 Brinkerhoff Rd Santa Ynez Santa Barbara C...,None,Santa Ynez,None,93460,None,3462,None,None,None,Brinkerhoff Rd,None,Yes - Without Reflective,None,141-010-040,2019-06-05,None,None,None,None,2,None,None,None,None,None,None,None,None,None,None,None,None,SBC,None,yes,None,None,None,None,None,None,Woodstock,None,None,None,None,None,SBA,2018-05-25 16:25:06,None,None,None,NaT,NaT,None,None,None,0,No Deck/Porch,None,No Deck/Porch,None,Hardcopy,None,None,None,None,Unenclosed,NaT,None,None,None,None,32,NaN,None,None,Wood,None,None,None,No Fence,None,None,None,d9a4d031-d16d-4c84-b32c-f3fcd7d945df,None,None,None,None,None,None,None,None,None,30 min,0.0,NaN,2019-06-05,None,NaT,None,None,None,None,DSI,None,None,None,None,None,None,None,NaN,None,None,None,34.669616,0.0,None,-120.031160,None,None,None,None,None,0,None,NaN,NaN,0.0,0.0,None,None,0.0,None,None,None,None,Yes,None,None,No Patio Cover/Carport,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,>30',None,None,None,None,None,None,NaT,NaT,Defensible Space Inspection Report,None,None,Metal,None,None,None,None,None,None,None,32,None,None,None,Utility or Miscellaneous Structure > 120 sqft,None,2019-05-07 11:52:36,NaT,2019-06-05 16:35:26,NaT,None,None,2019-06-05 11:57:49,None,0,30-50',None,None,No Vents,2.0,None,None,Private Hydrant- Private Stored Water,None,Over 5000 gallons,None,yes,No Windows,2000.0,"POLYGON ((-2813.179 -371821.557, -2813.179 -37..."
1,2,Compliant,2019,5,2019-05-09,None,None,yes,None,None,Santa Barbara,CA,None,US,None,3290 Avenida Caballo Santa Ynez Santa Barbara ...,None,Santa Ynez,None,93460,None,3290,None,None,None,Avenida Caballo,None,Yes - Without Reflective,None,135-310-022,2019-05-09,None,None,None,None,2,None,None,None,None,None,None,None,None,None,None,None,None,SBC,None,yes,None,None,None,None,None,None,Woodstock,None,None,None,None,None,SBA,2018-05-25 16:25:10,None,None,None,NaT,NaT,None,None,None,None,No Deck/Porch,None,No Deck/Porch,None,Email,None,None,None,None,No Eaves,NaT,None,None,None,None,32,NaN,None,None,Wood,None,None,None,No Fence,None,None,None,7f9b6d98-548d-4b94-97c6-82cbddf84d99,None,None,None,None,None,None,None,None,None,15 min,0.0,NaN,2019-05-09,None,NaT,None,None,None,None,DSI,None,None,None,None,None,None,None,NaN,None,None,None,34.679129,0.0,None,-120.091914,None,None,None,None,None,0,None,NaN,NaN,0.0,0.0,None,None,0.0,None,None,None,None,No,None,None,No Patio Cover/Carport,None,f1556c16-78c8-44bf-b6ce-a7ddb5908d96,None,None,None,None,None,None,None,None,None,None,None,None,None,Not Applicable,None,None,None,None,None,None,NaT,NaT,Defensible Space Inspection Report,None,None,Metal,None,None,None,None,None,None,None,Santa Ynez Valley (Outside Engine Co. Area),None,None,None,Single Family Residence Multi Story,None,2019-05-07 11:52:37,NaT,2019-05-15 12:26:45,NaT,None,None,2019-05-15 12:26:44,None,1,30-50',None,None,No Vents,3.0,None,None,Private Hydrant- Private Stored Water,None,None,None,yes,Single Pane,0.0,"POLYGON ((-8368.416 -370860.259, -8475.394 -37..."
2,3,Compliant,2019,5,2019-05-09,None,None,yes,None,None,Santa Barbara,CA,None,US,None,3350 Caballo Ln Santa Ynez Santa Barbara CA 93...,None,Santa Ynez,None,93460,None,3350,None,None,None,Caballo Ln,None,Yes - Without Reflective,None,135-310-075,2019-05-09,None,None,None,None,2,None,None,None,None,None,None,None,None,None,None,None,None,SBC,None,None,None,None,None,None,None,None,Woodstock,None,None,None,None,None,SBA,2018-05-25 16:25:11,None,None,None,NaT,NaT,None,None,None,None,No Deck/Porch,None,No Deck/Porch,None,Email,None,None,None,None,Unenclosed,NaT,None,None,None,None,32,NaN,None,None,Stucco/Brick/Cement,None,None,None,No Fence,None,None,None,03afdf39-173a-4f02-bfdc-e0725e554959,None,None,None,None,None,None,None,None,None,15 min,0.0,NaN,2019-05-09,None,NaT,None,None,None,None,DSI,None,None,None,None,None,None,None,NaN,None,None,None,34.676197,0.0,None,-120.089553,None,None,None,None,None,0,None,NaN,NaN,0.0,0.0,None,None,0.0,None,None,None,None,No,None,None,No Patio Cover/Carport,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Not Applicable,None,None,None,None,None,None,NaT,NaT,Defensible Space Inspection Report,None,None,Tile,None,None,None,None,None,None,None,Santa Ynez Valley (Outside Engine Co. Area),None,None,None,Single Family Residence Multi Story,None,2019-05-07 11:52:37,NaT,2019-05-09 15:26:24,NaT,None,None,2019-05-09 14:20:04,None,2,>50',None,None,No Vents,2.0,None,None,None,None,None,None,None,Multi Pane,0.0,"POLYGON ((-8253.618 -371073.707, -8136.129 -37..."
3,4,Compliant,2019,5,2019-05-09,None,None,yes,None,None,Santa Barbara,CA,None,US,None,3350 Caballo Ln Santa Ynez Santa Barbara CA 93...,None,Santa Ynez,None,93460,None,3350,None,None,None,Caballo Ln,None,Yes - Without Reflective,None,135-310-075,2019-05-09,None,None,None,None,2,None,None,None,None,None,None,None,None,None,None,None,None,SBC,None,None,None,None,None,None,None,None,Woodstock,None,None,None,None,None,SBA,2018-05-25 16:25:11,None,None,None,NaT,NaT,None,None,None,None,No Deck/Porch,None,Masonry/Concrete,None,Email,None,None,None,None,Unenclosed,NaT,None,None,None,None,32,NaN,None,None,Metal,None,None,None,No Fence,None,None,None,941e29b0-6cd3-4c7e-a919-b8f2410b4a2b,None,None,None,None,None,None,None,None,None,15 min,0.0,NaN,2019-05-09,None,NaT,None,None,None,None,DSI,None,None,None,None,None,None,None,NaN,None,None,None,34.677982,0.0,None,-120.088944,None,None,None,None,None,0,None,NaN,NaN,0.0,0.0,None,None,0.0,None,None,None,None,Yes,None,None,No Patio Cover/Carport,None,17322007-d5d1-4568-bde6-00ae169a0bbf,None,None,None,None,None,None,None,None,None,None,None,None,None,Not Applicable,None,None,None,None,None,None,NaT,NaT,Defensible Space Inspection Report,None,None,Metal,None,None,None,None,None,None,None,Santa Ynez Valley (Outside Engine Co. Area),None,None,None,Utility or Miscellaneous Structure > 120 sqft,None,2019-05-07 11:52:38,NaT,2019-05-09 15:26:26,NaT,None,None,2019-05-09 14:25:18,None,0,None,None,None,No Vents,2.0,None,None,None,None,None,None,no,Single Pane,0.0,"POLYGON ((-8201.866 -370989.432, -8201.866 -37..."
4,5,Compliant,2019,12,2019-12-17,None,None,yes,None,None,Santa Barbara,CA,None,US,None,3320 A Canada Este Rd Santa Ynez Santa Barbara...,None,Santa Ynez,None,93460,None,3320 A,None,None,None,Canada Este Rd,None,Yes - Without Reflective,None,135-310-042,2019-05-08,None,None,None,None,2,None,None,None,None,None,None,None,None,None,None,None,None,SBC,None,None,None,None,None,None,None,None,Woodstock,None,None,None,None,None,SBA,2018-05-25 16:25:11,None,None,None,NaT,NaT,None,None,None,None,No Deck/Porch,None,Masonry/Concrete,None,Hardcopy,None,None,None,None,Unenclosed,NaT,None,None,None,None,32,NaN,None,None,Wood,None,None,None,No Fence,None,None,None,abe890ba-3269-4ef6-84d7-4a9b6bfd717e,None,None,None,None,None,None,None,None,None,5 min,0.0,NaN,2019-12-17,None,NaT,None,None,None,None,DSI,None,None,None,None,None,None,None,NaN,None,None,None,34.678469,0.0,None,-120.087539,None,None,None,None,None,0,None,NaN,NaN,0.0,0.0,None,None,0.0,None,None,None,None,No,None,None,Non Combustible,None,50114b4c-e04a-4054-bd54-5a7dbca535af,None,None,None,None,None,None,None,None,None,None,None,None,None,>30',None,None,None,None,None,None,NaT,NaT,Defensible Space Inspection Report,None,None,Asphalt,None,None,None,None,None,None,None,Santa Ynez Valley (Outside Engine Co. Area),None,None,None,Single Family Residence Multi Story,None,2019-05-07 11:52:38,NaT,2019-12-18 11:43:23,NaT,None,None,2019-12-17 14:16:14,None,0,None,None,None,"Mesh Screen > 1/8""",5.0,None,None,Pond,None,None,None,yes,Single Pane,2002.0,"POLYGON ((-7966.144 -370818.558, -7966.144 -37..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67575,67576,Compliant,2023,10,2023-10-31,None,None,None,Yes,None,None,None,CA,None,None,None,2114 Fallen Leaf Drive Santa Maria Santa Barba...,None,Santa Maria,None,93455,None,Santa Barbara,2114,None,None,Fallen Leaf Drive,None,None,129-132-001,NaT,None,None,None,None,2,None,None,None,None,None,None,None,None,None,None,None,None,None,SBC,None,None,None,None,None,None,None,None,None,None,None,None,None,SBA,2023-10-30 16:45:17,anne.mitcham@sbcfire.com,None,None,NaT,2023-10-30,None,None,None,None,None,None,None,None,None,Email,None,None,None,None,2023-10-30,None,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,3b9d56ac-899c-440d-8370-9ec2636cc40f,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,2023-10-31,15,None,None,None,None,Prevention,None,None,None,None,None,None,NaN,None,None,None,34.870960,NaN,None,-120.382833,None,None,None,None,None,None,None,NaN,0.0,NaN,NaN,None,None,NaN,None,None,None,None,None,No,None,None,None,None,None,None,None,Tim,None,Gailey,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaT,NaT,None,Defensible Space Inspection Report,None,None,None,C,None,310,None,None,None,None,26,None,Habitable,None,Single Family Residence Multi Story,NaT,2023-10-30 16:45:18,NaT,2023-11-06 13:09:08,None,None,2023-11-06 13:09:08,anne.mitcham@sbcfire.com,None,None,None,None,"Mesh Screen <= 1/8""",2.0,None,None,None,None,None,None,None,None,NaN,"POLYGON ((-34938.314 -349478.543, -34991.669 -..."
67576,67577,Compliant,2023,11,2023-11-15,None,None,None,Yes,None,None,None,CA,None,None,None,1600 East Clark Space 158 Orcutt Santa Barba...,None,Orcutt,None,93455,None,Santa Barbara,1600,Space 158,None,East Clark,None,None,129-280-026,NaT,None,None,None,None,2,None,None,None,None,None,None,None,None,None,None,None,None,None,SBC,None,None,None,None,None,None,None,Orcutt,None,None,None,None,None,SBA,2023-11-15 13:38:59,anne.mitcham@sbcfire.com,None,None,NaT,2023-11-15,None,None,None,None,None,None,None,None,None,Email,None,None,None,None,2023-11-15,None,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,5ba57641-41b8-4d9c-adee-098dbe4876b0,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,2023-11-15,15,None,None,None,None,Prevention,None,None,None,None,None,None,NaN,None,None,None,34.863251,NaN,None,-120.399151,None,None,None,None,None,None,None,NaN,0.0,NaN,NaN,None,None,NaN,None,None,None,None,None,No,None,None,None,None,None,None,None,Tim,None,Gailey,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaT,NaT,None,Defensible Space Inspection Report,None,None,None,C,None,319,None,None,None,None,None,None,Habitable,None,None,NaT,2023-11-15 13:38:59,NaT,2023-11-15 14:21:12,None,None,2023-11-15 14:21:12,anne.mitcham@sbcfire.com,None,None,None,None,"Mesh Screen <= 1/8""",2.0,None,None,None,None,None,None,None,None,NaN,"POLYGON ((-36511.881 -350331.419, -36511.881 -..."
67577,67578,Compliant,2023,11,2023-11-15,None,None,None,Yes,None,None,None,CA,None,None,None,3210 Santa Maria Way Space 153 Orcutt Santa B...,None,Orcutt,None,93455,None,Santa Barbara,3210,Space 153,None,Santa Maria Way,None,None,109-200-026,NaT,None,None,None,None,2,None,None,None,None,None,None,None,None,None,None,None,None,None,SBC,None,None,None,None,None,None,None,Orcutt,None,None,None,None,None,SBA,2023-11-15 14:49:40,anne.mitcham@sbcfire.com,None,None,NaT,2023-11-15,None,None,None,None,None,None,None,None,None,Email,None,None,None,None,2023-11-15,None,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,bd357572-7828-4f55-b827-fc4d63d0f69b,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,2023-11-15,15,None,None,None,None,Prevention,None,None,None,None,None,None,NaN,None,None,None,34.901260,NaN,None,-120.424188,None,None,None,None,None,None,None,NaN,0.0,NaN,NaN,None,None,NaN,None,None,None,None,None,No,None,None,None,None,None,None,None,Tim,None,Gailey,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaT,NaT,None,Defensible Space Inspection Report,None,None,None,A,None,324,None,None,None,None,None,None,Habitable,None,Mobile Home Double Wide,NaT,2023-11-15 14:49:41,NaT,2023-11-20 10:27:12,None,None,2023-11-20 10:27:11,anne.mitcham@sbcfire.com,None,None,None,None,"Mesh Screen <= 1/8""",3.0,None,None,None,None,None,None,None,None,NaN,"POLYGON ((-38702.857 -346029.921, -38702.857 -..."
67578,67579,Compliant,2023,11,2023-11-15,None,None,None,Yes,None,None,None,CA,None,None,None,3210 Santa Maria Way Space 153 Orcutt Santa Ba...,None,Orcutt,None,93455,None,Santa Barbara,3210,Space 153,None,Santa Maria Way,None,None,109-200-023,NaT,None,None,None,None,2,None,None,None,None,None,None,None,None,None,None,None,None,None,SBC,None,None,None,None,None,None,None,Orcutt,None,None,None,None,None,SBA,2023-11-15 14:59:11,anne.mitcham@sbcfire.com,None,None,NaT,2023-11-15,None,None,None,None,None,None,None,None,None,Email,None,None,None,None,2023-11-15,None,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,9830aba3-0c5e-4fa4-a704-d565da2f8519,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,2023-11-15,15,None,None,None,None,Engine,None,None,None,None,None,None,NaN,None,None,None,34.900785,NaN,None,-120.426280,None,None,None,None,None,None,None,NaN,0.0,NaN,NaN,None,None,NaN,None,None,None,None,None,No,None,None,None,None,None,None,None,Tim,None,Gailey,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaT,NaT,None,Defensible Space Inspection Report,None,None,None,C,None,319,None,None,None,None,None,None,Habitable,None,Mobile Home Double Wide,NaT,2023-11-15 14:59:17,NaT,2023-11-15 16:18:32,None,None,2023-11-15 16:18:32,anne.mitcham@sbcfire.com,None,None,None,None,"Mesh Screen <= 1/8""",2.0,None,None,None,None,None,None,None,None,NaN,"POLYGON ((-38988.592 -346062.709, -38884.895 -..."
67579,67580,Compliant,2023,12,2023-12-01,None,None,None,Yes,None,None,None,CA,None,None,None,206 Jullien Drive Santa Maria Santa Barbara CA...,None,Santa Maria,None,93455,None,Santa Barbara,206,None,None,Jullien Drive,None,None,103-192-003,NaT,None,None,None,None,2,None,None,None,None,None,None,None,None,None,None,None,None,None,SBC,None,None,None,None,None,None,None,Rice Ranch,None,None,None,None,None,SBA,2023-12-01 09:32:18,anne.mitcham@sbcfire.com,None,None,NaT,2023-12-01,None,None,None,None,None,None,None,None,None,Email,None,None,None,None,2023-12-01,None,None,None,None,None,NaN,None,None,None,None,None,None,None,None,None,None,c5c84bb9-c0e3-42c2-8d1b-895bc56f2f12,None,None,None,None,None,None,None,None,None,None,None,NaN,None,None,2023-12-01,15,None,None,None,None,Prevention,None,None,None,None,None,None,NaN,None,None,None,34.860787,NaN,None,-120.434805,None,None,None,None,None,None,None,NaN,0.0,NaN,NaN,None,None,NaN,None,None,None,None,None,No,None,None,None,None,None,None,None,Tim,None,Gailey,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaT,NaT,None,Defensible Space Inspection Report,None,None,None,A,None,335,None,None,None,None,21,None,Habitable,None,Single Family Residence Single Story,NaT,2023-12-01 09:32:19,NaT,2023-12-01 14:01:42,None,None,2023-12-01 14:01:34,anne.mitcham@sbcfire.com,None,None,None,None,Not Observed,2.0,None,None,None,None,None,None,None,None,NaN,"POLYGON ((-39719.563 -350572.198, -39740.188 -..."

In [24]:
# Write to file
buffer_inspections.to_file(
    os.path.join(config.data_dir, "PUZZLE_PIECES", "inspections_master.geojson"),
    driver="GeoJSON",
)

## Check that the inpection ids match for training geometry and buffer geometries

In [25]:
# Create dataframe of just compliance status and inspection_id
status_training = training_inspections.reindex(columns=["inspection_id", "status"])
status_training["status"] = status_training["status"].map(
    {"Compliant": 0, "Non-Compliant": 1}
)

In [26]:
status_buffer = buffer_inspections.reindex(columns=["inspection_id", "status"])
status_buffer["status"] = status_buffer["status"].map(
    {"Compliant": 0, "Non-Compliant": 1}
)

In [27]:
status_training_sorted = status_training.sort_values('inspection_id').reset_index(drop=True)
status_buffer_sorted = status_buffer.sort_values('inspection_id').reset_index(drop=True)
are_equal = status_training_sorted.equals(status_buffer_sorted)
are_equal

True