In [90]:
import os
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import geopandas as gpd
import rioxarray as rioxr
from shapely import box

import pystac_client
import planetary_computer

from IPython.display import Image

In [91]:
# Load one year of data
in23 = gpd.read_file(
    "/capstone/wildfire_prep/data/inspections_data/cleaned_status/inspections_2023.geojson"
)

In [96]:
# View only status and structuretype columns, to see what it looks like before the function.
# After the function, the 'structuretype' column will be gone, and the 'structure_code' column will replace it 

in23[['status', 'structuretype']]

          status                         structuretype
0      Compliant    Multi Family Residence Multi Story
1      Compliant  Single Family Residence Single Story
2      Compliant  Single Family Residence Single Story
3      Compliant   Single Family Residence Multi Story
4      Compliant  Single Family Residence Single Story
...          ...                                   ...
13368  Compliant   Single Family Residence Multi Story
13369  Compliant                                  None
13370  Compliant               Mobile Home Double Wide
13371  Compliant               Mobile Home Double Wide
13372  Compliant  Single Family Residence Single Story

[13373 rows x 2 columns]

In [93]:
def structuretype_codes(data):
    
    # Load structure codes from metadata folder: change path as needed
    codes = pd.read_csv(
        "/capstone/wildfire_prep/data/metadata/structuretype_codes.csv"
    ).rename(columns={"structure_type": "structuretype"})

    # Merging structure_codes.csv metadata to the given dataset, dropping extra 'structuretype' column after merge
    data = data.merge(
        codes[["structuretype", "structure_code"]],
        on="structuretype",
        how="left",
    ).drop(columns=["structuretype"])
    
    return data

In [94]:
test = structuretype_codes(in23)

In [99]:
test[["status", "structure_code"]]

          status  structure_code
0      Compliant             111
1      Compliant             102
2      Compliant             102
3      Compliant             101
4      Compliant             102
...          ...             ...
13368  Compliant             101
13369  Compliant             116
13370  Compliant             106
13371  Compliant             106
13372  Compliant             102

[13373 rows x 2 columns]