### Loading SB County Rainfall Data

- Rain gauge data downloaded from the hydrology section of the Santa Barbara County website
- Need to determine the number of rain gauges we are using data from

#### Steps
- Clean data from

In [1]:
# Load packages
import os
import sys
import numpy as np
import pandas as pd
import geopandas as gpd

import os
import sys

sys.path.append("../utils")

import config

In [2]:
# File paths to rain gauge data
file_list = [
    os.path.join(config.data_dir, "sb_rain_gauges", "155dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "156dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "196dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "197dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "198dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "200dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "204dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "205dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "208dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "210dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "211dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "212dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "218dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "220dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "221dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "226dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "227dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "228dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "229dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "230dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "231dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "232dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "233dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "234dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "236dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "237dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "238dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "242dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "249dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "251dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "252dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "255dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "256dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "259dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "262dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "270dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "275dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "276dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "280dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "285dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "290dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "300dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "301dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "304dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "309dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "314dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "317dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "321dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "325dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "326dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "328dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "332dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "334dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "335dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "336dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "347dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "349dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "352dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "353dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "356dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "359dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "361dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "369dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "380dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "383dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "387dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "389dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "391dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "393dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "398dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "402dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "408dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "411dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "415dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "419dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "421dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "429dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "436dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "438dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "439dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "440dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "470dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "473dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "474dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "477dailys.xls"),
    os.path.join(config.data_dir, "sb_rain_gauges", "565dailys.xls")
]

In [3]:
# Function to convert Degrees-Minutes-Seconds to Decimal Degrees
def dms_to_decimal(dms):
    degrees, minutes, seconds = map(int, dms.split('-'))
    return degrees + (minutes / 60) + (seconds / 3600)

In [4]:
def clean_rain_gauge_data(excel_file):
    #
    rain = pd.read_excel(excel_file, header = 9)

    #
    metadata = pd.read_excel(excel_file, nrows = 8, usecols="A")

    # Normalize column names: strip spaces, lowercase, and remove symbols
    rain.columns = rain.columns.str.strip().str.lower().str.replace(' ', '_')

    # Rename specific columns for consistency
    rename_map = {
        'stationid': 'station_id',
        'wy': 'water_year',
        'monthnum': 'month',
        'daily_rain': 'dailyrain',
        'daily_rainfall': 'dailyrain'  
    }
    rain.rename(columns=rename_map, inplace=True)
    
    # Creating `latitude`, `longitude`, and `elevation` columns
    rain[['lat', 'long', 'elevation']] = (metadata['County of Santa Barbara'].dropna()
                                           .loc[lambda x: x.str.startswith('L')]
                                           .iloc[0]
                                           .split(', '))                                     

    # Removing text from `latitude`, `longitude`, and `elevation` columns
    rain['lat'] = rain['lat'].apply(lambda x: x.replace('Lat ', '')).apply(dms_to_decimal)
    rain['long'] = rain['long'].apply(lambda x: x.replace('Long ', '')).apply(dms_to_decimal)
    rain['elevation'] = rain['elevation'].apply(lambda x: int(x.replace('Elev ', '').replace('ft', '')))

    # Turn `station_id` from numeric to string
    rain['station_id'] = rain['station_id'].astype(str)

    # Turn `year` from string to numeric
    rain['year'] = pd.to_numeric(rain['year'], errors='coerce')

    return rain

In [5]:
# Function to process a list of files and append them to a single DataFrame
def process_rain_gauges(file_list):
    # Initialize an empty DataFrame to append data
    rain_data = pd.DataFrame()
    
    for file_path in file_list:
        cleaned = clean_rain_gauge_data(file_path)
        rain_data = pd.concat([rain_data, cleaned], ignore_index=True)
    
    return rain_data

In [6]:
rain_data = process_rain_gauges(file_list)
rain_data

,station_id,water_year,year,month,day,dailyrain,code,lat,long,elevation,unnamed:_7
0,155,2019.0,2018.0,10.0,4.0,0.35,NaN,34.482778,119.637500,3450,NaN
1,155,2019.0,2018.0,10.0,5.0,0.14,NaN,34.482778,119.637500,3450,NaN
2,155,2019.0,2018.0,10.0,13.0,0.02,NaN,34.482778,119.637500,3450,NaN
3,155,2019.0,2018.0,11.0,22.0,0.61,NaN,34.482778,119.637500,3450,NaN
4,155,2019.0,2018.0,11.0,29.0,2.40,NaN,34.482778,119.637500,3450,NaN
...,...,...,...,...,...,...,...,...,...,...,...
185239,565,2024.0,2024.0,5.0,19.0,0.01,NaN,34.570833,119.732222,2870,NaN
185240,565,2024.0,2024.0,5.0,20.0,0.01,NaN,34.570833,119.732222,2870,NaN
185241,565,2024.0,2024.0,5.0,23.0,0.01,NaN,34.570833,119.732222,2870,NaN
185242,565,2024.0,2024.0,5.0,24.0,0.01,NaN,34.570833,119.732222,2870,NaN
185243,565,2024.0,2024.0,8.0,31.0,0.00,NaN,34.570833,119.732222,2870,NaN

In [7]:
rain_data = rain_data[(rain_data['year'] >= 2017) & (rain_data['year'] <= 2023)]
rain_data

,station_id,water_year,year,month,day,dailyrain,code,lat,long,elevation,unnamed:_7
0,155,2019.0,2018.0,10.0,4.0,0.35,NaN,34.482778,119.637500,3450,NaN
1,155,2019.0,2018.0,10.0,5.0,0.14,NaN,34.482778,119.637500,3450,NaN
2,155,2019.0,2018.0,10.0,13.0,0.02,NaN,34.482778,119.637500,3450,NaN
3,155,2019.0,2018.0,11.0,22.0,0.61,NaN,34.482778,119.637500,3450,NaN
4,155,2019.0,2018.0,11.0,29.0,2.40,NaN,34.482778,119.637500,3450,NaN
...,...,...,...,...,...,...,...,...,...,...,...
185187,565,2024.0,2023.0,12.0,21.0,3.02,NaN,34.570833,119.732222,2870,NaN
185188,565,2024.0,2023.0,12.0,22.0,2.29,NaN,34.570833,119.732222,2870,NaN
185189,565,2024.0,2023.0,12.0,24.0,0.01,NaN,34.570833,119.732222,2870,NaN
185190,565,2024.0,2023.0,12.0,30.0,0.67,NaN,34.570833,119.732222,2870,NaN
185191,565,2024.0,2023.0,12.0,31.0,0.01,NaN,34.570833,119.732222,2870,NaN