## Join SB County Rainfall Data to Buffered Buildings

In [1]:
# Load packages
import os
import sys
import numpy as np
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point

import os
import sys

sys.path.append("../utils")

import config

In [13]:
# Load building data
buffered_buildings = os.path.join(config.data_dir, "inspections_data", "cleaned_status_with_id", "inspections_buffbuild_no_2023.geojson")
buffered_buildings = gpd.read_file(buffered_buildings).drop('index_right', axis = 1)
buffered_buildings

,fulcrum_id,created_at,updated_at,system_cre,system_upd,version,status,project,assigned_t,latitude,...,previous_1,calculat_3,calculat_4,creationda,editdate,creator,editor,number_of_,shift_juli,geometry
0,683a87b1-c652-4554-b3ea-6c2e2dd7bff3,2018-05-25 16:40:24,2019-10-10 11:00:34,2019-05-28 16:18:04,2019-10-10 15:14:47,2.0,Compliant,None,None,34.608120,...,None,None,None,NaT,NaT,None,None,NaN,None,"POLYGON ((-9290.574 -378632.312, -9035.561 -37..."
1,b71460a8-5be1-4e30-89af-ff1b8a3199ca,2018-05-25 16:40:24,2020-07-10 10:22:13,2020-05-19 15:01:53,2020-07-10 10:22:15,2.0,Compliant,None,None,34.608120,...,None,None,None,2020-07-10,2020-07-10,None,None,NaN,None,"POLYGON ((-9290.574 -378632.312, -9035.561 -37..."
2,35eef80e-f2d4-477d-88ef-b9c5e87d34b8,2018-05-25 16:40:24,2021-07-08 12:33:30,2021-04-05 09:33:18,2021-07-08 14:25:02,2.0,Compliant,None,None,34.608120,...,None,None,None,2021-07-08,2020-07-10,None,None,0.0,None,"POLYGON ((-9290.574 -378632.312, -9035.561 -37..."
3,f9567f92-c24a-48a0-af66-124bd2e046e6,2022-04-05 13:50:56,2022-08-15 14:40:05,2022-04-05 13:50:56,2022-08-15 15:17:57,4.0,Compliant,None,None,34.608120,...,None,None,None,2022-08-15,2020-07-10,None,None,0.0,227,"POLYGON ((-9290.574 -378632.312, -9035.561 -37..."
4,1b796830-dc42-4cc0-a732-1d71350f5d23,2018-05-25 16:26:06,2020-07-09 10:36:14,2020-05-18 16:48:55,2020-07-09 10:36:16,2.0,Compliant,None,None,34.672202,...,None,None,None,2020-07-09,2020-07-09,None,None,NaN,None,"POLYGON ((-38766.251 -371421.02, -38538.65 -37..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34603,a0514032-3790-467c-b39b-35cedc0290f6,2022-07-13 16:35:12,2022-07-13 16:51:04,2022-07-13 16:41:28,2022-07-13 16:51:07,3.0,Compliant,None,None,34.857940,...,None,None,None,2022-07-13,2022-07-13,None,None,0.0,194,"POLYGON ((-39466.196 -350875.586, -39471.35 -3..."
34604,1f7faaf3-d67e-4746-885f-91d9fb156310,2022-04-06 09:58:21,2022-06-29 12:34:55,2022-04-06 09:58:21,2022-06-29 12:34:55,4.0,Compliant,None,None,34.454282,...,None,None,None,2022-06-29,2020-07-29,None,None,0.0,180,"POLYGON ((22007.218 -395742.615, 22004.059 -39..."
34605,1a410b3f-940a-41aa-967a-0a652fb989fc,2018-05-25 16:56:28,2020-07-29 10:44:08,2020-05-18 16:28:16,2020-07-29 10:44:10,2.0,Compliant,None,None,34.454282,...,None,None,None,2020-07-29,2020-07-29,None,None,NaN,None,"POLYGON ((22007.218 -395742.615, 22004.059 -39..."
34606,ab159d02-d93d-41bf-ba46-42850c6c5c7f,2018-05-25 16:56:28,2021-06-12 18:23:35,2021-04-05 08:55:38,2021-06-12 20:53:53,2.0,Compliant,None,None,34.454282,...,None,None,None,2021-06-12,2020-07-29,None,None,0.0,None,"POLYGON ((22007.218 -395742.615, 22004.059 -39..."
34607,1bcfcb43-59d7-4de2-b156-8794351c37f0,2018-05-25 16:56:28,2019-06-07 15:31:59,2019-05-28 15:19:48,2019-06-07 15:32:03,2.0,Compliant,None,None,34.454282,...,None,None,None,NaT,NaT,None,None,NaN,None,"POLYGON ((22007.218 -395742.615, 22004.059 -39..."

In [3]:
# Load rain data
rain_data = os.path.join(config.data_dir, "sb_rain_gauges", "rain_gauge_data.csv")
rain_data = pd.read_csv(rain_data)

In [4]:
# Convert rain_data to a GeoDataFrame
rain_gdf = gpd.GeoDataFrame(
    rain_data,
    geometry=gpd.points_from_xy(rain_data['long'], rain_data['lat']),
    crs=config.albers_crs
)
rain_gdf

,station_id,year,month,monthly_rain_total,lat,long,elevation,geometry
0,196.0,2017.0,1.0,7.49,34.694167,120.131667,1000,POINT (120.132 34.694)
1,196.0,2017.0,2.0,6.97,34.694167,120.131667,1000,POINT (120.132 34.694)
2,196.0,2017.0,3.0,0.81,34.694167,120.131667,1000,POINT (120.132 34.694)
3,196.0,2017.0,4.0,0.53,34.694167,120.131667,1000,POINT (120.132 34.694)
4,196.0,2017.0,5.0,0.37,34.694167,120.131667,1000,POINT (120.132 34.694)
...,...,...,...,...,...,...,...,...
4604,565.0,2023.0,8.0,0.51,34.570833,119.732222,2870,POINT (119.732 34.571)
4605,565.0,2023.0,9.0,0.02,34.570833,119.732222,2870,POINT (119.732 34.571)
4606,565.0,2023.0,10.0,0.01,34.570833,119.732222,2870,POINT (119.732 34.571)
4607,565.0,2023.0,11.0,0.44,34.570833,119.732222,2870,POINT (119.732 34.571)
4608,565.0,2023.0,12.0,7.87,34.570833,119.732222,2870,POINT (119.732 34.571)

In [14]:
# Check that the CRS match
if buffered_buildings.crs != rain_gdf.crs:
    buffered_buildings = buffered_buildings.to_crs(rain_gdf.crs)

In [16]:
closest_rain = gpd.sjoin_nearest(
    buffered_buildings,
    rain_gdf[['station_id', 'geometry']],
    distance_col='station_distance'
)
closest_rain

,fulcrum_id,created_at,updated_at,system_cre,system_upd,version,status,project,assigned_t,latitude,...,creationda,editdate,creator,editor,number_of_,shift_juli,geometry,index_right,station_id,station_distance
0,683a87b1-c652-4554-b3ea-6c2e2dd7bff3,2018-05-25 16:40:24,2019-10-10 11:00:34,2019-05-28 16:18:04,2019-10-10 15:14:47,2.0,Compliant,None,None,34.608120,...,NaT,NaT,None,None,NaN,None,"POLYGON ((-9290.574 -378632.312, -9035.561 -37...",390,208.0,378777.364849
0,683a87b1-c652-4554-b3ea-6c2e2dd7bff3,2018-05-25 16:40:24,2019-10-10 11:00:34,2019-05-28 16:18:04,2019-10-10 15:14:47,2.0,Compliant,None,None,34.608120,...,NaT,NaT,None,None,NaN,None,"POLYGON ((-9290.574 -378632.312, -9035.561 -37...",391,208.0,378777.364849
0,683a87b1-c652-4554-b3ea-6c2e2dd7bff3,2018-05-25 16:40:24,2019-10-10 11:00:34,2019-05-28 16:18:04,2019-10-10 15:14:47,2.0,Compliant,None,None,34.608120,...,NaT,NaT,None,None,NaN,None,"POLYGON ((-9290.574 -378632.312, -9035.561 -37...",439,208.0,378777.364849
0,683a87b1-c652-4554-b3ea-6c2e2dd7bff3,2018-05-25 16:40:24,2019-10-10 11:00:34,2019-05-28 16:18:04,2019-10-10 15:14:47,2.0,Compliant,None,None,34.608120,...,NaT,NaT,None,None,NaN,None,"POLYGON ((-9290.574 -378632.312, -9035.561 -37...",424,208.0,378777.364849
0,683a87b1-c652-4554-b3ea-6c2e2dd7bff3,2018-05-25 16:40:24,2019-10-10 11:00:34,2019-05-28 16:18:04,2019-10-10 15:14:47,2.0,Compliant,None,None,34.608120,...,NaT,NaT,None,None,NaN,None,"POLYGON ((-9290.574 -378632.312, -9035.561 -37...",425,208.0,378777.364849
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34607,1bcfcb43-59d7-4de2-b156-8794351c37f0,2018-05-25 16:56:28,2019-06-07 15:31:59,2019-05-28 15:19:48,2019-06-07 15:32:03,2.0,Compliant,None,None,34.454282,...,NaT,NaT,None,None,NaN,None,"POLYGON ((22007.218 -395742.615, 22004.059 -39...",4546,474.0,396370.523434
34607,1bcfcb43-59d7-4de2-b156-8794351c37f0,2018-05-25 16:56:28,2019-06-07 15:31:59,2019-05-28 15:19:48,2019-06-07 15:32:03,2.0,Compliant,None,None,34.454282,...,NaT,NaT,None,None,NaN,None,"POLYGON ((22007.218 -395742.615, 22004.059 -39...",4545,474.0,396370.523434
34607,1bcfcb43-59d7-4de2-b156-8794351c37f0,2018-05-25 16:56:28,2019-06-07 15:31:59,2019-05-28 15:19:48,2019-06-07 15:32:03,2.0,Compliant,None,None,34.454282,...,NaT,NaT,None,None,NaN,None,"POLYGON ((22007.218 -395742.615, 22004.059 -39...",4544,474.0,396370.523434
34607,1bcfcb43-59d7-4de2-b156-8794351c37f0,2018-05-25 16:56:28,2019-06-07 15:31:59,2019-05-28 15:19:48,2019-06-07 15:32:03,2.0,Compliant,None,None,34.454282,...,NaT,NaT,None,None,NaN,None,"POLYGON ((22007.218 -395742.615, 22004.059 -39...",4543,474.0,396370.523434
34607,1bcfcb43-59d7-4de2-b156-8794351c37f0,2018-05-25 16:56:28,2019-06-07 15:31:59,2019-05-28 15:19:48,2019-06-07 15:32:03,2.0,Compliant,None,None,34.454282,...,NaT,NaT,None,None,NaN,None,"POLYGON ((22007.218 -395742.615, 22004.059 -39...",4542,474.0,396370.523434

In [17]:
gpd.sjoin_nearest(buffered_buildings.head(5), rain_gdf[['station_id', 'geometry']], how='left')

,fulcrum_id,created_at,updated_at,system_cre,system_upd,version,status,project,assigned_t,latitude,...,calculat_4,creationda,editdate,creator,editor,number_of_,shift_juli,geometry,index_right,station_id
0,683a87b1-c652-4554-b3ea-6c2e2dd7bff3,2018-05-25 16:40:24,2019-10-10 11:00:34,2019-05-28 16:18:04,2019-10-10 15:14:47,2.0,Compliant,None,None,34.608120,...,None,NaT,NaT,None,None,NaN,None,"POLYGON ((-9290.574 -378632.312, -9035.561 -37...",390,208.0
0,683a87b1-c652-4554-b3ea-6c2e2dd7bff3,2018-05-25 16:40:24,2019-10-10 11:00:34,2019-05-28 16:18:04,2019-10-10 15:14:47,2.0,Compliant,None,None,34.608120,...,None,NaT,NaT,None,None,NaN,None,"POLYGON ((-9290.574 -378632.312, -9035.561 -37...",391,208.0
0,683a87b1-c652-4554-b3ea-6c2e2dd7bff3,2018-05-25 16:40:24,2019-10-10 11:00:34,2019-05-28 16:18:04,2019-10-10 15:14:47,2.0,Compliant,None,None,34.608120,...,None,NaT,NaT,None,None,NaN,None,"POLYGON ((-9290.574 -378632.312, -9035.561 -37...",439,208.0
0,683a87b1-c652-4554-b3ea-6c2e2dd7bff3,2018-05-25 16:40:24,2019-10-10 11:00:34,2019-05-28 16:18:04,2019-10-10 15:14:47,2.0,Compliant,None,None,34.608120,...,None,NaT,NaT,None,None,NaN,None,"POLYGON ((-9290.574 -378632.312, -9035.561 -37...",424,208.0
0,683a87b1-c652-4554-b3ea-6c2e2dd7bff3,2018-05-25 16:40:24,2019-10-10 11:00:34,2019-05-28 16:18:04,2019-10-10 15:14:47,2.0,Compliant,None,None,34.608120,...,None,NaT,NaT,None,None,NaN,None,"POLYGON ((-9290.574 -378632.312, -9035.561 -37...",425,208.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,1b796830-dc42-4cc0-a732-1d71350f5d23,2018-05-25 16:26:06,2020-07-09 10:36:14,2020-05-18 16:48:55,2020-07-09 10:36:16,2.0,Compliant,None,None,34.672202,...,None,2020-07-09,2020-07-09,None,None,NaN,None,"POLYGON ((-38766.251 -371421.02, -38538.65 -37...",422,208.0
4,1b796830-dc42-4cc0-a732-1d71350f5d23,2018-05-25 16:26:06,2020-07-09 10:36:14,2020-05-18 16:48:55,2020-07-09 10:36:16,2.0,Compliant,None,None,34.672202,...,None,2020-07-09,2020-07-09,None,None,NaN,None,"POLYGON ((-38766.251 -371421.02, -38538.65 -37...",454,208.0
4,1b796830-dc42-4cc0-a732-1d71350f5d23,2018-05-25 16:26:06,2020-07-09 10:36:14,2020-05-18 16:48:55,2020-07-09 10:36:16,2.0,Compliant,None,None,34.672202,...,None,2020-07-09,2020-07-09,None,None,NaN,None,"POLYGON ((-38766.251 -371421.02, -38538.65 -37...",453,208.0
4,1b796830-dc42-4cc0-a732-1d71350f5d23,2018-05-25 16:26:06,2020-07-09 10:36:14,2020-05-18 16:48:55,2020-07-09 10:36:16,2.0,Compliant,None,None,34.672202,...,None,2020-07-09,2020-07-09,None,None,NaN,None,"POLYGON ((-38766.251 -371421.02, -38538.65 -37...",452,208.0
4,1b796830-dc42-4cc0-a732-1d71350f5d23,2018-05-25 16:26:06,2020-07-09 10:36:14,2020-05-18 16:48:55,2020-07-09 10:36:16,2.0,Compliant,None,None,34.672202,...,None,2020-07-09,2020-07-09,None,None,NaN,None,"POLYGON ((-38766.251 -371421.02, -38538.65 -37...",451,208.0

In [ ]:
# Create a year and month column to merge the rain data by
closest_rain['year'] = closest_rain['date'].dt.year
closest_rain['month'] = closest_rain['date'].dt.month
closest_rain

In [ ]:
closest_rain = closest_rain.merge(
    rain_data,
    on=['station_id', 'year', 'month'],
    how='left'
)
closest_rain

In [ ]:
print(rain_data.dtypes)

In [ ]:
# Read to CSV
buffered_buildings_rain_data_joined = os.path.join(config.data_dir, "sb_rain_gauges", "buffered_buildings_rain_data_joined.csv")
closest_rain.to_csv(buffered_buildings_rain_data_joined, index=False)