## Join SB County Rainfall Data to Buffered Buildings

In [12]:
# Load packages
import os
import sys
import numpy as np
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point

import os
import sys

sys.path.append("../utils")

import config

In [3]:
# Load building data
buffered_buildings = os.path.join(config.data_dir, "PUZZLE_PIECES", "inspections_master.geojson")
buffered_buildings = gpd.read_file(buffered_buildings)
buffered_buildings

,address_ad,deckporche,occupantho,water_sour,propanetan,b_removeleavesneedlesveg,can_engine_access_water_source,reinspectiondate,numberfield1,e_removefl,...,textfield2,calculat_3,address_th,prevention_inspectorfirstname,calfireunit,stationname,e_removeflammablegroundcover,siteaddress,deliverynotificationmethod,geometry
0,CA,No Deck/Porch,Yes,Private Hydrant- Private Stored Water,>30',None,None,NaT,None,None,...,None,None,Brinkerhoff Rd,None,None,None,None,None,None,"POLYGON ((-2813.179 -371821.557, -2813.179 -37..."
1,CA,No Deck/Porch,No,Private Hydrant- Private Stored Water,Not Applicable,None,None,NaT,None,None,...,None,None,Avenida Caballo,None,None,None,None,None,None,"POLYGON ((-8368.416 -370860.259, -8475.394 -37..."
2,CA,No Deck/Porch,No,None,Not Applicable,None,None,NaT,None,None,...,None,None,Caballo Ln,None,None,None,None,None,None,"POLYGON ((-8253.618 -371073.707, -8136.129 -37..."
3,CA,No Deck/Porch,Yes,None,Not Applicable,None,None,NaT,None,None,...,None,None,Caballo Ln,None,None,None,None,None,None,"POLYGON ((-8201.866 -370989.432, -8201.866 -37..."
4,CA,No Deck/Porch,No,Pond,>30',None,None,NaT,None,None,...,None,None,Canada Este Rd,None,None,None,None,None,None,"POLYGON ((-7966.144 -370818.558, -7966.144 -37..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67575,None,None,None,None,None,None,None,NaT,None,None,...,None,None,None,Tim,SBC,26,None,None,Email,"POLYGON ((-34938.314 -349478.543, -34991.669 -..."
67576,None,None,None,None,None,None,None,NaT,None,None,...,None,None,None,Tim,SBC,None,None,None,Email,"POLYGON ((-36511.881 -350331.419, -36511.881 -..."
67577,None,None,None,None,None,None,None,NaT,None,None,...,None,None,None,Tim,SBC,None,None,None,Email,"POLYGON ((-38702.857 -346029.921, -38702.857 -..."
67578,None,None,None,None,None,None,None,NaT,None,None,...,None,None,None,Tim,SBC,None,None,None,Email,"POLYGON ((-38988.592 -346062.709, -38884.895 -..."
67579,None,None,None,None,None,None,None,NaT,None,None,...,None,None,None,Tim,SBC,21,None,None,Email,"POLYGON ((-39719.563 -350572.198, -39740.188 -..."

In [11]:
# 
buffered_buildings[['latitude', 'longitude']]

        latitude   longitude
0      34.669616 -120.031160
1      34.679129 -120.091914
2      34.676197 -120.089553
3      34.677982 -120.088944
4      34.678469 -120.087539
...          ...         ...
67575  34.870960 -120.382833
67576  34.863251 -120.399151
67577  34.901260 -120.424188
67578  34.900785 -120.426280
67579  34.860787 -120.434805

[67580 rows x 2 columns]

In [13]:
# Load rain data
rain_data = os.path.join(config.data_dir, "sb_rain_gauges", "rain_gauge_data.csv")
rain_data = pd.read_csv(rain_data)

In [14]:
# Convert rain_data to a GeoDataFrame
rain_gdf = gpd.GeoDataFrame(
    rain_data,
    geometry=gpd.points_from_xy(rain_data['long'], rain_data['lat']),
    crs=config.albers_crs
)
rain_gdf

,station_id,year,month,monthly_rain_total,lat,long,elevation,geometry
0,196.0,2017.0,1.0,7.49,34.694167,-120.131667,1000,POINT (-120.132 34.694)
1,196.0,2017.0,2.0,6.97,34.694167,-120.131667,1000,POINT (-120.132 34.694)
2,196.0,2017.0,3.0,0.81,34.694167,-120.131667,1000,POINT (-120.132 34.694)
3,196.0,2017.0,4.0,0.53,34.694167,-120.131667,1000,POINT (-120.132 34.694)
4,196.0,2017.0,5.0,0.37,34.694167,-120.131667,1000,POINT (-120.132 34.694)
...,...,...,...,...,...,...,...,...
4604,565.0,2023.0,8.0,0.51,34.570833,-119.732222,2870,POINT (-119.732 34.571)
4605,565.0,2023.0,9.0,0.02,34.570833,-119.732222,2870,POINT (-119.732 34.571)
4606,565.0,2023.0,10.0,0.01,34.570833,-119.732222,2870,POINT (-119.732 34.571)
4607,565.0,2023.0,11.0,0.44,34.570833,-119.732222,2870,POINT (-119.732 34.571)
4608,565.0,2023.0,12.0,7.87,34.570833,-119.732222,2870,POINT (-119.732 34.571)

In [16]:
# Convert buffered building to points instead of polygons
inspection_points = gpd.GeoDataFrame(
    buffered_buildings,
    geometry=gpd.points_from_xy(buffered_buildings['longitude'], buffered_buildings['latitude']),
    crs=config.albers_crs
)
inspection_points

,address_ad,deckporche,occupantho,water_sour,propanetan,b_removeleavesneedlesveg,can_engine_access_water_source,reinspectiondate,numberfield1,e_removefl,...,textfield2,calculat_3,address_th,prevention_inspectorfirstname,calfireunit,stationname,e_removeflammablegroundcover,siteaddress,deliverynotificationmethod,geometry
0,CA,No Deck/Porch,Yes,Private Hydrant- Private Stored Water,>30',None,None,NaT,None,None,...,None,None,Brinkerhoff Rd,None,None,None,None,None,None,POINT (-120.031 34.67)
1,CA,No Deck/Porch,No,Private Hydrant- Private Stored Water,Not Applicable,None,None,NaT,None,None,...,None,None,Avenida Caballo,None,None,None,None,None,None,POINT (-120.092 34.679)
2,CA,No Deck/Porch,No,None,Not Applicable,None,None,NaT,None,None,...,None,None,Caballo Ln,None,None,None,None,None,None,POINT (-120.09 34.676)
3,CA,No Deck/Porch,Yes,None,Not Applicable,None,None,NaT,None,None,...,None,None,Caballo Ln,None,None,None,None,None,None,POINT (-120.089 34.678)
4,CA,No Deck/Porch,No,Pond,>30',None,None,NaT,None,None,...,None,None,Canada Este Rd,None,None,None,None,None,None,POINT (-120.088 34.678)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67575,None,None,None,None,None,None,None,NaT,None,None,...,None,None,None,Tim,SBC,26,None,None,Email,POINT (-120.383 34.871)
67576,None,None,None,None,None,None,None,NaT,None,None,...,None,None,None,Tim,SBC,None,None,None,Email,POINT (-120.399 34.863)
67577,None,None,None,None,None,None,None,NaT,None,None,...,None,None,None,Tim,SBC,None,None,None,Email,POINT (-120.424 34.901)
67578,None,None,None,None,None,None,None,NaT,None,None,...,None,None,None,Tim,SBC,None,None,None,Email,POINT (-120.426 34.901)
67579,None,None,None,None,None,None,None,NaT,None,None,...,None,None,None,Tim,SBC,21,None,None,Email,POINT (-120.435 34.861)

In [18]:
# Check that the CRS match
if inspection_points.crs != rain_gdf.crs:
    inspection_points = inspection_points.to_crs(rain_gdf.crs)

In [22]:
# Try using thesian polygons to determine what rain gauges are nearest to each buffered building
closest_rain = gpd.sjoin_nearest(
    inspection_points,
    rain_gdf[['station_id', 'geometry']],
    distance_col='station_distance'
)
closest_rain

,address_ad,deckporche,occupantho,water_sour,propanetan,b_removeleavesneedlesveg,can_engine_access_water_source,reinspectiondate,numberfield1,e_removefl,...,prevention_inspectorfirstname,calfireunit,stationname,e_removeflammablegroundcover,siteaddress,deliverynotificationmethod,geometry,index_right,station_id,station_distance
0,CA,No Deck/Porch,Yes,Private Hydrant- Private Stored Water,>30',None,None,NaT,None,None,...,None,None,None,None,None,None,POINT (-120.031 34.67),4140,421.0,0.069204
0,CA,No Deck/Porch,Yes,Private Hydrant- Private Stored Water,>30',None,None,NaT,None,None,...,None,None,None,None,None,None,POINT (-120.031 34.67),4139,421.0,0.069204
0,CA,No Deck/Porch,Yes,Private Hydrant- Private Stored Water,>30',None,None,NaT,None,None,...,None,None,None,None,None,None,POINT (-120.031 34.67),4138,421.0,0.069204
0,CA,No Deck/Porch,Yes,Private Hydrant- Private Stored Water,>30',None,None,NaT,None,None,...,None,None,None,None,None,None,POINT (-120.031 34.67),4122,421.0,0.069204
0,CA,No Deck/Porch,Yes,Private Hydrant- Private Stored Water,>30',None,None,NaT,None,None,...,None,None,None,None,None,None,POINT (-120.031 34.67),4121,421.0,0.069204
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67579,None,None,None,None,None,None,None,NaT,None,None,...,Tim,SBC,21,None,None,Email,POINT (-120.435 34.861),134,198.0,0.025497
67579,None,None,None,None,None,None,None,NaT,None,None,...,Tim,SBC,21,None,None,Email,POINT (-120.435 34.861),133,198.0,0.025497
67579,None,None,None,None,None,None,None,NaT,None,None,...,Tim,SBC,21,None,None,Email,POINT (-120.435 34.861),132,198.0,0.025497
67579,None,None,None,None,None,None,None,NaT,None,None,...,Tim,SBC,21,None,None,Email,POINT (-120.435 34.861),131,198.0,0.025497
67579,None,None,None,None,None,None,None,NaT,None,None,...,Tim,SBC,21,None,None,Email,POINT (-120.435 34.861),130,198.0,0.025497

In [24]:
import numpy as np
from scipy.spatial import cKDTree
import pandas as pd

# Make sure both GeoDataFrames use the same projected CRS (for distance accuracy)
inspection_proj = inspection_points.to_crs(epsg=3857)
rain_proj = rain_gdf.to_crs(epsg=3857)

# Extract coordinates
inspection_coords = np.array(list(inspection_proj.geometry.apply(lambda geom: (geom.x, geom.y))))
rain_coords = np.array(list(rain_proj.geometry.apply(lambda geom: (geom.x, geom.y))))

# Build KDTree and query nearest
tree = cKDTree(rain_coords)
distances, indices = tree.query(inspection_coords, k=1)

# Extract matched rain station info
matched_rain = rain_gdf.iloc[indices].reset_index(drop=True)
matched_rain = matched_rain[['station_id']].copy()
matched_rain['station_distance'] = distances

# Join with original inspection_points
result = inspection_points.reset_index(drop=True).join(matched_rain)

result

,address_ad,deckporche,occupantho,water_sour,propanetan,b_removeleavesneedlesveg,can_engine_access_water_source,reinspectiondate,numberfield1,e_removefl,...,address_th,prevention_inspectorfirstname,calfireunit,stationname,e_removeflammablegroundcover,siteaddress,deliverynotificationmethod,geometry,station_id,station_distance
0,CA,No Deck/Porch,Yes,Private Hydrant- Private Stored Water,>30',None,None,NaT,None,None,...,Brinkerhoff Rd,None,None,None,None,None,None,POINT (-120.031 34.67),421.0,0.087951
1,CA,No Deck/Porch,No,Private Hydrant- Private Stored Water,Not Applicable,None,None,NaT,None,None,...,Avenida Caballo,None,None,None,None,None,None,POINT (-120.092 34.679),196.0,0.053971
2,CA,No Deck/Porch,No,None,Not Applicable,None,None,NaT,None,None,...,Caballo Ln,None,None,None,None,None,None,POINT (-120.09 34.676),196.0,0.058143
3,CA,No Deck/Porch,Yes,None,Not Applicable,None,None,NaT,None,None,...,Caballo Ln,None,None,None,None,None,None,POINT (-120.089 34.678),196.0,0.058012
4,CA,No Deck/Porch,No,Pond,>30',None,None,NaT,None,None,...,Canada Este Rd,None,None,None,None,None,None,POINT (-120.088 34.678),196.0,0.059474
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67575,None,None,None,None,None,None,None,NaT,None,None,...,None,Tim,SBC,26,None,None,Email,POINT (-120.383 34.871),349.0,0.042885
67576,None,None,None,None,None,None,None,NaT,None,None,...,None,Tim,SBC,None,None,None,Email,POINT (-120.399 34.863),349.0,0.055847
67577,None,None,None,None,None,None,None,NaT,None,None,...,None,Tim,SBC,None,None,None,Email,POINT (-120.424 34.901),198.0,0.039334
67578,None,None,None,None,None,None,None,NaT,None,None,...,None,Tim,SBC,None,None,None,Email,POINT (-120.426 34.901),198.0,0.036886
67579,None,None,None,None,None,None,None,NaT,None,None,...,None,Tim,SBC,21,None,None,Email,POINT (-120.435 34.861),198.0,0.032397

In [ ]:
# Create a year and month column to merge the rain data by
closest_rain['year'] = closest_rain['date'].dt.year
closest_rain['month'] = closest_rain['date'].dt.month
closest_rain

In [ ]:
closest_rain = closest_rain.merge(
    rain_data,
    on=['station_id', 'year', 'month'],
    how='left'
)
closest_rain

In [ ]:
print(rain_data.dtypes)

In [ ]:
# Read to CSV
buffered_buildings_rain_data_joined = os.path.join(config.data_dir, "sb_rain_gauges", "buffered_buildings_rain_data_joined.csv")
closest_rain.to_csv(buffered_buildings_rain_data_joined, index=False)